Create labeler.yml
fishtown-analytics/docs.getdbt.com pull request #1013
Opened 2022-01-12 22:38 UTC by runleonarun

## Description & motivation
This new workflow will size up PRs to make them easier to know how long it will take to review them. 

## To-do before merge

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [ ] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2022-01-12 23:16 UTC, joellabes commented on .github/workflows/labeler.yml
> +            YOu can also make it mor emanageable by only addressing one issue per PR or moving some changes to a separate branch.’
```suggestion
            You can also make it more manageable by only addressing one issue per PR or moving some changes to a separate branch.
```

2022-01-12 23:20 UTC, joellabes requested changes
😍 love it! 

Those sizes feel slightly oversized to me given that they're going to be prose instead of code. I might say 10, 50, 250, 500 lines for XS/S/M/L, but I don't have strong feelings about that at all. 

The only thing I'd say is that if all PRs fall into the same bucket (e.g. Small) then we don't gain a lot of signal, so it could be worth having a look at a handful of recent PRs and seeing what they would fall into. 

Requested changes are the typos in the warning message 📝

2022-01-12 23:35 UTC, runleonarun reviewed
Great point about it being text and lowering the thresholds, @joellabes. Let's try the numbers you proposed. We can always adjust if we need to.

2022-01-12 23:35 UTC, runleonarun commented on .github/workflows/labeler.yml
> +          s_max_size: '100'
```suggestion
          s_max_size: '50'
```

2022-01-12 23:35 UTC, runleonarun commented on .github/workflows/labeler.yml
> +          m_max_size: '500'
```suggestion
          m_max_size: '250'
```

2022-01-12 23:35 UTC, runleonarun commented on .github/workflows/labeler.yml
> +          l_max_size: '1000'
```suggestion
          l_max_size: '500'
```

2022-01-13 01:13 UTC, joellabes approved these changes
leshgoooooo

2022-01-13 16:54 UTC, merged