require-dbt-version docs reflect post-1.0 advice
fishtown-analytics/docs.getdbt.com pull request #1017
Opened 2022-01-13 04:46 UTC by joellabes

## Description & motivation
With the release of 1.0, our recommendations for require-dbt-version have changed - users can safely pin to major versions instead of minor (or, heaven forbid, a specific patch). 

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

2022-01-13 17:20 UTC, runleonarun requested changes
@joellabes This is great! Are you a mind reader? @jtcohen6 and I were just talking about changing this yesterday. 😍 

I just made some minor suggestions and I am going to rewrite the 1st paragraph to add more information. I will submit that separately.

2022-01-13 17:20 UTC, runleonarun commented on website/docs/reference/project-configs/require-dbt-version.md
> +Use an exact version number. In this example, this project will only run with dbt v0.21.1.
```suggestion
While you can restrict your project to run only with an exact version of dbt Core, we do not recommend this for dbt Core v1.0.0 and higher. 

In the following example, the project will only run with dbt v0.21.1. 
```

2022-01-13 17:20 UTC, runleonarun commented on website/docs/reference/project-configs/require-dbt-version.md
> +Use a comma separated list for an upper and lower bound. In this example, this project will run with dbt 1.x.x.
```suggestion
Use a comma separated list for an upper and lower bound. In the following example, this project will run with dbt 1.x.x.
```

2022-01-13 17:20 UTC, runleonarun commented on website/docs/reference/project-configs/require-dbt-version.md
> +Use a `>=` operator for a minimum boundary. In this example, this project will run with any version of dbt greater than or equal to 1.0.0.
```suggestion
Use a `>=` operator for a minimum boundary. In the following example, this project will run with any version of dbt greater than or equal to 1.0.0.
```

2022-01-13 17:22 UTC, runleonarun commented
@joellabes I added more [changes here](https://github.com/dbt-labs/docs.getdbt.com/pull/1017/commits/18ee6e9b2dcd897f60683b9a5cb4a42e071a1c6a). Do they look OK?

2022-01-13 22:22 UTC, joellabes commented
@runleonarun I tweaked it a bit - what you wrote was correct for why you should set a package bound in your `packages.yml` file, but this is a layer further back

2022-01-14 17:25 UTC, runleonarun approved these changes
This looks good to me. Let's merge it!

2022-01-14 20:24 UTC, merged