load time on task blog
fishtown-analytics/docs.getdbt.com pull request #1018
Opened 2022-01-13 14:45 UTC by jasnonaz

Load Time on Task Blog

2022-01-13 16:36 UTC, krevitt requested changes
Love this post!  

Content + graphics are great, couple things I'd challenge us to improve here:

1) Scannability - some paragraphs are long / dense and there aren't many headers to break up the piece / make it navigable.

In particular, we jump in the intro right into how we're solving the problem (nested macros / calculation via subquery).  

Could we (in a similarly scannable way, with a header + bullets) introduce the problem itself (ignoring weekends + holidays)?  A quick google search for these topics (ignore weekends SQL, ignore holidays SQL, etc) will help us find how people are looking for answers on these problems, and thus how we'd want to frame them in headers / bullets.

2) Is "time on task" the right title framing here?  A google search returns education-focused content ("Increasing Time-on-Task and Student Engagement") - is there something else that people call this at work?

2022-01-27 16:23 UTC, jasnonaz commented
@krevitt ready for another look. Added and reworked the intro to make it clearer what problem we're solving and added more scannability. I agree that measuring business hours is a very common way that people phrase this _problem,_ but I do think Time on Task is an elegant way to refer to the _solution_, Added more discussion and context around the problem which should hopefully help clear this up.

2022-02-01 18:59 UTC, krevitt approved these changes

2022-02-01 19:00 UTC, krevitt commented
@jasnonaz pushed a commit with some refinement to headers + the intro, otherwise looks great!

there also were some unintentional code formatting on paragraphs in the middle, removed that.

2022-02-03 19:41 UTC, merged