Add discourse comments
fishtown-analytics/docs.getdbt.com pull request #1069
Opened 2022-02-01 20:52 UTC by breezyfasano

## Description & motivation
Adding comments to the dev blog via Discourse embeds

2022-02-01 21:43 UTC, lfracalossiFA commented
I can see the Discourse embed! Is it okay to add comments to it?

2022-02-01 22:06 UTC, breezyfasano commented
> I can see the Discourse embed! Is it okay to add comments to it?

That is a very good question. I think yes! My only reservation is that it may or may not create something on the dbt Discourse's forums. But thats ok, we can delete any "testing" comments

2022-02-02 02:41 UTC, krevitt commented
Looks great!  A couple usability notes here:

* Discourse topics are unlisted (meaning they don't appear in the discourse feed), so we can feel free to test as needed.
![image](https://user-images.githubusercontent.com/77362861/152084674-608e1aac-e30c-4f87-86ba-69f869daeffa.png)

* One risk here is that Discourse posts are included in the sitemap ([sitemap here](https://discourse.getdbt.com/sitemap_1.xml))+ indexed by google - since they include the full text of the original post, if they were indexed this would count as duplicate content.  They don't appear in the sitemap (probably bc they're unlisted on Discourse), but we'll want to confirm before going live w/ this.

2022-02-02 15:36 UTC, JKarlavige commented
>     * One risk here is that Discourse posts are included in the sitemap ([sitemap here](https://discourse.getdbt.com/sitemap_1.xml))+ indexed by google - since they include the full text of the original post, if they were indexed this would count as duplicate content.  They don't appear in the sitemap (probably bc they're unlisted on Discourse), but we'll want to confirm before going live w/ this.

Did some digging on this, as I was thinking there's no way Discourse didn't think this through. Low and behold, it was indeed an issue, with the discussion [here](https://meta.discourse.org/t/add-option-to-set-canonical-url-to-embed-url/103915/13).

The fix was merged in back in 2020 ([PR Here](https://github.com/discourse/discourse/pull/9134/files)).

I believe we will have to check the option in Discourse > Settings > Posting > "Set the canonical URL for embedded topics to the embedded content's URL." to ensure the correct canonical is set.

2022-02-02 15:48 UTC, lfracalossiFA requested changes
Just wanted to add context here: I spoke with Breezy about the styling of the embed, and it looks like this can be controlled within the "embedded CSS" in the Discourse theme. So @breezyfasano I'm requesting changes based on that -- basically just making the "Start the Discussion" link, and any comments, match the docs styling.

2022-02-02 15:52 UTC, JKarlavige requested changes
All the code and functionality looks good! Just marking this for requested changes to ensure the canonical url/duplicate content issue Krevitt noted is tested and verified, whether it's using the Discourse setting or another solution.

2022-02-02 17:29 UTC, breezyfasano commented
Thanks for the comments and guidance folks :)
Update: I have styled the embed widget to match the docs styling a bit more, and I found the canonical URL setting in the backend! Requesting re-review.

![Screen Shot 2022-02-02 at 11 26 52 AM](https://user-images.githubusercontent.com/26210517/152205796-04b1a581-b07e-4bcc-9975-0f88d680f94a.png)

2022-02-02 17:53 UTC, JKarlavige approved these changes
lgtm! Can confirm the canonical urls on the Discourse post now point to the original domain from the embed
![image](https://user-images.githubusercontent.com/13647110/152209922-44cf9a1d-0058-44f0-a722-2dc62ce27490.png)

2022-02-04 14:33 UTC, lfracalossiFA requested changes
Hi Breezy,
This is looking more on brand! I think we're almost there. 

Any chance of using the Source Sans Pro font for that embed? I know we use it on Discourse, but I'm not sure if we have access to it in the embedded CSS. You could try adding `font-family: var(--font-family)` to the element in the embedded CSS, as it looks like it might already be set up as a CSS variable. If the variable doesn't work, you can try manually setting the font-family to `SourceSansPro, Arial, sans-serif `.

(As a total aside, I wonder if it might be nice to present that text as a button like we use on both docs and Discourse -- teal background, white text, flip the colors on hover. @krevitt any thoughts on if that's a good use of Breezy's time?)

2022-02-04 14:48 UTC, krevitt commented
Button styling would be great if it’s quick!  If it looks like it’ll be a drag we can skip it.

> On Feb 4, 2022, at 8:33 AM, Lise Fracalossi ***@***.***> wrote:
> 
> ﻿
> @lfracalossiFA requested changes on this pull request.
> 
> Hi Breezy,
> This is looking more on brand! I think we're almost there.
> 
> Any chance of using the Source Sans Pro font for that embed? I know we use it on Discourse, but I'm not sure if we have access to it in the embedded CSS. You could try adding font-family: var(--font-family) to the element in the embedded CSS, as it looks like it might already be set up as a CSS variable. If the variable doesn't work, you can try manually setting the font-family to SourceSansPro, Arial, sans-serif .
> 
> (As a total aside, I wonder if it might be nice to present that text as a button like we use on both docs and Discourse -- teal background, white text, flip the colors on hover. @krevitt any thoughts on if that's a good use of Breezy's time?)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-02-04 17:47 UTC, breezyfasano commented
Okie doke! I went ahead and matched the button styling to the coalesce CTA button on docs! Unfortunately, I couldn't get the font to pull in to the embed :( but I set it to arial, which is the fallback font on the main site for Source Sans Pro. Let me know what you think!

2022-02-04 19:01 UTC, lfracalossiFA commented
Hey @breezyfasano,
It looks like the button styling only applies to the "continue discussion" on posts that already have comments. The "Start Discussion" text looks like it's still text only. Can you take a look? 

Thanks!
Lise

2022-02-04 19:07 UTC, breezyfasano commented
Done and done!

2022-02-04 19:25 UTC, lfracalossiFA approved these changes
lgtm!

2022-02-04 19:31 UTC, merged

2022-02-04 19:32 UTC, breezyfasano commented
Thank you! Merging in, and will QA shortly

2022-02-10 14:36 UTC, gwenwindflower commented
I apologize for swooping in late with this, but we're fairly settled on the Community team with archiving Discourse and promoting GH Discussions as our centralized area for forum-like discussion as well as Stack Overflow-like question asking. I just would hate for this go live and then we archive Discourse in a month. Hopefully there's a way to swap out this or similar frontend interface but feed it [using the GH API](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions) instead of Discourse?



The primary concern here is that we want to consolidate the places where knowledge lives, which also maps to the places that the community and Community team need to monitor. Focusing this on GH consolidates knowledge and activity, minimizes surface area. Additionally, there would be a super helpfully transparent and connected record of the discussion and activity around a piece of knowledge's conception, creation, and continued life and growth after publish.

Super happy to discuss more on a call as this is a big change. Also definitely not something that needs to necessarily block this going live, but very much something I want y'all to be aware of, as it's very likely Discourse will be set it into a frozen archive state soon.

2022-02-10 14:44 UTC, lfracalossiFA commented
Hey @gwenwindflower -- let me swoop in with another consideration! This is the first I'm hearing of archiving Discourse, and in fact we have a plan to migrate it to the new dbt.com domain in two weeks! (See [here](https://www.notion.so/dbtlabs/getdbt-com-dbt-com-migration-c474d4076ae14042a4654e7ef0e7cf8a#96651489745b467bb1328b0b8995f493)). 

I have no strong feelings one way or another about this, but if we are archiving discourse.dbt.com, I think @krevitt needs to be aware of that, so that we can make a call not only on this PR (which has been merged but reverted), but also on the dbt.com migration runbook.