Add in airflow, dbt Cloud Provider into official ways to run dbt in production
fishtown-analytics/docs.getdbt.com pull request #1194
Opened 2022-03-02 17:06 UTC by sungchun12

## Description & motivation

Adding in a better way to interface airflow and dbt Cloud based on this pull request: https://github.com/apache/airflow/pull/20998

## To-do before merge

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

2022-04-04 21:55 UTC, mik-laj commented on website/docs/docs/running-a-dbt-project/running-dbt-in-production.md
> +* Invoking dbt through the [DbtCloudRunJobOperator](link to production docs in airflow).
```suggestion
* Invoking dbt through the [DbtCloudRunJobOperator](https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/operators.html).
```

2022-04-06 15:07 UTC, sungchun12 commented
@asteichen will officially own this PR

2022-04-06 15:10 UTC, sungchun12 commented
![image](https://user-images.githubusercontent.com/19176976/162007190-5718a24a-f493-4ae5-9d94-d29bd30388cc.png)
Have this official airflow provider be the first option.

Include a screenshot of Airflow DAG working AND dbt Cloud job that references the airflow DAG.

2022-04-07 17:51 UTC, sungchun12 reviewed
Check out my suggestions above!

2022-04-07 17:51 UTC, sungchun12 commented on website/docs/docs/running-a-dbt-project/running-dbt-in-production.md
> +* Invoking dbt through the [DbtCloudRunJobOperator](link to production docs in airflow).
I also recommend adding a link for the astronomer registry: https://registry.astronomer.io/providers/dbt-cloud?type=Sensors&utm_campaign=Monthly%20Product%20Updates&utm_medium=email&_hsmi=208603877&utm_content=208603877&utm_source=hs_email

2022-04-07 17:51 UTC, sungchun12 commented on website/docs/docs/running-a-dbt-project/running-dbt-in-production.md
> +* Invoking dbt through the [DbtCloudRunJobOperator](https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/operators.html). See the [Astronomer Registry](https://registry.astronome
```suggestion
* Invoking dbt through the [DbtCloudRunJobOperator](https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/operators.html). See the [Astronomer Registry](https://registry.astronomer.io/providers/dbt-cloud?type=Operators) to see an [example airflow DAG](https://registry.astronomer.io/dags/example-dbt-cloud) to get started!
```

2022-04-07 17:51 UTC, sungchun12 commented on website/docs/docs/running-a-dbt-project/running-dbt-in-production.md
> +<Lightbox src="/img/docs/running-a-dbt-project/airflow_dbt_connector.png" title="Airflow DAG using DbtCloudRunJobOperator"/>
The images look great!

2022-04-20 20:41 UTC, sungchun12 commented
@runleonarun any updates on this?

2022-04-22 18:51 UTC, sungchun12 commented
@dbt-labs/oss-maintainers Any review for this?

2022-05-05 20:03 UTC, krevitt requested changes
Looks like the [running dbt in production](https://docs.getdbt.com/docs/running-a-dbt-project/running-dbt-in-production#using-airflow) page was updated in another PR to include the provider + a link to the Astronomer guide.  

Want to resolve merge conflicts there @sungchun12?  Looks like this PR can resolve to adding the images.

2022-05-05 20:08 UTC, sungchun12 commented
@asteichen I'll let you take the lead to resolve conflicts!

2022-05-06 20:51 UTC, runleonarun commented
@sungchun12 sorry it's taken so long to get to this. I'm trying to get my GitHub notifications under control. Once those conflicts are resolved, I can approve!

2022-05-09 20:49 UTC, asteichen commented
@krevitt @runleonarun  I added the images, made the dbt Cloud operator the first bullet, and combined that description a bit.

2022-05-09 22:08 UTC, krevitt approved these changes
LGTM!

2022-05-10 14:37 UTC, sungchun12 commented
@asteichen you have the honor of officially merging this branch!

2022-05-10 15:12 UTC, merged