Fix step in dbt Cloud getting started
fishtown-analytics/docs.getdbt.com pull request #1624
Opened 2022-06-27 18:44 UTC by nghi-ly

## Description & motivation

Updated the code snippets in step 1 in https://docs.getdbt.com/guides/getting-started/building-your-first-project/build-your-first-models#change-the-way-your-model-is-materialized. 

Before Changes: 
![Screen Shot 2022-06-27 at 11 42 55 AM](https://user-images.githubusercontent.com/107218380/176013055-6189b163-4af5-4795-b862-abde379ef359.png)

After Changes: 
![Screen Shot 2022-06-27 at 11 43 11 AM](https://user-images.githubusercontent.com/107218380/176013105-823dcf9b-7b16-47e8-bd71-548d8d090f53.png)

## To-do before merge

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](../contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](../website/docs/docs/guides/migration-guide)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2022-06-27 18:58 UTC, nghi-ly commented
@lbenezra-FA : could you provide an eng review for technical accuracy? tysm!

2022-06-27 21:26 UTC, runleonarun approved these changes
This LGTM! Thank you for your first PR, Ly!! 🎉

2022-06-28 00:30 UTC, lbenezra-FA requested changes

2022-06-28 00:30 UTC, lbenezra-FA commented on website/snippets/tutorial-change-way-model-materialized.md
> +  - Replace the value for `models` with:
would edit to say: 
"- Replace the the project name under `models` with: "
since it's not quite a value for models.

2022-06-28 16:59 UTC, nghi-ly commented
@lbenezra-FA , thanks so much for the review! really appreciate the extra context it gave me. 

here's another idea for the word change:

![Screen Shot 2022-06-28 at 9 55 33 AM](https://user-images.githubusercontent.com/107218380/176238663-30a1ef68-d99b-4719-b303-a5412cf0ae19.png)

i think it reads better. wdyt? 

thanks!

2022-06-29 16:25 UTC, lbenezra-FA commented
> @lbenezra-FA , thanks so much for the review! really appreciate the extra context it gave me.
> 
> here's another idea for the word change:
> 
> ![Screen Shot 2022-06-28 at 9 55 33 AM](https://user-images.githubusercontent.com/107218380/176238663-30a1ef68-d99b-4719-b303-a5412cf0ae19.png)
> 
> i think it reads better. wdyt?
> 
> thanks!

Maybe change it to something like "Update your model config block to:" 
because really, you aren't updating the models, just the configuration the models in the project.

2022-06-29 16:38 UTC, nghi-ly commented
reads better. like it! incorporated the feedback, @lbenezra-FA ! good to go?

2022-06-29 16:40 UTC, lbenezra-FA approved these changes

2022-06-29 16:46 UTC, merged