Adding BigQuery label length req
fishtown-analytics/docs.getdbt.com pull request #1631
Opened 2022-06-28 15:48 UTC by leahwicz

## Description & motivation
Adding in a note about BigQuery enforcing a max length on labels. This has been a new error shown in dbt that people have hit. It would be ideal if they knew the limitation beforehand though so they can avoid the issue all together. 

Example issue: https://github.com/dbt-labs/dbt-bigquery/issues/202
Code where error message was added: https://github.com/dbt-labs/dbt-core/pull/3703

2022-06-28 17:12 UTC, McKnight-42 approved these changes
Looks like a good notifier

2022-06-28 18:14 UTC, runleonarun requested changes

2022-06-28 18:14 UTC, runleonarun commented on website/docs/reference/resource-configs/bigquery-configs.md
> +**Note:** Per BigQuery requirements, both key-value pair entries for labels have a maximum length of 63 characters.
Looks good, just adding our note format:

```suggestion
::: note
BigQuery requires that both key-value pair entries for labels have a maximum length of 63 characters.
:::
```

2022-06-28 20:10 UTC, runleonarun commented on website/docs/reference/resource-configs/bigquery-configs.md
> +:::note
```suggestion
:::info Note
```

2022-06-29 18:46 UTC, runleonarun approved these changes
🚢 it!

2022-06-29 18:46 UTC, merged