Update dry.md
fishtown-analytics/docs.getdbt.com pull request #1640
Opened 2022-06-29 19:38 UTC by johnblust

Updates DRY code glossary page content

2022-06-29 20:00 UTC, KiraFuruichi commented on website/docs/terms/dry.md
> +Let’s just say it: Writing DRY code is easier said than done. For classical software engineers, there’s a ton of resources out there to help them write DRY code. In the world of data transformation,
```suggestion
Let’s just say it: Writing DRY code is easier said than done. For classical software engineers, there’s a ton of resources out there to help them write DRY code. In the world of data transformation, there are also some tools and methodologies that can help folks in [the field of analytics engineering](https://www.getdbt.com/what-is-analytics-engineering/) write more DRY and [modular code](https://www.getdbt.com/analytics-engineering/modular-data-modeling-technique/).
```

2022-06-29 20:00 UTC, KiraFuruichi commented on website/docs/terms/dry.md
> +CTEs are a great way to help you write more DRY code in your data analysis and dbt models. In a formal sense, a CTE is a temporary results set that can be used in a query. In a much more human and pr
Can we add a link/hover to CTE glossary page here?

2022-06-29 20:00 UTC, KiraFuruichi commented on website/docs/terms/dry.md
> +View [materializations](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/materializations) are also extremely useful for abstracting code that might otherwise be repeated often. A
Can we link/hover to View glossary page here?

2022-06-29 20:01 UTC, KiraFuruichi commented on website/docs/terms/dry.md
> +  from {{ ref(‘users’) }}
```suggestion
  from {{ ref('users') }}
```

2022-06-29 20:03 UTC, KiraFuruichi requested changes
Hell yessss looks great, thanks for getting this up! Left a few minor edits.

2022-06-30 13:02 UTC, johnblust commented
Thanks for the review, Kira! Should be good to go now

2022-06-30 14:29 UTC, KiraFuruichi approved these changes

2022-06-30 15:10 UTC, merged