Add LOWER love letter
fishtown-analytics/docs.getdbt.com pull request #1645
Opened 2022-06-30 13:40 UTC by johnblust

Adds canonical LOWER love letter to DevBlog

2022-06-30 16:21 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +> At a high level, a function takes an input (or multiple inputs) and returns a manipulation of those inputs. Some common SQL functions are COALESCE, EXTRACT, and DATEDIFF. For example, the `COALESCE
```suggestion
> At a high level, a function takes an input (or multiple inputs) and returns a manipulation of those inputs. Some common SQL functions are COALESCE, EXTRACT, and DATEDIFF. For example, the COALESCE function takes a group of values and returns the first non-null value from that group.
```

Can we mark somewhere to link to COALESCE, EXTRACT and DATEDIFF pages?

2022-06-30 16:21 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +lower(‘<string_value>’)
```suggestion
lower('<string_value>')
```

2022-06-30 16:21 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +Let’s take this to an actual example! Below, you’ll see the first three rows from the `customers` <Term id="table" /> in the jaffle_shop, a simple dataset and dbt project, that has three columns: `cu
```suggestion
Let’s take this to an actual example! Below, you’ll see the first three rows from the `customers` <Term id="table" /> in the [jaffle_shop](https://github.com/dbt-labs/jaffle_shop), a simple dataset and dbt project, that has three columns: `customer_id`, `first_name`, and `last_name`.
```

2022-06-30 16:22 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +from {{ ref(‘customers’) }}
```suggestion
from {{ ref('customers') }}
```

2022-06-30 16:24 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +Google BigQuery, Amazon Redshift, Snowflake, Postgres, and Databricks all support the LOWER function. In addition, the syntax to use LOWER is the same across all of them.
```suggestion
[Google BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#lower), [Amazon Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_LOWER.html), [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/lower.html), [Postgres](https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-letter-case-functions/), and [Databricks](https://docs.databricks.com/sql/language-manual/functions/lower.html) all support the LOWER function. In addition, the syntax to use LOWER is the same across all of them.
```

2022-06-30 16:24 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +> Changing all string columns to lowercase to create uniformity across data sources typically happens in our dbt project’s staging models. There are a few reasons for that: data cleanup and standardi
```suggestion
> Changing all string columns to lowercase to create uniformity across data sources typically happens in our dbt project’s [staging models](https://docs.getdbt.com/guides/best-practices/how-we-structure/2-staging). There are a few reasons for that: data cleanup and standardization, such as aliasing, casting, and lowercasing, should ideally happen in staging models to create downstream uniformity. It’s also more performant in downstream models that join on string values to join on strings that are of all the same casing versus having to join and perform lowercasing at the same time.
```

2022-06-30 16:25 UTC, KiraFuruichi requested changes
Some minor edits, mostly links missing!

2022-07-12 15:09 UTC, KiraFuruichi commented on website/blog/2022-06-30-lower-sql-function.md
> +```
```suggestion
```sql
```

I was wondering why the colors weren't displaying correctly!

2022-07-12 15:13 UTC, johnblust commented
Thanks for the review Kira. I added the links. I'll do this for the rest as well since we'll be merging them at the same time.

2022-07-13 17:07 UTC, KiraFuruichi approved these changes
dope dope dope

2022-07-15 18:08 UTC, merged