adding bq Oauth
fishtown-analytics/docs.getdbt.com pull request #1740
Opened 2022-07-19 06:13 UTC by schottj

Adding docs for BQ OAuth

## To-do before merge

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2022-07-27 23:42 UTC, nghi-ly requested changes
looks great! happy to answer any questions you may have re: any of my review comments!

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +
instead of using ordered lists to capture the steps here, consider using tabs (eg `BigQuery admin` and `dbt Cloud devs` tabs) for a slightly better reading experience with less jumping around.

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +dbt Cloud supports developer [OAuth](https://cloud.google.com/bigquery/docs/authentication) with BigQuery, providing an additional layer of security for our enterprise customers. When BigQuery OAuth
```suggestion
dbt Cloud supports developer [OAuth](https://cloud.google.com/bigquery/docs/authentication) with BigQuery, providing an additional layer of security for dbt enterprise users. When BigQuery OAuth is enabled for a dbt Cloud project, all dbt Cloud developers must authenticate with BigQuery in order to use the dbt Cloud IDE. The project's deployment environments will still leverage the BigQuery service account key set in the project credentials.
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +In the BigQuery console, navigate to **APIs & Services** and select the **Credentials** page:
```suggestion
In the BigQuery console, navigate to **APIs & Services** and select **Credentials**:
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +Here you'll see your existing keys, client IDs and service accounts. Note, if you haven't set up an [OAuth consent screen](https://support.google.com/cloud/answer/6158849) before, you'll need to do t
```suggestion
On the **Credentials** page, you can see your existing keys, client IDs, and service accounts.
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +Otherwise, click the **+ Create Credentials** at the  of the page, and select **OAuth client ID**.
```suggestion
Set up an [OAuth consent screen](https://support.google.com/cloud/answer/6158849) if you haven't already. Then, click **+ Create Credentials** at the top of the page and select **OAuth client ID**.
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +If you're a dbt Cloud single tenant customer, you'll need to replace **cloud.getdbt.com** with the hostname of
```suggestion
If you're a dbt Cloud single tenant customer, you need to replace `cloud.getdbt.com` with the hostname of
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +Then click **Create**, which will create the BigQuery OAuth app and will display the app client ID and secret. These values will be available even if you close the app screen, so this is not the only
```suggestion
Then click **Create** to create the BigQuery OAuth app and see the app client ID and secret values. These values are available even if you close the app screen, so this isn't the only chance you have to save them. 
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> + - navigate to your **Account Settings** pane
```suggestion
 - go to [Settings](https://cloud.getdbt.com/next/settings/profile)
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> + - select the **Projects** tab
```suggestion
 - on the left, select **Projects** under **Account Settings** 
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> + - find your project
```suggestion
 - choose your project from the list
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> + - select **Connection** to edit the connection details
```suggestion
 - select **Connection** to edit the connection details
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +Once the BigQuery OAuth app has been set up for the dbt Cloud project, each dbt Cloud user will need to authenticate with BigQuery in order to use the IDE. To do so:
```suggestion
Once the BigQuery OAuth app is set up for a dbt Cloud project, each dbt Cloud user will need to authenticate with BigQuery in order to use the IDE. To do so:
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +- navigate to **Your Profile** settings
```suggestion

```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +- select the **Credentials** tab
```suggestion
- go to the [Credentials](https://cloud.getdbt.com/next/settings/profile#credentials) section
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +- find your project
```suggestion
- choose your project from the list
```

2022-07-27 23:42 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +Select **Allow**, which will redirect you back to dbt Cloud. You should now be an authenticated BigQuery user, ready to use the dbt Cloud IDE.
```suggestion
Select **Allow**. This redirects you back to dbt Cloud. You should now be an authenticated BigQuery user, ready to use the dbt Cloud IDE.
```

2022-07-28 00:27 UTC, runleonarun approved these changes
Thank you for the review, @nghi-ly and the PR, Julia! These changes look great.

2022-07-28 00:27 UTC, runleonarun commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +dbt Cloud supports developer [OAuth](https://cloud.google.com/bigquery/docs/authentication) with BigQuery, providing an additional layer of security for our enterprise customers. When BigQuery OAuth
Good call on removing "our"

2022-07-28 00:27 UTC, runleonarun commented on website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-setting-up-bigquery-oauth.md
> +
@nghi-ly this is a great idea. Let's capture this in a follow-up task so we can merge this content!

2022-07-28 01:03 UTC, nghi-ly approved these changes

2022-07-28 01:03 UTC, merged