Change billing
fishtown-analytics/docs.getdbt.com pull request #1794
Opened 2022-07-25 18:40 UTC by syanaga

## Description & motivation

## To-do before merge

## Prerelease docs

## Checklist

If you removed existing pages (delete if not applicable):

2022-07-25 18:59 UTC, syanaga commented
@runleonarun this PR is ready for review :)

2022-07-26 21:24 UTC, nghi-ly requested changes
thanks for making the change! left a sugg to help improve readability and with navigation

2022-07-26 21:24 UTC, nghi-ly commented on website/docs/faqs/Accounts/change-billing.md
> +If you would like to change your account's credit card details, the account owner can do this by clicking the gear icon in the upper right corner and going to Account Settings  &#8594; Billing  &#859
```suggestion
If you want to change your account's credit card details, select the gear menu in the upper right corner of dbt Cloud. Go to Account Settings  &#8594; Billing  &#8594; Payment Information. In the upper right corner of **Payment Information**, click **Edit**  to enter the new credit card details. Only the _account owner_ can make this change. 
```

2022-07-26 21:24 UTC, nghi-ly commented on website/docs/faqs/Accounts/change-billing.md
> +If you would like to change your account's credit card details, the account owner can do this by clicking the gear icon in the upper right corner and going to Account Settings  &#8594; Billing  &#859
suggest breaking up the first sentence a tiny bit to help increase readability and for faster reading

2022-07-26 22:53 UTC, nghi-ly commented
stephanie 👍 the sugg in slack: 

<img width="551" alt="Screen Shot 2022-07-26 at 3 51 28 PM" src="https://user-images.githubusercontent.com/107218380/181125717-cd2e61e4-2c53-43ee-b4e2-02057ad69fc1.png">

2022-07-26 22:55 UTC, nghi-ly approved these changes

2022-07-26 22:58 UTC, merged