Add EDW glossary entry
fishtown-analytics/docs.getdbt.com pull request #1846
Opened 2022-08-09 17:02 UTC by johnblust

## Description & motivation
Adds EDW glossary entry to the analytics engineering glossary

2022-08-12 17:41 UTC, KiraFuruichi commented
I made some substantial changes to the written content [here](https://docs.google.com/document/d/1R7JDoDuI_Z4VHVOtq49tX75qHAquKefU15Vu8h8HrIY/edit#), lmk if you have any questions or want to chat through this version I have!

2022-08-16 14:58 UTC, johnblust commented
You killed it, Kira! I responded to your one comment, but I think I'm going to start adding this content to the PR

2022-08-16 17:31 UTC, johnblust commented
@KiraFuruichi Okay, I added the new content. You can view the [preview here](https://deploy-preview-1846--docs-getdbt-com.netlify.app/terms/edw). If it looks good, go ahead and approve the PR so I can merge. Thanks!!

2022-08-16 18:59 UTC, KiraFuruichi commented on website/docs/terms/edw.md
> +If a company has very siloed departments that manage their own data, budgets, and have little need for crossover with other departments or data sources, emphasizing the difference between a central E
```suggestion

If a company has very siloed departments that manage their own data, budgets, and have little need for crossover with other departments or data sources, emphasizing the difference between a central EDW data warehouse and their own data warehouse could be a necessity for budgeting and governance reasons.
```

Add additional spacing to match paragraph spacing in draft

2022-08-16 18:59 UTC, KiraFuruichi commented on website/docs/terms/edw.md
> +Lastly, the somewhat exponential adoption of cloud data warehouses in the last decade has shifted the terminology from what many people called an EDW to a data warehouse.
```suggestion

Lastly, the somewhat exponential adoption of cloud data warehouses in the last decade has shifted the terminology from what many people called an EDW to a data warehouse.
```

2022-08-16 19:00 UTC, KiraFuruichi commented on website/docs/terms/edw.md
> +## Additional reading
```suggestion
## Additional reading
EDW, data warehouse, or something different altogether? Check out some of our favorite resources on the fundamental of data storage and organization:
```

2022-08-16 19:03 UTC, KiraFuruichi requested changes
Minor edits to match draft

2022-08-16 19:24 UTC, johnblust commented
Should be good to go now!

2022-08-16 19:29 UTC, KiraFuruichi approved these changes
Amazing, thanks! Think `current` had some updates, so feel free to merge in once this branch is updated!

2022-08-16 19:41 UTC, merged