Create render-lineage-feature.md
fishtown-analytics/docs.getdbt.com pull request #1881
Opened 2022-08-18 12:40 UTC by mirnawong1

created a release note for large dag rendering per notion request here: https://www.notion.so/dbtlabs/DAG-in-the-IDE-will-not-auto-render-large-DAGs-e654861a099d4b789fb8d36176594c32

## Description & motivation

## To-do before merge

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2022-08-18 18:31 UTC, nghi-ly requested changes
looks good! small nits

2022-08-18 18:31 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/release-notes/07-July-2022/render-lineage-feature.md
> +description: "Add a render button for Large DAGs to visualize"
```suggestion
description: "Add a render button to visualize large DAGs"
```

2022-08-18 18:31 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/release-notes/07-July-2022/render-lineage-feature.md
> +Large DAGs can take a long time (10+ seconds, if not minutes) to render and can cause browsers to crash.
```suggestion
Large DAGs can take a long time (10 or more seconds, if not minutes) to render and can cause browsers to crash. 
```

2022-08-18 18:31 UTC, nghi-ly commented on website/docs/docs/dbt-cloud/release-notes/07-July-2022/render-lineage-feature.md
> +The new button feature prevents large DAGs from rendering automatically. Instead, you can select **Render Lineage** to load up the visualization. This should affect only ~15% of the DAGs.
```suggestion
The new button prevents large DAGs from rendering automatically. Instead, you can select **Render Lineage** to load the visualization. This should affect about 15% of the DAGs.
```

2022-08-19 10:56 UTC, mirnawong1 commented
thank you very much @nghi-ly 🔥 !

2022-08-19 11:05 UTC, mirnawong1 reviewed
changes made

2022-08-19 16:09 UTC, nghi-ly approved these changes
:shipit:

2022-08-19 16:21 UTC, merged