Matts moves
fishtown-analytics/docs.getdbt.com pull request #2219
Opened 2022-10-13 19:35 UTC by matthewshaver

## Description & motivation

## Checklist
If you added new pages (delete if not applicable):
- [ x] The page has been added to `website/sidebars.js`
- [ x] The new page has a unique filename

2022-10-13 22:47 UTC, nghi-ly commented on website/docs/docs/collaborate/manage-access/manage-access.md
> +id: "manage-access"
should this be "About access" ?

2022-10-13 22:49 UTC, runleonarun requested changes
@matthewshaver Just a few tweaks and this will be good!

2022-10-13 22:49 UTC, runleonarun commented on website/docs/docs/collaborate/cloud-build-and-view-your-docs.md
> +## Viewing docs in the IDE
```suggestion
## Viewing docs
```
This section and the one above describe the same thing. Can you combine them under this heading?

> ## Viewing documentation
> Once you have a job set up to generate documentation for your project, then click **Documentation** in the top left. Your project's documentation should open. This link will always navigate you to the most recent version of your project's documentation in dbt Cloud.
<Lightbox src="/img/docs/dbt-cloud/using-dbt-cloud/98c05c5-Screen_Shot_2019-02-08_at_9.18.22_PM.png" title="Project documentation"/>

2022-10-13 22:49 UTC, runleonarun commented on website/docs/docs/collaborate/cloud-build-and-view-your-docs.md
>  ## Easy access
```suggestion
## Provide access
```

2022-10-13 22:49 UTC, runleonarun commented on website/docs/docs/collaborate/cloud-build-and-view-your-docs.md
>  See [Building and Configuring Artifacts](artifacts) for more information on exposing links to the latest Documentation and Source Freshness reports to your team.
```suggestion
Before the documentation can be generated, you need to select the job to create the artifacts.  Read more in [Building and Configuring Artifacts](artifacts).
```

2022-10-13 22:49 UTC, runleonarun commented on website/docs/docs/collaborate/cloud-build-and-view-your-docs.md
> +The dbt Cloud IDE makes it possible to view [documentation](/building-a-dbt-project/documentation)
```suggestion
The dbt Cloud IDE makes it possible to view [documentation](/docs/collaborate/documentation)
```

2022-10-13 22:51 UTC, matthewshaver commented on website/sidebars.js
> +            "docs/collaborate/manage-access/manage-access",
```suggestion
            "docs/collaborate/manage-access/about-access",
```

2022-10-13 22:51 UTC, matthewshaver commented on _redirects
> +/docs/dbt-cloud/access-control/access-control-overview /docs/collaborate/manage-access/manage-access 301
```suggestion
/docs/dbt-cloud/access-control/access-control-overview /docs/collaborate/manage-access/about-access 301
```

2022-10-13 22:51 UTC, runleonarun requested changes
One more change!

2022-10-13 22:51 UTC, runleonarun commented on website/docs/docs/collaborate/manage-access/about-access.md
> +For a full list of enterprise permission sets, see [Enterprise Permissions](/docs/dbt-cloud/access-control/enterprise-permissions).
```suggestion
For a full list of enterprise permission sets, see [Enterprise Permissions](/docs/collaborate/manage-access/enterprise-permissions).
```

2022-10-14 02:50 UTC, runleonarun commented on website/docs/docs/collaborate/manage-access/about-access.md
> +At a high-level, Developers may be granted _any_ permissions, whereas Read Only
```suggestion
At a high level, Developers may be granted _any_ permissions, whereas Read Only
```

2022-10-14 03:03 UTC, runleonarun approved these changes
This looks good now!

2022-10-14 03:04 UTC, merged