Add relational database glossary entry
fishtown-analytics/docs.getdbt.com pull request #2404
Opened 2022-11-16 16:09 UTC by johnblust

## Description & motivation
Adds relational database glossary entry to the AE glossary

2022-11-16 16:30 UTC, KiraFuruichi commented on website/docs/terms/relational-database.md
> +## Additional reading
```suggestion
## Further reading
```
We call this further reading in all other pages

2022-11-16 16:30 UTC, KiraFuruichi commented on website/docs/terms/relational-database.md
> +| Data Integrity | The relationships and constraints defined ensure high data integrity.  | Non-relational databases do not guarantee data integrity. |
```suggestion
| Data Integrity | The relationships and constraints defined help ensure higher data integrity.  | Non-relational databases do not guarantee data integrity. |
```

2022-11-16 16:32 UTC, KiraFuruichi commented on website/docs/terms/relational-database.md
> +Relational databases also have a strong record of transactional consistency. While companies race to embrace non-relational databases in order to handle the big volume of unstructured data, most of t
```suggestion
Relational databases also have a strong record of transactional consistency. While some companies are racing to embrace non-relational databases in order to handle the big volume of unstructured data, most of their workloads likely remain transactional and analytical in nature which is why relational databases are very common. 
```

2022-11-16 16:34 UTC, KiraFuruichi commented on website/docs/terms/relational-database.md
> +Relational databases support common data modeling techniques such as dimensional modeling, Data Vault, or sometimes hybrid approaches that combine different modeling techniques. Such methodologies al
```suggestion
Relational databases support common data modeling techniques such as <Term id = "dimensional modeling"/>, Data Vault, or sometimes hybrid approaches that combine different modeling techniques. Such methodologies allow teams to organize their data into useful data structures. 
```

2022-11-16 16:35 UTC, KiraFuruichi requested changes
Left some minor comments

2022-11-17 14:46 UTC, johnblust commented
Awesome, thanks for the review @KiraFuruichi! Should be good to go now

2022-11-17 15:50 UTC, KiraFuruichi commented on website/docs/terms/relational-database.md
> +Relational databases support common data modeling techniques such as <Term id = "dimensional modeling" />, Data Vault, or sometimes hybrid approaches that combine different modeling techniques. Such
```suggestion
Relational databases support common data modeling techniques such as <Term id = "dimensional-modeling" />, Data Vault, or sometimes hybrid approaches that combine different modeling techniques. Such methodologies allow teams to organize their data into useful data structures. 
```

2022-11-17 15:50 UTC, KiraFuruichi requested changes
forgot hyphen

2022-11-17 16:01 UTC, KiraFuruichi approved these changes

2022-11-18 14:29 UTC, merged