adding all t
fishtown-analytics/docs.getdbt.com pull request #2689
Opened 2023-01-10 16:54 UTC by Sachin-Thakur

## What are you changing in this pull request and why?
 we have made content improvisation on vertica setup and configuration pages 
Describe your changes and why you're making them. If linked to an open
issue or a pull request on dbt Core, then link to them here!

2023-01-11 06:06 UTC, Sachin-Thakur commented
@dataders  could you please review this PR and merge the code base

2023-01-11 14:12 UTC, Sachin-Thakur commented
Hi dbt-labs/product-docs  could you please look into the PR

2023-01-11 21:19 UTC, dataders requested changes
some small tweaks! you should be able to look at [the deploy log](https://app.netlify.com/sites/docs-getdbt-com/deploys/63be9226471ffc00082ac641#L94-L103) to find any errors. because there is no preview link, there must be an issue going

2023-01-11 21:19 UTC, dataders commented on website/docs/reference/warehouse-setups/vertica-setup.md
> +  slack_channel_link: 'https://app.slack.com/client/T0VLPD22H/C030A0UF5LM/thread/C030A0UF5LM-1669649490.022339'
this should stay the same. feel free to request a #db-vertica channel in the #channel-requests channel!
```suggestion
  slack_channel_name: 'n/a'
  slack_channel_link: 'https://www.getdbt.com/community/'
```

2023-01-11 21:19 UTC, dataders commented on website/docs/reference/warehouse-setups/vertica-setup.md
> +  min_supported_version: 'Vertica v12.0'
the intent of this field is to say:
> to use this adapter, you must have at least this version of Vertica.
so this change tells me that you used to be able to use Vertica 10.0, but cannot anymore. Is that the case?
```suggestion
  min_supported_version: 'Vertica 10.0'
```

2023-01-11 21:19 UTC, dataders commented on website/docs/reference/resource-configs/vertica-configs.md
> +    { label: 'Run code', value: 'run', },
```suggestion
    { label: 'Run code', value: 'run', }
```

2023-01-12 08:20 UTC, Sachin-Thakur commented on website/docs/reference/warehouse-setups/vertica-setup.md
> +  min_supported_version: 'Vertica v12.0'
yes @dataders

2023-01-12 17:20 UTC, dataders commented on website/docs/reference/warehouse-setups/vertica-setup.md
> +### Connecting to Vertica with {frontMatter.meta.pypi_package}
for inane reasons, you can't use markdown headers when injecting front matter info
```suggestion
<h3> Connecting to {frontMatter.meta.platform_name}   with {frontMatter.meta.pypi_package} </h3>
```

2023-01-12 18:24 UTC, dataders approved these changes
thanks for the quick turn around @Sachin-Thakur !

2023-01-12 18:30 UTC, merged

2023-01-13 06:26 UTC, Sachin-Thakur commented
> 

Thank You @dataders  for your quick support!