Add dbt-fal adapter
fishtown-analytics/docs.getdbt.com pull request #2700
Opened 2023-01-12 22:00 UTC by chamini2

## What are you changing in this pull request and why?

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.

Adding new pages (delete if not applicable):
- [x] Add page to `website/sidebars.js`
- [x] Provide a unique filename for the new page

2023-01-12 22:01 UTC, burkaygur commented on website/docs/reference/warehouse-setups/fal-setup.md
> +  pypi_package: 'dbt-duckdb'
is this correcT?

2023-01-17 04:27 UTC, dataders requested changes
@chamini2 you'll also want to add yourselves to the table on `docs/supported-data-platforms` 
https://docs.getdbt.com/docs/supported-data-platforms#community-adapters

2023-01-18 00:43 UTC, dataders approved these changes, later dismissed
🐿️

2023-01-25 18:15 UTC, dataders approved these changes
thanks @chamini2! :shipit:

2023-01-25 18:22 UTC, merged