jan ide release note
fishtown-analytics/docs.getdbt.com pull request #2804
Opened 2023-02-02 13:19 UTC by mirnawong1

release note for jan ide updates. 

see release note: https://www.notion.so/dbtlabs/Update-IDE-release-notes-for-Jan-2023-6a0d67e417e04bc4a0fdb825b5c43eb8

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-02-02 13:20 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- dbt Labs is researching ways to include Linting/SQL Fluff in the IDE. If anyone is interested in sharing how you're using SQL Fluff today, please reach out to dbt Labs Product Manager, [Nate Nunta]
hey @bossnunta - if users want to reach out to you, would it only be via slack dm's or email or another option? thinking of users that may not have slack

```suggestion
- dbt Labs is researching ways to include Linting/SQL Fluff in the IDE. If anyone is interested in sharing how you're using SQL Fluff today, please reach out to dbt Labs Product Manager, [Nate Nunta](bossman's email or dm?).
```

2023-02-02 18:15 UTC, bossnunta commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- dbt Labs is researching ways to include Linting/SQL Fluff in the IDE. If anyone is interested in sharing how you're using SQL Fluff today, please reach out to dbt Labs Product Manager, [Nate Nunta]
I think let's leave my name in there but -- DM me on community Slack or use this email cloud-ide-feedback@dbtlabs.com

2023-02-02 18:17 UTC, bossnunta submitted a review, later dismissed
Other than the one comment. This looks great to me!

2023-02-02 20:19 UTC, runleonarun requested changes
Hey @mirnawong1 I added a few minor requests. I rewrote the fixed bugs to state the fix rather than the original problem, but feel free to change that wording.

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +sidebar_label: "IDE updates and fixes"
I'm not married to this wording, but I wonder if we should keep consistent with previous naming conventions? I update [this section](https://www.notion.so/dbtlabs/Request-a-dbt-Cloud-release-note-f962f39b49af4a23811d70984fef4f65#bf538d5b1cb44ba5ba58fb0411d80783) of our internal release notes page to capture these differences.  
```suggestion
sidebar_label: "Update and Fixes: IDE"
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +## Bugs fixed
Just changing this to parallel other sections
```suggestion
## Bug fixes
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Users running into `RPC server got an unknown async ID` arbitrarily
```suggestion
- You no longer arbitrarily encounter an `RPC server got an unknown async ID` message
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- The build button dropdown was hidden behind the placeholder DAG screen
```suggestion
- You can now see the build button dropdown, which had been hidden behind the placeholder DAG screen
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Unable to close toast notifications for command failure when the history drawer is open
```suggestion
- You can now close toast notifications for command failure when the history drawer is open
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Users ran into `Something went wrong` when previewing a model
```suggestion
- You no longer encounter a `Something went wrong` message when previewing a model
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Unable to retrieve repository status in the IDE due to inability to find SSH folder
Was there an error message this addressed?
```suggestion
- You can now see repository status in the IDE, and the IDE finds the SSH folder
```

2023-02-02 20:19 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Scroll bars and download CSV flicker within the preview pane
```suggestion
- Scroll bars and download CSV no longer flicker within the preview pane. 
```

2023-02-03 09:17 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +sidebar_label: "IDE updates and fixes"
oh good callout, thank you Leona! i should've noticed that 🙏

2023-02-03 09:20 UTC, mirnawong1 commented
hey @runleonarun suggestions have been committed, thank you for those knowledge bombs!

2023-02-06 17:01 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/01-Jan-2023/ide-updates.md
> +- Scroll bars and download CSV no longer flicker within the preview pane.
```suggestion
- Scroll bars and download CSV no longer flicker within the preview pane
```

2023-02-06 17:01 UTC, runleonarun approved these changes
LGTM!

2023-02-06 17:08 UTC, merged