add feb product newsletter
fishtown-analytics/docs.getdbt.com pull request #2817
Opened 2023-02-03 16:53 UTC by glin7

## What are you changing in this pull request and why?
Upload Feb product email to dev blog

2023-02-03 21:16 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +# authors: [lauren_craigie]
Can you either add yourself as an author or uncomment Lauren here? Always nice to give a face to blog content.

2023-02-03 21:16 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +title: "February 2023 dbt Update"
```suggestion
title: "February 2023 dbt update"
```

to be consistent with dbt Labs capitalization standards

2023-02-03 21:17 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +## **What's Better?**
```suggestion
## **What's better?**
```

2023-02-03 21:18 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +- **[Custom node colors in the dbt DAG](https://www.getdbt.com/blog/announcing-dbt-v1.3-and-utils/).** Color coding your DAG makes it *much* easier to understand your project at a glance. Read about
```suggestion
- **[Custom node colors in the dbt DAG](https://www.getdbt.com/blog/announcing-dbt-v1.3-and-utils/):** Color coding your DAG makes it *much* easier to understand your project at a glance. Read about this update, as well as other dbt Core v1.3 improvements.
```

2023-02-03 21:18 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +## **New Resources**
```suggestion
## New resources
```

2023-02-03 21:21 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +![https://hs-8698602.f.hubspotemail.net/hub/8698602/hubfs/Screen%20Shot%202023-02-01%20at%208.12.43%20PM.png?upscale=true&width=600&upscale=true&name=Screen%20Shot%202023-02-01%20at%208.12.43%20PM.pn
This is a pretty low-quality screenshot; can you potentially upload it as an actual image into the docs repo and use  a lightbox element (that way you can add alt text description to this)? See D[oug's autoscaling CI blog post for an example](https://raw.githubusercontent.com/dbt-labs/docs.getdbt.com/current/website/blog/2023-01-27-autoscaling-ci.md).

2023-02-03 21:21 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +## **Weekend Reads**📚
```suggestion
## Weekend reads📚
```

2023-02-03 21:21 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +## **Places to Go** 🌎
```suggestion
## Places to go 🌎
```

2023-02-03 21:22 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +## **Consulting Corner** 🌎
```suggestion
## Consulting corner 🌎
```

2023-02-03 21:22 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +- **[Querying dbt metrics](https://aimpointdigital.com/querying-dbt-metrics/)** - Aimpoint Digital shows how to use dbt Metrics via the Proxy Server if your BI tool if it isn't yet integrated with th
```suggestion
- **[Querying dbt metrics](https://aimpointdigital.com/querying-dbt-metrics/)**: Aimpoint Digital shows how to use dbt Metrics via the Proxy Server if your BI tool if it isn't yet integrated with the dbt Semantic Layer.
```

2023-02-03 21:23 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +- **[Simplifying Data Validation with dbt Data Audit](https://medium.com/slalom-build/simplifying-data-validation-with-dbt-ba492d216abe)** Slalom shares how to speed up query validation with the dbt-
```suggestion
- **[Simplifying Data Validation with dbt Data Audit](https://medium.com/slalom-build/simplifying-data-validation-with-dbt-ba492d216abe):** Slalom shares how to speed up query validation with the dbt-audit-helper package.
```

2023-02-03 21:23 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +- **[A Guide to Passing the dbt Analytics Engineering Certification](https://aimpointdigital.com/guide-passing-dbt-analytics-engineering-certification/)**  Join 500+ dbt certified analytics engineers
```suggestion
- **[A Guide to Passing the dbt Analytics Engineering Certification](https://aimpointdigital.com/guide-passing-dbt-analytics-engineering-certification/):**  Join 500+ dbt certified analytics engineers with Aimpoint’s latest guide!
```

2023-02-03 21:24 UTC, KiraFuruichi commented on website/blog/2023-02-03-product-update.md
> +![https://hs-8698602.f.hubspotemail.net/hub/8698602/hubfs/Screen%20Shot%202023-02-01%20at%209.55.51%20PM.png?upscale=true&width=600&upscale=true&name=Screen%20Shot%202023-02-01%20at%209.55.51%20PM.pn
This is pic renders in low quality; can you potentially upload it as an actual image into the docs repo and use a lightbox element (that way you can add alt text description to this)? See [Doug's autoscaling CI blog post for an example](https://raw.githubusercontent.com/dbt-labs/docs.getdbt.com/current/website/blog/2023-01-27-autoscaling-ci.md).

2023-02-03 21:25 UTC, KiraFuruichi requested changes
Capitalization consistencies, replace images with Lightbox images + actual image uploads to repo

2023-05-30 23:24 UTC, runleonarun commented
Closing this as it's maybe a little late to publish. I will check with the PMM team to see if they want to publish their emails updates going forward.

2023-05-30 23:24 UTC, closed without merging