added exasol community adapter documentation
fishtown-analytics/docs.getdbt.com pull request #291
Opened 2020-07-17 15:52 UTC by tglunde

We added an adapter for the Exasol Analytics database. These are the corresponding documentation sites.

2020-07-29 21:30 UTC, clrcrl commented
@jtcohen6 — is this `current` or `next`?

2020-07-29 21:52 UTC, jtcohen6 commented
This is `current`, since it looks like the exasol adapter [is pinned to dbt v0.14.0](https://github.com/tglunde/dbt-exasol/blob/master/setup.py#L27). I'll assign myself as a reviewer.

2020-07-30 07:45 UTC, tglunde commented
> This is `current`, since it looks like the exasol adapter [is pinned to dbt v0.14.0](https://github.com/tglunde/dbt-exasol/blob/master/setup.py#L27). I'll assign myself as a reviewer.

Could you please explain the relevance on current versus next? Which versions include current/next?

2020-07-30 14:30 UTC, jtcohen6 commented
> Could you please explain the relevance on current versus next? Which versions include current/next?

Surely! The `next` branch serves a prerelease docs site, which will include any features/changes coming in a dbt version that has yet to reach final release.

Since the dbt-exasol plugin is usable _without_ needing to wait for v0.18.0, this PR can be against `current`, not `next`.

2020-08-20 14:21 UTC, tglunde commented
when will this get reviews?

2020-08-21 12:43 UTC, drewbanin requested changes
Hey @tglunde - thanks for the bump. This one was blocking on my review!

I have one (small) suggested change here. Happy to merge it once that change is addressed. Thanks for your hard work on this plugin and for your patience with this PR!

2020-08-21 12:43 UTC, drewbanin commented on website/docs/reference/warehouse-profiles/exasol-profile.md
> +---
i think you're going to need to add this link [to the `sidebars.js` file](https://github.com/fishtown-analytics/docs.getdbt.com/blob/current/website/sidebars.js#L422) to get the sidebar to render [on this page](https://deploy-preview-291--docs-getdbt-com.netlify.app/reference/warehouse-profiles/exasol-profile).

2020-08-21 13:01 UTC, tglunde commented on website/docs/reference/warehouse-profiles/exasol-profile.md
> +---
sorry, but I don't know how - I just copied another file and changed the content - i dont see any sidebar.js link on the postgres-profile.md either. could you give me a hint on how to do this?

2020-08-21 13:27 UTC, drewbanin commented on website/docs/reference/warehouse-profiles/exasol-profile.md
> +---
all good! It's an easy thing to miss.

You're just going to want to update this file to add a link to `exasol-profile`:

https://github.com/fishtown-analytics/docs.getdbt.com/blob/3deda0efd5e6f4c1b3ca06ea0178818edd9f563c/website/sidebars.js#L415-L422

Check out the "sidebar" I'm referring to here:

<img width="873" alt="Screen Shot 2020-08-21 at 9 25 31 AM" src="https://user-images.githubusercontent.com/1541139/90895575-60613300-e390-11ea-9e3e-8ce0f59400a5.png">

2020-08-21 14:20 UTC, tglunde commented on website/docs/reference/warehouse-profiles/exasol-profile.md
> +---
ok. thx. added the commit.

2020-08-21 15:10 UTC, drewbanin approved these changes
Thanks @tglunde! Approved :)

2020-08-21 15:10 UTC, merged