Add Tableau workbook refresh via webhooks
fishtown-analytics/docs.getdbt.com pull request #3123
Opened 2023-04-03 00:57 UTC by ramiz-bozai-dbt

## What are you changing in this pull request and why?

A common workflow for data teams involves refreshing a Tableau workbook after rebuilding the underlying data.  dbt Cloud's new webhook functionality can be extended to this use case alongside the Tableau REST API.

## Checklist
- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Provide a unique filename for the new page

2023-04-04 09:37 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +This guide will teach you how to refresh a Tableau workbook that leverages extracts when a dbt Cloud job has completed successfully and there is fresh data available. The integration will:
sugg a link to tableau extracts
```suggestion
This guide will teach you how to refresh a Tableau workbook that leverages [extracts](https://help.tableau.com/current/pro/desktop/en-us/extracting_data.htm) when a dbt Cloud job has completed successfully and there is fresh data available. The integration will:
```

2023-04-04 09:39 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +- The [version](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm#rest_api_versioning) of Tableau's REST API that is compatible with your server
```suggestion
To set up the integration, you need to be familiar with:

- [dbt Cloud Webhooks](/docs/deploy/webhooks)
- Zapier
- The [Tableau API](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api.htm)
- The [version](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm#rest_api_versioning) of Tableau's REST API that is compatible with your server 
```

2023-04-04 09:42 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +Obtain a [Personal Access Token](https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm) from your Tableau Server/Cloud instance.  You'll need this to authenticate with the
```suggestion
To authenticate with the Tableau API, obtain a [Personal Access Token](https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm) from your Tableau Server/Cloud instance. In addition, make sure your Tableau workbook uses data sources that allow refresh access, which is usually set when publishing.
```

2023-04-04 09:47 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +Press **Continue**, then copy the webhook URL.
sugg clarifying intro to what user is doing here

```suggestion

To set up a webhook in Zapier, select **Webhooks by Zapier** as the Trigger and **Catch Raw Hook** as the Event. However, if you choose not to [validate the authenticity of your webhook](docs/deploy/webhooks#validate-a-webhook), which isn't recommended, you can choose **Catch Hook** instead. 

Press **Continue** and then copy the webhook URL. 
```

2023-04-04 09:59 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +The sample body's values are hard-coded and not reflective of your project, but they give Zapier a correctly-shaped object during development.
```suggestion
To set up a webhook subscription for dbt Cloud, follow the instructions in [Create a webhook subscription](/docs/deploy/webhooks#create-a-webhook-subscription). For the event, choose **Run completed** and modify the **Jobs** list to include only the jobs that should trigger a report refresh.

Remember to save the Webhook Secret Key for later. Paste in the webhook URL obtained from Zapier in step 2 into the **Endpoint** field and test the endpoint.

Once you've tested the endpoint in dbt Cloud, go back to Zapier and click **Test Trigger**, which will create a sample webhook body based on the test event dbt Cloud sent.

The sample body's values are hard-coded and not reflective of your project, but they give Zapier a correctly-shaped object during development. 
```

2023-04-04 10:05 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +If you haven't already got one, go to <https://zapier.com/app/connections/storage> and create a new connection. Remember the UUID secret you generate for later.
```suggestion
#### a. Create a Storage by Zapier connection 

Create a new connection at https://zapier.com/app/connections/storage if you don't already have one and remember the UUID secret you generate for later.
```

2023-04-04 10:07 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +Test the step. You can delete this Action when the test succeeds. The key will remain stored as long as it is accessed at least once every three months.
```suggestion
#### b. Add a temporary code step

Choose **Run Python** as the Event and run the following code: 

```python 
store = StoreClient('abc123') #replace with your UUID secret
store.set('DBT_WEBHOOK_KEY', 'abc123') #replace with your dbt Cloud Webhook key
store.set('TABLEAU_SITE_URL', 'abc123') #replace with your Tableau Site URL, inclusive of https:// and .com
store.set('TABLEAU_SITE_NAME', 'abc123') #replace with your Tableau Site/Server Name
store.set('TABLEAU_API_TOKEN_NAME', 'abc123') #replace with your Tableau API Token Name
store.set('TABLEAU_API_TOKEN_SECRET', 'abc123') #replace with your Tableau API Secret
```
Test the step. You can delete this Action when the test succeeds. The key will remain stored as long as it is accessed at least once every three months.
```

2023-04-04 10:07 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +### 4. Add a code action
duplicate 4 so changing this to 5

```suggestion
### 5. Add a code action
```

2023-04-04 10:08 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +### 5. Test and deploy
Update step
```suggestion
### 6. Test and deploy
```

2023-04-04 10:10 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +The code below will validate the authenticity of the request then obtain the workbook ID for the specified workbook name.  Next, the code will send a [`update workbook` command to the Tableau API](ht
```suggestion
The following code validates the authenticity of the request and obtains the workbook ID for the specified workbook name.  Next, the code will send a [`update workbook` command to the Tableau API](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#update_workbook_now) for the given workbook ID.
```

2023-04-04 10:12 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +You can iterate on the Code step by modifying the code and then running the test again. When you're happy with it, you can publish your Zap.
```suggestion
To make changes to your code, you can modify it and test it again. When you're happy with it, you can publish your Zap.
```

2023-04-04 10:15 UTC, mirnawong1 commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +title: "Refresh a Tableau workbook with extracts when a job completes"
non blocker but sugg shortening title
```suggestion
title: "Refresh Tableau workbook with extracts after job finishes"
```

2023-04-04 10:18 UTC, mirnawong1 requested changes
hey @ramiz-bozai-dbt this looks awesome, thanks so much for opening this up! I've left some suggestions on my end and am happy to re-review it further!  let me know if you have any questions at all!

2023-04-05 18:41 UTC, ramiz-bozai-dbt commented
> hey @ramiz-bozai-dbt this looks awesome, thanks so much for opening this up! I've left some suggestions on my end and am happy to re-review it further! let me know if you have any questions at all!

Thanks @mirnawong1 ! Added/revised changes as needed.  I'd appreciate one final review on this.

2023-04-05 20:21 UTC, joellabes requested changes, later dismissed
lgtm!

2023-04-05 20:21 UTC, joellabes commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +
Missing closing triple backticks here

2023-04-06 14:04 UTC, ramiz-bozai-dbt commented on website/docs/guides/orchestration/webhooks/zapier-refresh-tableau-workbook.md
> +
Thanks @joellabes .  Resolved.

2023-04-06 14:56 UTC, mirnawong1 approved these changes
this looks SOOOO good @ramiz-bozai-dbt ! lgtm as well and thank you for opening this up for users ✨

2023-04-06 15:01 UTC, mirnawong1 commented
will dismiss Joel's review since you've addressed this already and it's currently blocking your merge.

2023-04-06 15:02 UTC, mirnawong1 commented
will dismiss Joel's review since you've addressed this already and it's currently blocking your merge. good to merge for you @ramiz-bozai-dbt !!

2023-04-06 15:27 UTC, merged