Feature: add docs for handling merge conflicts in the IDE
fishtown-analytics/docs.getdbt.com pull request #320
Opened 2020-08-03 15:17 UTC by aescay

## Description & motivation
1. Add in the documentation for handling merge conflicts!
2. Move IDE to its own subsection in the dbt Cloud docs sidebar

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes
- [x] No

2020-08-03 20:43 UTC, alexbethea22 requested changes
This is so fantastic! Thanks for your help 🙌 I've requested just a few tiny, tiny changes.

2020-08-03 20:43 UTC, alexbethea22 commented on website/docs/docs/dbt-cloud/cloud-ide/handling-merge-conflicts.md
> +Merge conflicts often occur when multiple users are concurrently making edits to the same section in the same file. This makes it difficult for Git to determine the appropriate change to keep. The me
```suggestion
Merge conflicts often occur when multiple users are concurrently making edits to the same section in the same file. This makes it difficult for Git to determine the appropriate change to keep. The merge conflict process gives users the ability to sort out which lines of code should be kept and committed. Here we'll show you how you'd resolve merge conflicts in the IDE!
```

2020-08-03 20:43 UTC, alexbethea22 commented on website/docs/docs/dbt-cloud/cloud-ide/handling-merge-conflicts.md
> +You and your teammate come in to make the change but decide to go two separate routes. You rename this column to `total_number_of_orders` and your teammate decides to name it `historical_order_count`
```suggestion
You and a teammate make changes to the column name, but have gone two separate routes. You rename this column to `total_number_of_orders` and your teammate has renamed it `historical_order_count`. 
```

2020-08-03 20:43 UTC, alexbethea22 commented on website/docs/docs/dbt-cloud/cloud-ide/handling-merge-conflicts.md
> +Your teammate got to make their change first so you encounter the merge conflict when you press commit.
```suggestion
Your teammate has committed their change first, so you encounter a merge conflict when you press commit.
```

2020-08-03 20:52 UTC, aescay commented
incorporated all 3 suggestions! 🙏

2020-08-03 20:54 UTC, clrcrl commented on website/docs/docs/about/license.md
> -[dbt is licensed under the Apache 2.0 License](https://github.com/fishtown-analytics/dbt).
Heh, this made it in from #312 — I think this PR came in just as we were changing the branching behavior so we merged it into `master` instead of `current`. It's a good thing we picked it back up !

2020-08-04 17:26 UTC, alexbethea22 approved these changes
LGTM!

2020-08-04 19:08 UTC, drewbanin approved these changes
One suggestion around the sidebar label that i think we should change before merging, but otherwise LGTM!

2020-08-04 19:08 UTC, drewbanin commented on website/sidebars.js
> +      label: "dbt Cloud IDE (Develop)",
```suggestion
      label: "dbt Cloud IDE",
```

2020-08-04 20:03 UTC, drewbanin commented
thanks so much for your hard work on this doc @aescay!! I'm merging it so that we can link out to this page in the Cloud release notes :D

2020-08-04 20:03 UTC, merged