Adding the 3rd blog of our Databricks series
fishtown-analytics/docs.getdbt.com pull request #3298
Opened 2023-04-27 21:09 UTC by asteichen

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-04-27 21:10 UTC, asteichen commented
This has been reviewed by Amy and the Databricks team. I would appreciate suggestions on where screenshots would be most helpful in addition to style/content review. Thanks!

2023-04-28 09:28 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +# Productionizing your dbt Databricks Project
```suggestion
---
title: Productionizing your dbt Databricks project
id: "productionizing-your-dbt-databricks-project"
sidebar_label: "Productionizing your dbt Databricks project"
description: "Learn how to deliver models to end users and use best practices to maintain production data" 
---
```

2023-04-28 09:29 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +# Intro
```suggestion
```

2023-04-28 09:32 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Welcome to the third installment of our comprehensive series on optimizing and deploying your data pipelines using Databricks and dbt Cloud. By now, you should have successfully [set up your Databric
```suggestion
Welcome to the third installment of our comprehensive series on optimizing and deploying your data pipelines using Databricks and dbt Cloud. In this guide, we'll dive into delivering these models to end users while incorporating best practices to ensure that your production data remains reliable and timely.
```

2023-04-28 09:33 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +
```suggestion

## Prerequisites

If you don't have any of the following requirements, refer to the instructions in the [setup guide](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project) to catch up:

- You have [set up your Databricks and dbt Cloud environments](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project)
- You have [optimized your dbt models for peak performance](https://docs.getdbt.com/guides/dbt-ecosystem/databricks-guides/how_to_optimize_dbt_models_on_databricks)
- You have created two catalogs in Databricks: *dev* and *prod*.
- You have created  Databricks Service Principal to run your production jobs.
- You have at least one [deployment environment](docs/collaborate/environments/dbt-cloud-environments) in dbt Cloud.


```

2023-04-28 09:36 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +In software engineering, environments play a crucial role in allowing engineers to develop and test code without affecting the end users of their software. Similarly, [data lakehouses](https://www.da
sugg active voice:

```suggestion
In software engineering, environments play a crucial role in allowing engineers to develop and test code without affecting the end users of their software. Similarly, you can design [data lakehouses](https://www.databricks.com/product/data-lakehouse) with separate environments. The _production_ environment includes the relations (schemas, tables, and views) that end users query or use, typically in a BI tool or ML model.
```

2023-04-28 09:37 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +
adding prerequisites 

```suggestion

## Prerequisites

If you don't have any of the following requirements, refer to the instructions in the [setup guide](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project) to catch up:

- You have [set up your Databricks and dbt Cloud environments](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project)
- You have [optimized your dbt models for peak performance](/guides/dbt-ecosystem/databricks-guides/how_to_optimize_dbt_models_on_databricks)
- You have created two catalogs in Databricks: *dev* and *prod*.
- You have created  Databricks Service Principal to run your production jobs.
- You have at least one [deployment environment](docs/collaborate/environments/dbt-cloud-environments) in dbt Cloud.

```

2023-04-28 09:37 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +If any of the above elements are missing, refer to the instructions in the [setup guide](https://docs.getdbt.com/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project) to c
```suggestion
```

2023-04-28 09:37 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +1. Two catalogs in Databricks: *dev* and *prod*.
```suggestion*.
```

2023-04-28 09:37 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +2. A Databricks Service Principal to run your production jobs.
```suggestion
```

2023-04-28 11:07 UTC, mirnawong1 commented
hey @asteichen thanks for opening this up! such a lovely written guide and I'm so glad you wrote it. i have some suggestions in terms of slight reformatting and changing some links. let me know what you think and happy to help get this merged for you asap!

2023-04-28 11:09 UTC, mirnawong1 requested changes

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +3. At least one deployment environment in dbt Cloud.
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +If you have been following our series of guides, you should have already created:
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +In dbt Cloud, environments come in two flavors: deployment and development. Deployment environments define the settings used when jobs created within that environment are executed. In contrast, devel
sugg turning this into bullets so it's easier to scan

```suggestion
In dbt Cloud, [environments](/docs/collaborate/environments/dbt-cloud-environments) come in two flavors:

- Deployment &mdash; Defines the settings used for executing jobs created within that environment.
- Development. &mdash; Determine the settings used in the dbt Cloud IDE for a particular dbt Cloud project. 

Each dbt Cloud project can have multiple deployment environments, but only one development environment per user.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +To deploy our data transformation workflows, we will utilize dbt Cloud’s built-in job scheduler. The job scheduler is designed specifically to streamline your dbt project deployments and runs, ensuri
```suggestion
To deploy our data transformation workflows, we will utilize [dbt Cloud’s built-in job scheduler](/docs/deploy/dbt-cloud-job). The job scheduler is designed specifically to streamline your dbt project deployments and runs, ensuring that your data pipelines are easy to create, monitor, and modify efficiently.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Leveraging dbt Cloud's job scheduler allows data teams to own the entire transformation workflow. You do not need to learn and maintain additional tools for orchestration, or rely on another team to
```suggestion
Leveraging dbt Cloud's job scheduler allows data teams to own the entire transformation workflow. You don't need to learn and maintain additional tools for orchestration or rely on another team to schedule code written by your team. This end-to-end ownership simplifies the deployment process and accelerates the delivery of new data products.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Let’s [create a job](http://incremental_predicates/) in dbt Cloud that will transform data in our Databricks *prod* catalog.
i dont think this is the correct link, so am linking to the 'create jobs' doc
```suggestion
Let’s [create a job](/docs/deploy/dbt-cloud-job#create-and-schedule-jobs) in dbt Cloud that will transform data in our Databricks *prod* catalog.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    - Check the **Generate docs on run** checkbox to configure the job to automatically generate project docs each time this job runs. This will ensure your documentation stays evergreen as models ar
😍 love how this is all explained

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    - This will allow the job to inherit the catalog, schema, credentials, and environment variables defined in the [setup guide](https://docs.getdbt.com/guides/dbt-ecosystem/databricks-guides/how-to
updating links to relative path
```suggestion
    - This will allow the job to inherit the catalog, schema, credentials, and environment variables defined in the [setup guide](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project#defining-your-dbt-deployment-environment).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    - Check the **Run on source freshness** checkbox to configure dbt [source freshness](https://docs.getdbt.com/docs/deploy/source-freshness) as the first step of this job. Your sources will need to
```suggestion
    - Select the **Run on source freshness** checkbox to configure dbt [source freshness](/docs/deploy/source-freshness) as the first step of this job. Your sources will need to be configured to [snapshot freshness information](/docs/build/sources#snapshotting-source-data-freshness) for this to drive meaningful insights.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +# Create and schedule a production job
not sure why this is h1 - it's also not appearing in the right sidebar and you can't click the header
<img width="965" alt="Screenshot 2023-04-28 at 11 05 27" src="https://user-images.githubusercontent.com/89008547/235119218-9a0fdc9c-2d66-4ac3-8e04-0db73cd386d8.png">



```suggestion
## Create and schedule a production job
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    - Check the **Run on source freshness** checkbox to configure dbt [source freshness](https://docs.getdbt.com/docs/deploy/source-freshness) as the first step of this job. Your sources will need to
```suggestion
    - Select the **Run on source freshness** checkbox to configure dbt [source freshness](/docs/deploy/source-freshness) as the first step of this job. Your sources will need to be configured to [snapshot freshness information](/docs/build/sources#snapshotting-source-data-freshness) for this to drive meaningful insights.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    Add the following **Commands:**
```suggestion
    - Add the following **Commands:**
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +        - `dbt build --exclude source:* --fail-fast`
```suggestion
        - `dbt build --exclude source:* --fail-fast` &mdash; `dbt build` is more efficient than running `dbt run` and `dbt test` separately. This is because `dbt build` will run and test each model in a single step. 
            - Additionally, source data is excluded from the build step since it was already tested in step 2.
            - If a single resource fails to build, the fail-fast flag will make dbt exit immediately. If other models are in-progress when the first model fails, dbt will terminate the connections for those still-running models.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +            - dbt build is more efficient than issuing separate commands for dbt run and dbt test separately because it will run then test each model before continuing.
```suggestion

```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +            - We are excluding source data because we already tested it in step 2.
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +            - The fail-fast flag will make dbt exit immediately if a single resource fails to build. If other models are in-progress when the first model fails, then dbt will terminate the connection
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +        - `dbt source freshness`
```suggestion
        - `dbt source freshness` &mdash; Checks if any sources are stale. We don’t want to recompute models with data that hasn’t changed since our last run.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +            - This will check if any sources are stale. We don’t want to recompute models with data that hasn’t changed since our last run.
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +        - `dbt test --models source:*`
```suggestion
        - `dbt test --models source:*` &mdash; Test the data quality of our source data, such as making sure ID fields are unique and not null. We don’t want bad data getting into production models.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +            - This will test the data quality our source data, such as checking making sure ID fields are unique and not null. We don’t want bad data getting into production models.
```suggestion
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +5. Under **Triggers**, use the toggle to configure your job run on a schedule. You can enter specific days and timing or create a custom cron schedule.
```suggestion
5. Under **Triggers**, use the toggle to configure your job to [run on a schedule](/docs/deploy/job-triggers). You can enter specific days and timing or create a custom cron schedule. 
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +# Advanced Considerations
making this h2 so it's visible and you can link to it. also change to sentence case
```suggestion
## Advanced considerations
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +- [Databricks + dbt Cloud Quickstart Guide](https://docs.getdbt.com/docs/quickstarts/dbt-cloud/databricks)
```suggestion
- [Databricks + dbt Cloud Quickstart Guide](/docs/quickstarts/dbt-cloud/databricks)
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +**Additional resources:**
sugg turning into h2 

```suggestion
## Additional resources
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +To get the most out of both tools, you can use the [persist docs config](https://docs.getdbt.com/reference/resource-configs/persist_docs) to push table and column descriptions written in dbt into Uni
```suggestion
To get the most out of both tools, you can use the [persist docs config](/reference/resource-configs/persist_docs) to push table and column descriptions written in dbt into Unity Catalog, making the information easily accessible to both tools' users. Keeping the descriptions in dbt ensures they are version controlled and can be reproduced after a table is dropped.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +dbt docs is a documentation site generated from your dbt project that provides an interface for developers and non-technical stakeholders to understand the data lineage and business logic applied to
😍

```suggestion
dbt docs is a documentation site generated from your dbt project that provides an interface for developers and non-technical stakeholders to understand the data lineage and business logic applied to transformations without requiring full access to dbt Cloud or Databricks. It gives you additional options on how you can organize and search for your data. You can automatically [build and view your dbt docs using dbt Cloud](/docs/collaborate/build-and-view-your-docs) to keep the documentation evergreen.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Using the same sources for development and deployment  environments enables testing with the same volumes and frequency you will see in production. However, this may cause development runs to take lo
```suggestion
Using the same sources for development and deployment environments enables testing with the same volumes and frequency you will see in production. However, this may cause development runs to take longer than necessary. To address this issue, consider using the Jinja variable target.name to [limit data when working in the development environment](/reference/dbt-jinja-functions/target#use-targetname-to-limit-data-in-dev).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +## Refreshing Your Data With Databricks Workflows
sug sentence case
```suggestion
## Refreshing your data with Databricks workflows
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +For more on performance tuning, see our guide on [How to Optimize and Troubleshoot dbt Models on Databricks](https://docs.getdbt.com/guides/dbt-ecosystem/databricks-guides/how_to_optimize_dbt_models_
```suggestion
For more on performance tuning, see our guide on [How to Optimize and Troubleshoot dbt Models on Databricks](/guides/dbt-ecosystem/databricks-guides/how_to_optimize_dbt_models_on_databricks).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +To troubleshoot issues with a dbt Cloud job, navigate to the "Deploy > Run History" tab in your dbt Cloud project and select the failed run. Then, expand the run steps to view [console and debug logs
```suggestion
To troubleshoot issues with a dbt Cloud job, navigate to the "Deploy > Run History" tab in your dbt Cloud project and select the failed run. Then, expand the run steps to view [console and debug logs](/docs/deploy/dbt-cloud-job#access-logs) to review the detailed log messages. To obtain additional information, open the Artifacts tab and download the compiled files associated with the run.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +To troubleshoot issues with a dbt Cloud job, navigate to the "Deploy > Run History" tab in your dbt Cloud project and select the failed run. Then, expand the run steps to view [console and debug logs
it makes me happy to see the deploy w dbt cloud docs/sections referenced ❤️

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Consult the [Debugging Errors documentation](https://docs.getdbt.com/guides/best-practices/debugging-errors) for a comprehensive list of error types and diagnostic methods.
```suggestion
Consult the [Debugging errors documentation](/guides/best-practices/debugging-errors) for a comprehensive list of error types and diagnostic methods.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +If you require notifications through other means than email or Slack, you can use dbt Cloud's outbound [webhooks](https://docs.getdbt.com/docs/deploy/webhooks) feature to relay job events to other to
```suggestion
If you require notifications through other means than email or Slack, you can use dbt Cloud's outbound [webhooks](/docs/deploy/webhooks) feature to relay job events to other tools. Webhooks enable you to [integrate dbt Cloud with a wide range of SaaS applications](/guides/orchestration/webhooks), extending your pipeline’s automation into other systems.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Setting up [notifications](https://docs.getdbt.com/docs/deploy/job-notifications) in dbt Cloud allows you to receive alerts via email or a Slack channel whenever a run ends. This ensures that the app
```suggestion
Setting up [notifications](/docs/deploy/job-notifications) in dbt Cloud allows you to receive alerts via email or a Slack channel whenever a run ends. This ensures that the appropriate teams are notified and can take action promptly when jobs fail or are canceled. To set up notifications:
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +By adding [status tiles](https://docs.getdbt.com/docs/deploy/dashboard-status-tiles) to your BI dashboards, you can give stakeholders visibility into the health of your data pipeline without leaving
```suggestion
By adding [status tiles](/docs/deploy/dashboard-status-tiles) to your BI dashboards, you can give stakeholders visibility into the health of your data pipeline without leaving their preferred interface. Status tiles instill confidence in your data and help prevent unnecessary inquiries or context switching. To implement dashboard status tiles, you'll need to have dbt docs with [exposures](/docs/build/exposures) defined.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +The deployment monitor in dbt Cloud offers a higher-level view of your run history, enabling you to gauge the health of your data pipeline over an extended period of time. This feature includes infor
ah damn, i have a pr for this to launch in the release notes and 'deploy w dbt cloud' section too once it GA's! I'll try to open a pr for this guide so it link to it when it GA's.

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +The [run history](https://docs.getdbt.com/docs/deploy/dbt-cloud-job) dashboard in dbt Cloud provides a detailed view of all your project's job runs, offering various filters to help you focus on spec
```suggestion
The [run history](/docs/deploy/dbt-cloud-job) dashboard in dbt Cloud provides a detailed view of all your project's job runs, offering various filters to help you focus on specific aspects. This is an excellent tool for developers who want to check recent runs, verify overnight results, or track the progress of running jobs. To access it, select **Run History** from the **Deploy** menu.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +        - Combining [state](https://docs.getdbt.com/docs/deploy/project-state) with the defer option above, our job will use the production environment’s models upstream of the modified resources rat
```suggestion
        - Combining [state](/docs/deploy/project-state) with the defer option above, our job will use the production environment’s models upstream of the modified resources rather than rebuild models that have already been tested and are already running in production. The modified resources and downstream models will be built in a temporary schema in the *test* catalog.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +We recommend using dbt Cloud’s [defer](https://docs.getdbt.com/docs/deploy/cloud-ci-job#deferral-and-state-comparison) feature to set up a [Slim CI](https://docs.getdbt.com/docs/deploy/cloud-ci-job#c
```suggestion
We recommend using dbt Cloud’s [defer](/docs/deploy/cloud-ci-job#deferral-and-state-comparison) feature to set up a [Slim CI](/docs/deploy/cloud-ci-job#configuring-a-slim-ci-job) job. This will decrease the job’s runtime by running and testing only modified models, which also reduces compute spend on the lakehouse.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Your CI job will ensure that the models build properly and pass any tests applied to them. We recommend creating a separate *test* environment and having a dedicated service principal. This will ensu
```suggestion
Your CI job will ensure that the models build properly and pass any tests applied to them. We recommend creating a separate *test* environment and having a dedicated service principal. This will ensure the temporary schemas created during CI tests are in their own catalog and cannot unintentionally expose data to other users. Repeat the [steps](/guides/dbt-ecosystem/databricks-guides/how-to-set-up-your-databricks-dbt-project) used to create your *prod* environment to create a *test* environment. After setup, you should have:
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +dbt allows you to write [tests](https://docs.getdbt.com/docs/build/tests) for your data pipeline, which can be run at every step of the process to ensure the stability and correctness of your data tr
```suggestion
dbt allows you to write [tests](/docs/build/tests) for your data pipeline, which can be run at every step of the process to ensure the stability and correctness of your data transformations. The main places you’ll use your dbt tests are:
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +After your job is set up and runs successfully, configure your **[project artifacts](https://docs.getdbt.com/docs/deploy/artifacts)** to to make this job inform your production docs site and data sou
```suggestion
After your job is set up and runs successfully, configure your **[project artifacts](/docs/deploy/artifacts)** to make this job inform your production docs site and data sources dashboard that can be reached from the UI.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +This is just one example of an all-or-nothing command list designed to minimize wasted compute. The [job command list](https://docs.getdbt.com/docs/deploy/job-commands) and [selectors](https://docs.g
```suggestion
This is just one example of an all-or-nothing command list designed to minimize wasted computing. The [job command list](/docs/deploy/job-commands) and [selectors](/reference/node-selection/syntax) provide a lot of flexibility on how your DAG will execute. You may want to design yours to continue running certain models if others fail. You may want to set up multiple jobs to refresh models at different frequencies. See our [Job Creation Best Practices discourse](https://discourse.getdbt.com/t/job-creation-best-practices-in-dbt-cloud-feat-my-moms-lasagna/2980) for more job design suggestions.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +    - If you want your dbt Cloud job scheduled by another orchestrator, like Databricks Workflows, see the Advanced Considerations section below.
```suggestion
    - If you want your dbt Cloud job scheduled by another orchestrator, like Databricks Workflows, see the Advanced Considerations section below.
```
```suggestion
    - If you want your dbt Cloud job scheduled by another orchestrator, like Databricks Workflows, see the [Advanced Considerations](#advanced-considerations) section below.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +This is just one example of an all-or-nothing command list designed to minimize wasted compute. The [job command list](https://docs.getdbt.com/docs/deploy/job-commands) and [selectors](https://docs.g
```suggestion
This is just one example of an all-or-nothing command list designed to minimize wasted computing. The [job command list](/docs/deploy/job-commands) and [selectors](/reference/node-selection/syntax) provide a lot of flexibility on how your DAG will execute. You may want to design yours to continue running certain models if others fail. Or you may want to set up multiple jobs to refresh models at different frequencies. For more job design suggestions. check out [Job Creation Best Practices discourse](https://discourse.getdbt.com/t/job-creation-best-practices-in-dbt-cloud-feat-my-moms-lasagna/2980).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +The steps below show how to create a CI test for your dbt project. Continuous Deployment (CD) in dbt Cloud requires no additional steps, as your jobs will automatically pick up the latest changes fro
```suggestion
The steps below show how to create a CI test for your dbt project. CD in dbt Cloud requires no additional steps, as your jobs will automatically pick up the latest changes from the branch assigned to the environment your job is running in. You may choose to add steps depending on your deployment strategy. If you want to dive deeper into CD options, check out [this blog on adopting CI/CD with dbt Cloud](https://www.getdbt.com/blog/adopting-ci-cd-with-dbt-cloud/).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +2. Select the "Notifications" tab.
```suggestion
2. Select the **Notifications** tab.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +5. Seek help from the dbt Cloud support team if needed.
```suggestion
5. Seek help from the [dbt Cloud support team](/docs/dbt-support) if needed.
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +## Advanced Considerations
```suggestion
## Advanced considerations
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +### Refreshing Your Data With Databricks Workflows
```suggestion
### Refreshing your data with Databricks Workflows
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +To trigger your dbt Cloud job from Databricks, follow the instructions in our [Databricks Workflows to run dbt Cloud jobs guide](https://docs.getdbt.com/guides/orchestration/how-to-use-databricks-wor
```suggestion
To trigger your dbt Cloud job from Databricks, follow the instructions in our [Databricks Workflows to run dbt Cloud jobs guide](/guides/orchestration/how-to-use-databricks-workflows-to-run-dbt-cloud-jobs).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +Our [Best Practices for dbt and Unity Catalog](https://docs.getdbt.com/guides/dbt-ecosystem/databricks-guides/dbt-unity-catalog-best-practices) guide recommends using separate catalogs *dev* and *pro
```suggestion
Our [Best Practices for dbt and Unity Catalog](/guides/dbt-ecosystem/databricks-guides/dbt-unity-catalog-best-practices) guide recommends using separate catalogs *dev* and *prod* for development and deployment environments, with Unity Catalog and dbt Cloud handling configurations and permissions for environment isolation. Ensuring security while maintaining efficiency in your development and deployment environments is crucial. Additional security measures may be necessary to protect sensitive data, such as personally identifiable information (PII).
```

2023-04-28 11:09 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +The deployment monitor in dbt Cloud offers a higher-level view of your run history, enabling you to gauge the health of your data pipeline over an extended period of time. This feature includes infor
might be nice to add a screenshot if we can share that?

2023-04-28 15:49 UTC, asteichen reviewed
Made updates based on Mirna's fixes!

2023-04-28 15:50 UTC, mirnawong1 approved these changes, later dismissed
thanks for opening this up @asteichen - approved for you to 🚢 !!

2023-04-28 15:52 UTC, mirnawong1 commented on website/docs/guides/dbt-ecosystem/databricks-guides/productionizing-your-dbt-databricks-project.md
> +<Lightbox src="/img/guides/databricks-guides/deployment_monitor_dbx.png" title="The Deployment Monitor Shows Job Status Over Time Across Environments" />
```suggestion
<Lightbox src="/img/guides/databricks-guides/deployment_monitor_dbx.png" width="85%" title="The Deployment Monitor Shows Job Status Over Time Across Environments" />
```

2023-04-28 15:52 UTC, mirnawong1 approved these changes

2023-04-28 15:54 UTC, mirnawong1 approved these changes

2023-04-28 16:05 UTC, merged