update Python minimum version to 3.8
fishtown-analytics/docs.getdbt.com pull request #3369
Opened 2023-05-15 04:58 UTC by sdebruyn

## What are you changing in this pull request and why?
Docs change for PR https://github.com/dbt-labs/dbt-core/pull/7623 / issue https://github.com/dbt-labs/dbt-core/issues/7082

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

2023-05-15 15:56 UTC, dbeatty10 requested changes
Thanks for raising this PR @sdebruyn !

This review has a couple suggestions that I will commit in a moment.

2023-05-15 15:56 UTC, dbeatty10 commented on website/docs/faqs/Core/install-pip-os-prereqs.md
> +If you need a compatible version, you can download and install [Python version 8 or higher for MacOS](https://www.python.org/downloads/macos).
```suggestion
If you need a compatible version, you can download and install [Python version 3.8 or higher for MacOS](https://www.python.org/downloads/macos).
```

2023-05-15 15:56 UTC, dbeatty10 commented on website/docs/faqs/Core/install-python-compatibility.md
> +description: "Python versions 8 and newer can be used with dbt Core"
```suggestion
description: "Python versions 3.8 and newer can be used with dbt Core"
```

2023-05-15 16:15 UTC, dbeatty10 approved these changes, later dismissed
We haven't made a drop-down menu item for the 1.6 version of the docs yet, but I confirmed in the preview that it didn't create problems to include this ahead of time so it is ready when the time comes.

https://deploy-preview-3369--docs-getdbt-com.netlify.app/faqs/core/install-python-compatibility?version=1.6

Could you be extra confirmation @mirnawong1 ?

2023-05-15 16:17 UTC, sdebruyn commented
> Thanks for raising this PR @sdebruyn !
> 
> This review has a couple suggestions that I will commit in a moment.

Sorry, looks like I wasn't wearing my glasses while typing those `3.8`s 😂

2023-05-16 11:16 UTC, mirnawong1 commented on website/docs/faqs/Core/install-pip-os-prereqs.md
> +Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.8 or higher for Windows](https://www.python.org/downloads/windows/).
```suggestion

Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.8 or higher for Windows](https://www.python.org/downloads/windows/).
```

2023-05-16 11:16 UTC, mirnawong1 commented on website/docs/faqs/Core/install-pip-os-prereqs.md
>  Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.7 or higher for Windows](https://www.python.org/downloads/windows/).
```suggestion

Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.7 or higher for Windows](https://www.python.org/downloads/windows/).
```

2023-05-16 11:16 UTC, mirnawong1 commented on website/docs/faqs/Core/install-pip-os-prereqs.md
>  Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.7 or higher for Windows](https://www.python.org/downloads/windows/).
```suggestion

Install [Git for Windows](https://git-scm.com/downloads) and [Python version 3.7 or higher for Windows](https://www.python.org/downloads/windows/).
```

2023-05-16 12:21 UTC, mirnawong1 commented
This is awesome, thank you for opening this up @sdebruyn and for looking it over @dbeatty10 ! I made some small tweaks because the linked text wasn't rendering correctly due to spacing (see screenshot) but [it looks](https://deploy-preview-3369--docs-getdbt-com.netlify.app/faqs/core/install-pip-os-prereqs.md) great now! confirm the drop down works fine and doesn't harm the user experience. approved on my end, wdyt @dbeatty10 ?

![Screenshot 2023-05-16 at 12 16 43](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/e76c466a-1ed4-425b-adbb-624395bd932b)

2023-05-16 12:22 UTC, mirnawong1 approved these changes

2023-05-16 12:22 UTC, mirnawong1 approved these changes

2023-05-16 12:29 UTC, dbeatty10 approved these changes

2023-05-16 12:43 UTC, dbeatty10 commented
Looks great to meet @mirnawong1 -- squashing and merging.

2023-05-16 12:44 UTC, merged