add --state option to the result method example
fishtown-analytics/docs.getdbt.com pull request #3413
Opened 2023-05-24 09:13 UTC by bsuryachandra

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-05-24 13:12 UTC, mirnawong1 commented
hey @bsuryachandra thanks for opening this pr! we'll have a look at this for you soon!

2023-06-09 12:53 UTC, mirnawong1 commented on website/docs/reference/node-selection/methods.md
>  The `result` method is related to the `state` method described above, and can be used to select resources based on their result status from a prior run. Note that one of the dbt commands [`run`, `tes
```suggestion
The `result` method is related to the `state` method described above and can be used to select resources based on their result status from a prior run. Note that one of the dbt commands [`run`, `test`, `build`, `seed`] must have been performed in order to create the result on which a result selector operates. You can use `result` selectors in conjunction with the `+` operator. 
```

2023-06-09 12:58 UTC, mirnawong1 commented on website/docs/reference/node-selection/methods.md
```suggestion
**Note** &mdash; When you use dbt Cloud, please be aware that the `--state` parameter is automatically included when you click the [**Defer**](/docs/deploy/cloud-ci-job#deferral-and-state-comparison) button.
```

2023-06-09 13:21 UTC, b-per requested changes, later dismissed
Minor change

2023-06-09 13:21 UTC, b-per commented on website/docs/reference/node-selection/methods.md
> +**Note** &mdash; When you use dbt Cloud, please be aware that the `--state` parameter is automatically included when you click the [**Defer**](/docs/deploy/cloud-ci-job#deferral-and-state-comparison)
```suggestion
**Note** &mdash; When you define steps in your dbt Cloud jobs, please be aware that the `--state` parameter is automatically included when you click the [**Defer**](/docs/deploy/cloud-ci-job#deferral-and-state-comparison) button.
```

2023-06-09 13:21 UTC, b-per commented on website/docs/reference/node-selection/methods.md
> +**Note** &mdash; When you use dbt Cloud, please be aware that the `--state` parameter is automatically included when you click the [**Defer**](/docs/deploy/cloud-ci-job#deferral-and-state-comparison)
The only slight clarification is that `--state` is automatically added for **job steps** when the deferral box is ticked.

In the IDE for example people would still have to type `--state ...`

2023-06-09 13:28 UTC, mirnawong1 commented
thanks for that clarification @b-per !

2023-06-09 14:30 UTC, mirnawong1 commented
hey @bsuryachandra, thanks again for opening this pr and contributing to the docs ✨ with Benoit's help, i made some small tweaks to further clarify. going to merge this now and looking forward to future contributions!

2023-06-09 14:30 UTC, mirnawong1 approved these changes

2023-06-09 14:31 UTC, merged

2023-06-09 18:43 UTC, bsuryachandra commented
Thanks for your help @mirnawong1