Create may-ide-updates.md
fishtown-analytics/docs.getdbt.com pull request #3447
Opened 2023-05-31 23:25 UTC by runleonarun

## What are you changing in this pull request and why?

Creates release note for IDE changes. 

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-05-31 23:49 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +sidebar_position: 7
```suggestion
sidebar_position: 2
```

2023-05-31 23:54 UTC, bossnunta requested changes
can you also help add the BUGS section from the original post in as well

2023-05-31 23:54 UTC, bossnunta commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including `Ctrl + `` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edito
the CTRL + ` is funky looking

2023-05-31 23:55 UTC, bossnunta commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Lint via SQLFluff in beta (reach out if interested, otherwise this will be available for multi-tenant soon!)
let's just say "Lint via SQL Fluff is now available in beta (GA over the next 2-3 weeks)" and remove the comment about reach out

2023-06-01 00:06 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Lint via SQLFluff in beta (reach out if interested, otherwise this will be available for multi-tenant soon!)
```suggestion
- Lint via SQL Fluff is now available in beta (GA over the next 2-3 weeks)
```

2023-06-01 00:07 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including `Ctrl + `` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edito
```suggestion
- Leverage developer experience shortcuts, including `Ctrl + /`` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close editor tab)
```

2023-06-01 00:09 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +## Product refinements
```suggestion
## Product refinements 

```

2023-06-01 00:13 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Made many security enhancements in the IDE
```suggestion
- Made many security enhancements in the IDE
## Bug fixes

- File icon sizes no longer get wonky in small screen
- Toast notifications no longer take over command bar menu
- Hover info inside the text editor no longer gets cut off
- Transition between a file and a recently modified scratchpad no longer triggers a console error
- dbt v1.5+ now can access the IDE
- Confirm button on the Unsaved Changes modal now closes after clicking it
- Long node names no longer overflow in the parsed logs section in history drawer
- Status pill in history drawer no longer scales with longer command
- Tooltip for tab name with a long file name is no longer cut off
- Lint button should no longer available in main branch
```

2023-06-01 00:15 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including `Ctrl + /`` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edit
```suggestion
- Leverage developer experience shortcuts, including `Ctrl + \`` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close editor tab)
```

2023-06-01 00:16 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including `Ctrl + \`` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edit
```suggestion
- Leverage developer experience shortcuts, including `Ctrl + \`` (toggle history drawer), `CMD + Option + \/` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close editor tab)
```

2023-06-01 00:22 UTC, runleonarun commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including `Ctrl + \`` (toggle history drawer), `CMD + Option + \/` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edi
```suggestion
- Leverage developer experience shortcuts, including ``Ctrl +` `` (toggle history drawer), `CMD + Option + \/` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close editor tab)
```

2023-06-01 09:44 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +To continue improving your [Cloud IDE](https://docs.getdbt.com/docs/cloud/develop-in-the-cloud) development experience, the dbt Labs team continues to work on adding new features, fixing bugs, and in
```suggestion
To continue improving your [Cloud IDE](/docs/cloud/develop-in-the-cloud) development experience, the dbt Labs team continues to work on adding new features, fixing bugs, and increasing reliability ✨.
```

2023-06-01 09:44 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +Stay up-to-date with [IDE-related changes](https://docs.getdbt.com/tags/ide).
```suggestion
Stay up-to-date with [IDE-related changes](/tags/ide).
```

2023-06-01 09:44 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +description: "May 2023 release note: We've ."
```suggestion
description: "May 2023 release note: We've launched SQL Fluff in beta, released an IDE UI page, significantly improved IDE performance, improved error messages, fixed bugs, and more."
```

2023-06-01 09:45 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Leverage developer experience shortcuts, including ``Ctrl +` `` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close edi
```suggestion
- Leverage developer experience shortcuts, including ``Ctrl + ` `` (toggle history drawer), `CMD + Option + /` (toggle block comment), `CMD + Shift + P` (open command palette), `Option + W` (close editor tab)
```

2023-06-01 09:46 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +    - Improved IDE performance with dbt Core v1.5+ (faster and snappier – highly encourage you to update your dbt version!)
sugg linking to upgrade page

```suggestion
    - Improved IDE performance with dbt Core v1.5+ (faster and snappier – highly encourage you to [upgrade your dbt version](/docs/dbt-versions/upgrade-core-in-cloud)!)
```

2023-06-01 10:23 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +To continue improving your [Cloud IDE](/docs/cloud/develop-in-the-cloud) development experience, the dbt Labs team continues to work on adding new features, fixing bugs, and increasing reliability ✨.
```suggestion
To continue improving your [Cloud IDE](/docs/cloud/dbt-cloud-ide/develop-in-the-cloud) development experience, the dbt Labs team continues to work on adding new features, fixing bugs, and increasing reliability ✨.
```

2023-06-01 10:24 UTC, mirnawong1 commented on website/docs/docs/dbt-versions/release-notes/08-May-2023/may-ide-updates.md
> +- Navigate the new IDE features quickly using [the IDE User Interface](https://docs.getdbt.com/docs/cloud/dbt-cloud-ide/ide-user-interface) help page
```suggestion
- Navigate the new IDE features quickly using [the IDE User Interface](/docs/cloud/dbt-cloud-ide/ide-user-interface) help page
```

2023-06-01 16:41 UTC, bossnunta approved these changes
looks good to me!

2023-06-01 16:41 UTC, bossnunta approved these changes
looks good to me!

2023-06-06 01:58 UTC, merged