Update develop-in-the-cloud.md
fishtown-analytics/docs.getdbt.com pull request #3603
Opened 2023-06-22 08:25 UTC by mirnawong1

adding info the `exclude` flag isnt supported

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-06-22 22:08 UTC, patkearns10 requested changes
Otherwise, looks good!

2023-06-22 22:08 UTC, patkearns10 commented on website/docs/docs/cloud/dbt-cloud-ide/ide-user-interface.md
>      - Expand the DAG and use node selection syntax (select or exclude) to view a subset of your DAG
Line 103 should probably change to exclude the exclude prompt!
from
```
- Expand the DAG and use node selection syntax (select or exclude) to view a subset of your DAG
```
to
```
Expand or shrink the DAG using node selection syntax
```

2023-06-23 06:03 UTC, mirnawong1 commented
Nice catch @patkearns10 ! Have made that change, can you give it another look?

2023-06-23 07:49 UTC, patkearns10 approved these changes

2023-06-23 07:50 UTC, patkearns10 commented
🌵 LGTM!

2023-06-23 08:00 UTC, merged