Draft of modeling ragged time-varying hierarchies
fishtown-analytics/docs.getdbt.com pull request #3676
Opened 2023-07-05 18:32 UTC by gnilrets

## What are you changing in this pull request and why?
Resolves #3328 

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-07-11 20:30 UTC, joellabes commented
Oh my gosh this is so cool 👀👀👀👀👀👀👀

I will read this through and give any feedback in the sprint after this (so end of this month/start of next)

Thank you! 🚲

2023-07-24 21:00 UTC, joellabes requested changes
Loved reading this 🤩 excited to get it up! 

A handful of comments based on things that tripped me up while reading through, but this is basically ready to rock 🎉 

Side note: here's what it looks like on the preview site if you haven't found that yet https://deploy-preview-3676--docs-getdbt-com.netlify.app/blog/modeling-ragged-time-varying-hierarchies

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +Our ERP system (Enterprise Resource Management) contains records that log when a specific component serial number (`component_id`) was installed in or removed from a parent assembly component (`assem
```suggestion
Our ERP system (Enterprise Resource Planning) contains records that log when a specific component serial number (`component_id`) was installed in or removed from a parent assembly component (`assembly_id`).  The top-most assembly component is the eBike itself, which has no parent assembly.  So when an eBike (specifically, the eBike with serial number "Bike-1") is originally constructed, the ERP system would contain records that look like the following.
```

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Wheel-2       | Rim-2          | 2023-08-01     |              |
Somewhere around here I started thinking that `Wheel-2` was the second wheel in this bi-cycle, instead of the second replacement of a single wheel. It might be useful to call out under the first hierarchy diagram that we are ignoring one of the wheels, or change to an e-unicycle company? 

Or I can try harder at suspension of disbelief - I don't feel super strongly about this but it did confuse me for a sec.

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +This hierarchy is *ragged* because different paths through the hierarchy terminate at different depths.  It is *time-varying* because specific components can be added and removed.
This is such a great explanation 👨‍🍳💋

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Bike-1        | Wheel-1        | 2023-01-01     | 2023-08-01   |
```suggestion
| -             | -              | -              | -            |
| ...           | ...            | ...            | ...          |
| Bike-1        | Wheel-1        | 2023-01-01     | 2023-08-01   |
```

Might make it clearer that this is a subset of the table instead of the whole (This could also apply to the table above, but two rows makes it way more obvious that it's a subset)

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Tire-1        | Tube-2         | 2023-06-01     |              | # New record
If you want the comments column to come through, I think you'll need to enclose it in pipes on the end too, they're not coming through at the mo:
 
<img width="1016" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/7335046/3d801d56-bb31-4918-acec-73f6dede40fa">

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| bsk1      | csk1           | 2023-01-01   | 3       |
I don't yet know what the components represented by the `csk`s are - is the key in your example incremented every time the state of the bike changes somehow? (i.e. it incremented after the flat tire and again after the crash). Hoping I'll work it out as I keep reading

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +Dealing with all of the components is more complicated because there are many components installed on the same day.  The relationship between days when the bikes are ridden and the components is thus
> Hoping I'll work it out as I keep reading

I guessed right! It might be worth adding a quick clarifying sentence when you first introduce `fct_daily_mileage`, either explaining what it is or making clear that the reader doesn't need to spend any time on that column yet and it'll be covered later

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| bsk1      | csk4           | 2023-08-03   | 4       |
Given that your examples only get up to csk3, might be less confusing if that was what this key was too

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +This structure simplifies other kinds of interesting analysis.  Suppose we wanted to start exploring how one component affects another.  We can easily do this by partitioning the data into the segmen
This bit feels a bit more abstract than the rest - is there an example of something concrete you might do with the results of this query?

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +The key here is to use a recursive join to move from the top of the hierarchy to all children and grandchildren.  The top of the hierarchy is easy to identify because they are the only records withou
```suggestion
The key here is to use a [recursive join](https://docs.snowflake.com/en/sql-reference/constructs/with#recursive-clause) to move from the top of the hierarchy to all children and grandchildren.  The top of the hierarchy is easy to identify because they are the only records without any parents.
```

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +* `top_assembly_id` - This is the most important output of the hierarchy traversal.  It ties all sub components to a their common parent.  We'll use this in the next step to chop up the hierarchy int
This is when the component sk changes right?

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +        least(traversal.valid_to_at, components.valid_to_at) as valid_to_at
This comment doesn't map with the discussion below of handing cases where a parent is removed but not its children, does it? I don't see any overlap handling in these lines

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +The last step is perform a [temporal range join](https://discourse.getdbt.com/t/joining-snapshot-tables-time-range-based-joins/3226) between the top assembly and all of its descendents.  This [tempor
```suggestion
The last step is perform a [temporal range join](https://discourse.getdbt.com/t/joining-snapshot-tables-time-range-based-joins/3226) between the top assembly and all of its descendents.  This is what splits out all of the time-varying component changes into distinct ranges of time where the component hierarchy is constant.  This range join makes use of [the dbt macro in this gist](https://gist.github.com/gnilrets/48886b4c8945dde1da13547c2373df73), the operation of which is out-of-scope for this article, but you are encouraged to investigate it and the discourse post mentioned earlier.
```

2023-07-24 21:00 UTC, joellabes commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +description: "Learn how maximize the utility of complex hierarchical data in your analytics warehouse."
```suggestion
description: "Learn how to maximize the utility of complex hierarchical data in your analytics warehouse."
```

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Wheel-2       | Rim-2          | 2023-08-01     |              |
Attempted to clarify.

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +Our ERP system (Enterprise Resource Management) contains records that log when a specific component serial number (`component_id`) was installed in or removed from a parent assembly component (`assem
Change made

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +This hierarchy is *ragged* because different paths through the hierarchy terminate at different depths.  It is *time-varying* because specific components can be added and removed.
Thanks!

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Bike-1        | Wheel-1        | 2023-01-01     | 2023-08-01   |
This section does show the whole table, but the table above is partial.  I've added the `...` to that one.

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| Tire-1        | Tube-2         | 2023-06-01     |              | # New record
That was just for me.  Removed in the markdown.

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +| bsk1      | csk1           | 2023-01-01   | 3       |
Ok, I've moved the description of these fields to right before where they are introduced.

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +This structure simplifies other kinds of interesting analysis.  Suppose we wanted to start exploring how one component affects another.  We can easily do this by partitioning the data into the segmen
Attempted to clarify

2023-07-24 22:27 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +The key here is to use a recursive join to move from the top of the hierarchy to all children and grandchildren.  The top of the hierarchy is easy to identify because they are the only records withou
Change made

2023-07-24 22:28 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +* `top_assembly_id` - This is the most important output of the hierarchy traversal.  It ties all sub components to a their common parent.  We'll use this in the next step to chop up the hierarchy int
Added clarifying text

2023-07-24 22:28 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +        least(traversal.valid_to_at, components.valid_to_at) as valid_to_at
I've attempted to rewrite this comment to clarify what this is doing.

IIRC, this just reduced the number of records that need to be deduplicated and is mostly a minor performance improvement than any required logic.

2023-07-24 22:28 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +The last step is perform a [temporal range join](https://discourse.getdbt.com/t/joining-snapshot-tables-time-range-based-joins/3226) between the top assembly and all of its descendents.  This [tempor
Change made

2023-07-24 22:28 UTC, gnilrets commented on website/blog/2023-05-02-modeling-ragged-time-varying-hierarchies.md
> +description: "Learn how maximize the utility of complex hierarchical data in your analytics warehouse."
Change made

2023-07-24 22:28 UTC, gnilrets commented
@joellabes - Changes made, PTAL.

2023-07-24 23:46 UTC, joellabes approved these changes
Magnificent! Let's rumble 🚀

2023-07-24 23:50 UTC, merged