Update redshift-configs.md
fishtown-analytics/docs.getdbt.com pull request #3822
Opened 2023-07-26 15:50 UTC by Rafalem29

The existing sort key and dist key examples don't really align with Redshift's best practices. I wanted to propose changes that imply low-cardinality sort keys (which are preferable) and very high cardinality dist keys to ensure parallelism.

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

2023-09-13 16:20 UTC, dataders commented
> changes that imply low-cardinality sort keys (which are preferable) and very high cardinality dist keys to ensure parallelism.

I'm all for this change, but can we go one step further beyond "imply"? Can we not add a sentence that explicitly calls out this best practice?

2023-09-13 16:21 UTC, dataders requested changes
> changes that imply low-cardinality sort keys (which are preferable) and very high cardinality dist keys to ensure parallelism.

I'm all for this change, but can we go one step further beyond "imply"? Can we not add a sentence that explicitly calls out this best practice?

2023-09-13 16:45 UTC, Rafalem29 commented
Oh certainly, I'm in favor of calling this out in the most plain-spoken, clear way possible. I just didn't want to duplicate effort or re-invent the AWS Redshift documentation.

2023-09-13 19:36 UTC, dataders commented
> Oh certainly, I'm in favor of calling this out in the most plain-spoken, clear way possible. I just didn't want to duplicate effort or re-invent (sorry, accidental pun) the AWS Redshift documentation.

I'll take any language you propose!

2023-09-14 03:21 UTC, Rafalem29 commented
I think the links to AWS documentation and the modifications to the examples to point to what are, presumably, low-cardinality columns should suffice for now.

2024-02-12 19:53 UTC, matthewshaver commented on website/docs/reference/resource-configs/redshift-configs.md
> +When working with sort keys, it's highly recommended you follow [Redshift's best practices](https://docs.aws.amazon.com/prescriptive-guidance/latest/query-best-practices-redshift/best-practices-table
```suggestion
When working with sort keys, it's highly recommended you follow [Redshift's best practices](https://docs.aws.amazon.com/prescriptive-guidance/latest/query-best-practices-redshift/best-practices-tables.html#sort-keys) on sort key effectiveness and cardinality. 
```

2024-02-12 19:53 UTC, matthewshaver approved these changes

2024-02-12 19:54 UTC, matthewshaver commented
Thank you @Rafalem29 Sorry this took so long to implement

2024-08-07 16:12 UTC, merged

2024-08-07 16:12 UTC, matthewshaver commented
Author had addressed previous comments. Went ahead with the merge