Alpha docs for CLI
fishtown-analytics/docs.getdbt.com pull request #3879
Opened 2023-08-07 21:31 UTC by matthewshaver

## What are you changing in this pull request and why?

Adding alpha documentation for the Cloud CLI

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

2023-08-08 00:06 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +**More informaiton coming soon**
```suggestion
**Coming soon**
```

2023-08-08 18:32 UTC, greg-mckeon requested changes
took a pass! let me know if anything is unclear

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +
Could we make "upgrading" an aside or a callout? It currently feels like a necessary next step.

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +### Install and update with Brew (recommended)
"### Install and update with Brew on MacOS (recommended)"

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +### Manually install (Windows only)
"### Manually install (Windows and Linux)"

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +1. Download the latest darwin release from [Github](https://github.com/dbt-labs/dbti/releases).
"Download the latest release for your platform from [Github](https://github.com/dbt-labs/dbt-cli/releases)."

Note that the url changed

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +2. Place the `dbt` executable in `/usr/local/bin` or `/usr/.local/bin` if `/usr/local/bin` doesn’t exist.
Replace 2+3 with:
"Add the `dbt` executable to your path."

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +#### Updating dbt Cloud installation (Windows only)
Change to "#### Updating dbt Cloud installation (Windows + Linux)"

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +1. Ensure that you have created a project in dbt Cloud.
Add link to https://cloud.getdbt.com/

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +3. Create an environment variable with your [dbt cloud API key](#glossary):
Replace link to point to "https://cloud.getdbt.com/settings/profile#api-access"

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +2. Ensure that your personal [development credentials](#glossary) are set on the project
Add link to https://cloud.getdbt.com/settings/profile/credentials

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +
"You can find your project id by selecting your project and clicking on "documentation" in the navigation bar.  Your project id is the number in the url: https://cloud.getdbt.com/documentation/1/projects/{project id}.

2023-08-08 18:32 UTC, greg-mckeon commented on website/docs/docs/cloud/cloud-cli-installation.md
> +- **dbt cloud API key:** your API key found by navigating to the **gear icon**, clicking **Profile Settings**, and scrolling down to **API**.
Nice, didn't see these.  I think we can just link for the cloud API key, but keep the other ones in the glossary.

2023-08-09 19:25 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +### Install and update with Brew (recommended)
```suggestion
### Install and update with Brew on MacOS (recommended)
```

2023-08-09 19:25 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +### Manually install (Windows only)
```suggestion
### Manually install (Windows and Linux)
```

2023-08-09 19:29 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +1. Download the latest darwin release from [Github](https://github.com/dbt-labs/dbti/releases).
```suggestion
1. Download the latest darwin release from [Github](https://github.com/dbt-labs/dbt-cli/releases).
```

2023-08-09 19:29 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +2. Place the `dbt` executable in `/usr/local/bin` or `/usr/.local/bin` if `/usr/local/bin` doesn’t exist.
```suggestion
2. Add the `dbt` executable to your path.
```

2023-08-09 19:30 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +3. Navigate to `/usr/local/bin` / `/usr/.local/bin` in Finder and double click on the `dbt` executable:
```suggestion
3. Navigate to your `dbt` path in Finder and double-click on the `dbt` executable:
```

2023-08-09 19:30 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +#### Updating dbt Cloud installation (Windows only)
```suggestion
#### Updating dbt Cloud installation (Windows + Linux)
```

2023-08-09 20:23 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +1. Ensure that you have created a project in dbt Cloud.
```suggestion
1. Ensure that you have created a project in [dbt Cloud](https://cloud.getdbt.com/).
```

2023-08-09 20:23 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +2. Ensure that your personal [development credentials](#glossary) are set on the project
```suggestion
2. Ensure that your personal [development credentials](#glossary) are set on the project ([link](https://cloud.getdbt.com/settings/profile/credentials)).
```

2023-08-09 20:25 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +3. Create an environment variable with your [dbt cloud API key](#glossary):
```suggestion
3. Create an environment variable with your [dbt cloud API key](https://cloud.getdbt.com/settings/profile#api-access):
```

2023-08-09 20:27 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +
```suggestion
You can find your project ID by selecting your project and clicking on **documentation** in the navigation bar. Your project ID is the number in the URL: https://cloud.getdbt.com/documentation/1/projects/{project id}.
```

2023-08-09 20:27 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +2. Ensure that your personal [development credentials](#glossary) are set on the project
```suggestion
2. Ensure that your personal [development credentials](https://cloud.getdbt.com/settings/profile/credentials) are set on the project
```

2023-08-09 20:28 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +1. Ensure that you have created a project in dbt Cloud.
```suggestion
1. Ensure that you have created a project in [dbt Cloud](https://cloud.getdbt.com/).
```

2023-08-09 20:28 UTC, matthewshaver commented on website/docs/docs/cloud/cloud-cli-installation.md
> +Upgrade the CLI:
```suggestion
### Upgrade the CLI:
```

2023-08-09 21:16 UTC, greg-mckeon approved these changes

2023-08-09 21:31 UTC, merged