add time granularity
fishtown-analytics/docs.getdbt.com pull request #3881
Opened 2023-08-07 22:58 UTC by Jstein77

## What are you changing in this pull request and why?
Adding time granularity options to the CLI docs.

2023-08-07 23:06 UTC, gwenwindflower requested changes

2023-08-07 23:06 UTC, gwenwindflower commented on website/docs/docs/build/metricflow-cli.md
> +You can optionally specify the time granularity you want your data to be aggregated at by appending double underscore and the unit of granularity you want against your. The granularity options are: d
```suggestion
You can optionally specify the time granularity you want your data to be aggregated at by appending double underscore and the unit of granularity you want to the global time dimension `metric_time`. The granularity options to group by are: day, week, month, quarter year. 
```

2023-08-07 23:10 UTC, nghi-ly commented on website/docs/docs/build/metricflow-cli.md
> +## Time Granularity
our style in the docs is to use sentence case (vs title case) 

```suggestion
## Time granularity
```

2023-08-07 23:17 UTC, nghi-ly reviewed
Thank you for adding this, @Jstein77 ! left a few minor suggs

2023-08-07 23:17 UTC, nghi-ly commented on website/docs/docs/build/metricflow-cli.md
> +You can optionally specify the time granularity you want your data to be aggregated at by appending double underscore and the unit of granularity you want to the global time dimension `metric_time`.
```suggestion
Optionally, you can specify the time granularity you want your data to be aggregated at by appending two underscores and the unit of granularity you want to `metric_time`, the global time dimension . You can group the granularity by: `day`, `week`, `month`, `quarter`, and `year`. 
```

2023-08-07 23:17 UTC, nghi-ly commented on website/docs/docs/build/metricflow-cli.md
> +An example for querying metric data at a monthly grain would look like this
```suggestion
Below is an example for querying metric data at a monthly grain:
```

2023-08-07 23:19 UTC, nghi-ly commented on website/docs/docs/build/metricflow-cli.md
> +You can optionally specify the time granularity you want your data to be aggregated at by appending double underscore and the unit of granularity you want to the global time dimension `metric_time`.
i added ticks around the groups because i understood it to mean the "text" to use after the "__". please ignore if i'm mistaken

2023-08-07 23:29 UTC, nghi-ly approved these changes
:shipit:

2023-08-08 16:21 UTC, gwenwindflower approved these changes

2023-08-08 16:21 UTC, merged