add relation examples for {{this}}
fishtown-analytics/docs.getdbt.com pull request #4011
Opened 2023-09-04 11:41 UTC by mirnawong1

this pr expand options for {{this}} and use keywords/related docs to improve linkage. This was flagged by @alison985 in the [dbt slack community](https://getdbt.slack.com/archives/C0441GSRU04/p1692113239216959).

Resolves #3939

2023-09-08 00:06 UTC, patkearns10 approved these changes
LGTM! 🌵

2023-09-11 11:06 UTC, mirnawong1 commented
going to chat with joel about this tues

2023-09-16 22:31 UTC, joellabes requested changes

2023-09-16 22:31 UTC, joellabes commented on website/docs/reference/dbt-classes.md
> +dbt provides built-in relations, such as [`this`](/reference/dbt-jinja-functions/this), [`source`](/reference/dbt-jinja-functions/source), [`ref`](/reference/dbt-jinja-functions/ref).
```suggestion
```
Rephrased this and moved this to the next section

2023-09-16 22:31 UTC, joellabes commented on website/docs/reference/dbt-jinja-functions/source.md
> +  - Note &mdash; Starting from dbt v1.6 or higher, `{{ {source.identifier }}` will fetch the identifier (such as table name). Previously it would only return the request.
```suggestion
```
Unless you validated this in the IDE, I don't think it's accurate for sources, because those tables _always_ exist

2023-09-16 22:31 UTC, joellabes commented on website/docs/reference/dbt-classes.md
> +
```suggestion
In addition to `api.Relation.create`, dbt returns a Relation when you use [`ref`](/reference/dbt-jinja-functions/ref), [`source`](/reference/dbt-jinja-functions/source) or  [`this`](/reference/dbt-jinja-functions/this).
```

This isn't wrong, but it's not precise so I think it'll build an inaccurate mental model for people. It also conflicts with the code sample below, where the relation is created inside of a `{%  %} block not `{{ }}`.

2023-09-16 22:31 UTC, joellabes commented on website/docs/reference/dbt-jinja-functions/ref.md
> +  - Note &mdash; Starting from dbt v1.6 or higher, `{{ {ref.identifier }}` will fetch the identifier (such as table name). Previously it would only return the request.
```suggestion
  - Note &mdash; Prior to dbt v1.6, the dbt Cloud IDE returns `request` as the result of `{{ ref.identifier }}`.
```

2023-09-16 22:31 UTC, joellabes commented on website/docs/reference/dbt-jinja-functions/this.md
> +  - Note &mdash; Starting from dbt v1.6 or higher, `{{ {this.identifier }}` will fetch the identifier (such as table name). Previously it would only return the request.
```suggestion
  - Note &mdash; Prior to dbt v1.6, the dbt Cloud IDE returns `request` as the result of `{{ ref.identifier }}`.
```

2023-09-18 10:08 UTC, mirnawong1 commented
hey @joellabes , thanks for your amazing feedback! I've applied all your suggs - can you give it another look? [preview here](https://docs-getdbt-com-git-mwong-add-this-options-dbt-labs.vercel.app/reference/dbt-classes)

2023-09-18 23:06 UTC, joellabes approved these changes
:shipit:

2023-09-19 09:24 UTC, merged