Blog post: to defer or to clone (Publish Tues 10/31)
fishtown-analytics/docs.getdbt.com pull request #4288
Opened 2023-10-16 23:21 UTC by aranke

[Preview](https://docs-getdbt-com-git-featdeferclone-dbt-labs.vercel.app/blog/to-defer-or-to-clone)

## What are you changing in this pull request and why?

In dbt v1.6, we introduce support for zero-copy cloning via the new dbt clone command. 
In this blog post, Kshitij will cover what clone is, how it is different from deferral, and when to use each.

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

2023-10-26 19:27 UTC, jasnonaz requested changes
This post is a real banger - awesome work! Let's get the truncate in there and have it prepped for merge on Tuesday

2023-10-26 19:27 UTC, jasnonaz commented on website/blog/2023-10-27-to-defer-or-to-clone.md
> +
```SUGGESTION
<!--truncate-->

2023-10-26 19:27 UTC, jasnonaz commented on website/blog/2023-10-27-to-defer-or-to-clone.md
> +date: 2023-10-27
```SUGGESTION
date: 2023-10-31

2023-10-27 16:31 UTC, graciegoheen commented on website/blog/2023-10-31-to-defer-or-to-clone.md
> +    Therefore, we should use **defer** in this scenario
might be good to callout that clone can be helpful for handing incremental models in CI though!

2023-10-27 17:02 UTC, graciegoheen commented on website/blog/2023-10-31-to-defer-or-to-clone.md
> +    Therefore, we should use **defer** in this scenario
https://github.com/dbt-labs/docs.getdbt.com/issues/4359

2023-10-30 20:11 UTC, aranke commented on website/blog/2023-10-31-to-defer-or-to-clone.md
> +    Therefore, we should use **defer** in this scenario
I agree, but cut for sake of pacing since the "why" here will take a little bit to explain, and makes the distinction a little more fuzzy (even though it's correct).

I'll leave it out of this blog post, but happy to link to your deep dive once that is up 😄

2023-10-30 20:57 UTC, jasnonaz approved these changes
🚢

2023-10-31 15:05 UTC, matthewshaver approved these changes

2023-10-31 15:13 UTC, merged