Update pre-hook-post-hook.md
fishtown-analytics/docs.getdbt.com pull request #4393
Opened 2023-11-03 12:11 UTC by mirnawong1

clarify transactions not supported per [slack thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1695951000263009)

2023-11-03 12:11 UTC, mirnawong1 commented on website/docs/reference/resource-configs/pre-hook-post-hook.md
> +To achieve this behavior, you can use one of the following syntaxes. (Important Note: Do not use this syntax if you are using a database where dbt does not use transactions by default. This includes
```suggestion
To achieve this behavior, you can use one of the following syntaxes. (Important Note: Do not use this syntax if you are using a database where dbt does not use transactions by default. This includes databases like Snowflake, BigQuery, and Spark or Databricks.)
```

2023-11-03 12:13 UTC, mirnawong1 commented on website/docs/reference/resource-configs/pre-hook-post-hook.md
> +To achieve this behavior, you can use one of the following syntaxes. (Important Note: Do not use this syntax if you are using a database where dbt does not use transactions by default. This includes
```suggestion
To achieve this behavior, you can use one of the following syntaxes. 

Important note: Do not use this syntax if you are using a database where dbt does not use transactions by default. This includes databases like Snowflake, BigQuery, and Spark or Databricks.
```

2023-11-03 12:16 UTC, mirnawong1 commented on website/docs/reference/resource-configs/pre-hook-post-hook.md
> +<TabItem value="beforebegin" label="'before_begin' and 'after_commit'">
```suggestion
<TabItem value="beforebegin" label="before_begin and 'after_commit">
```

2023-11-03 13:31 UTC, mirnawong1 commented on website/docs/reference/resource-configs/pre-hook-post-hook.md
> +<TabItem value="dictionary" label="Use a dictionary'">
```suggestion
<TabItem value="dictionary" label="Use a dictionary">
```

2023-11-06 18:41 UTC, mirnawong1 commented
Waiting on team for feedback and will follow up this week

2023-11-07 23:07 UTC, patkearns10 requested changes
Looks good to me, but I would suggest making this less open to interpretation as well.

2023-11-07 23:07 UTC, patkearns10 commented on website/docs/reference/resource-configs/pre-hook-post-hook.md
> +  - Important note: Do not use this syntax if you are using a database where dbt does not use transactions by default. This includes databases like Snowflake, BigQuery, and Spark or Databricks.
```suggestion
  - Important note: Do not use this syntax if you are using a database where dbt does not support transactions. This includes databases like Snowflake, BigQuery, and Spark or Databricks.
```

2023-11-08 11:15 UTC, mirnawong1 commented
hey @patkearns10 , thanks so much for that and folded in your feedback - can you give it a look and approve? thank you again!

2023-11-08 21:29 UTC, patkearns10 approved these changes
🌵 LGTM!

2023-11-08 21:29 UTC, merged