Blog post addition: Serverless dlt + dbt project
fishtown-analytics/docs.getdbt.com pull request #4658
Opened 2023-12-15 15:42 UTC by euanjohnston-dev

## What are you changing in this pull request and why?

PR related to blog post ticket raised here: (https://github.com/dbt-labs/docs.getdbt.com/issues/4657).

2024-01-09 00:37 UTC, joellabes requested changes
Hey @euanjohnston-dev this is coming along nicely! Thanks for opening the issue and PR, and thanks for your patience over the holiday break. 

Most of the changes I've made are typo fixes or small clarifications, but there's a couple of places I did some more significant reworking. If it doesn't feel totally in your voice, feel free to make further changes. 

There's also a bunch of general comments where I think you need to provide a bit more context. The article is interesting but doesn't always make sense if you're coming into it without full context. 

Let me know if you've got questions about any of the comments, either here or on the dbt Community Slack.

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- An EtL pipeline. The little t stands for normalisation, such as transforming strings to dates or unpacking nested structures.
I assume this list is incomplete since it only has one element?

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +Due to the complexity of deduplication, we needed to add a human element to confirm the deduplication. This is reflected in the diagram below:
How does the diagram reflect it? I assume you're talking about the fact that it has to send a Slack alert, but it's not explicit anywhere

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +Due to the complexity of deduplication, we needed to add a human element to confirm the deduplication. This is reflected in the diagram below:
Reading further, this turns out to not be the case - the human element is actually manually fixing things in GSheets. It would be worth clarifying

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +To make our pipeline more “production ready”, we could make some improvements:
You say "could make", but it looks like you _did make_ these improvements, right? So I don't think this section is necessary as currently laid out. 

If you wanted to talk about the Slack notification setup you created, that could make sense in a different context. E.g. you could talk about dlt's extensibility and use this as an example

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +<Lightbox src="/img/blog/serverless-free-tier-data-stack-with-dlt-and-dbt-core/map_screenshot.png" width="70%" title="Dashboard mapping overview" />
This is cool!

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- I did have a small hiccup with the google sheets connector assuming an oauth authentication over my desired sdk but this was relatively easy to rectify.
If it's a one-line fix in a config file, it would be nice to either post the line of code here or link to whatever documentation/Stack Overflow post you used to solve your problem, as a pointer to whoever tries to replicate your work and [has the same issue](https://xkcd.com/979/)

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +## dlt
```suggestion
### dlt
```

I assume this is meant to be nested under the learnings section?

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +## dbt
```suggestion
### dbt
```
Same here

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +</aside>
```suggestion
💡 In this article, we explore how we can use dlt + dbt core in a serverless, free tier data stack by using Google Cloud Functions. I use this setup for a personal project where I try to get property prices to me and my partner make an informed purchase.
```

We don't have any special styling for `aside` blocks so this doesn't do anything

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +## The starting point
I'd move this section to the top of the article - it lays out clearly what the purpose of this work is, and sets the context for why it's important before diving into the technical implementation

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +**The problem**: There is no reference data for the real estate market - how many houses are being sold, for what price? nobody knows except the property office and maybe the banks, and they don’t te
```suggestion
**The problem**: There is no reference data for the real estate market in Portugal - how many houses are being sold, for what price? nobody knows except the property office and maybe the banks, and they don’t tell.
```

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +**The tools:** I want to be able to run my project on `google cloud functions` due to the generous free tier. I will try `dlt` for ingestion, which I wanted to test for some time. And for transformat
```suggestion
**The tools:** I want to be able to run my project on [Google Cloud Functions](https://cloud.google.com/functions) due to the generous free tier. [dlt](https://dlthub.com/) is a new Python library for declarative data ingestion which I have wanted to test for some time. Finally, I will use dbt Core for transformation.
```
Reshuffled this a bit to avoid the repetition from the earlier bullet.

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +Unfortunately, there are way fewer properties than ads - it seems many real estate companies re-post the same ad that others do, with intentionally different data and often misleading bits of info. T
This is the second _Unfortunately_ in two sentences - consider a rephrase. Either just changing to something like Frustratingly, or saying something like "As I started browsing, I quickly discovered that there are way fewer properties than ads"

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +So it seems if I want to collect some information I will need to
```suggestion
So it seems if I want to have reliable information on the state of the market I will need to 
```

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +For ingestion, we use a couple of sources
A general comment: throughout the article you switch back and forth from "we" to "I". Since this was a solo project, and it's not a tutorial so much as a writeup of your learnings, I'd suggest standardising on "I".

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +For transforming I use my favorite solution, dbt core. For running and orchestrating dbt core on cloud functions, I am using dlt’s dbt core runner. The benefit of the runner in this context is that I
It would be nice to have a bit of context of what transformations you're running here. How does using dbt map back to your original goals of deduplicating the property listings? Does it catch most of the issues for you, leaving you to only have to manually resolve the outliers? A screenshot of the DAG from dbt docs serve might help to contextualise everything.

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +No surprises there. I developed the package locally, and to deploy to cloud functions I injected credentials to dbt via the dlt runner. This meant I could re-use the setup I did for the other dlt pip
```suggestion
No surprises there. I developed the project locally, and to deploy to cloud functions I injected credentials to dbt via the dlt runner. This meant I could re-use the setup I did for the other dlt pipelines.
```
You use package in a few places (I haven't added comments on all of them though), but i think you're talking about a dbt project? Packages are technically projects as well, but they're imported via packages.yml.

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +		# make an authenticated connection with dlt
Does this mean you're using dlt to create an authenticated connection (presumably to the warehouse?), or that you're creating an authenticated connection to dlt?

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +DLT feels like the perfect solution for anyone who has scratched the surface of python development. To be able to have schema’s ready for transformation in such a short space of time is truly… transf
```suggestion
dlt feels like the perfect solution for anyone who has scratched the surface of python development. To be able to have schemas ready for transformation in such a short space of time is truly… transformational. As a freelancer, being able to accelerate the development of pipelines is a huge benefit within companies who are often frustrated with the amount of time it takes to start ‘showing value’.
```

2024-01-09 00:37 UTC, joellabes commented on website/blog/authors.yml
> +  organization: Freelancer
```suggestion
```
Organization is optional

2024-01-09 00:37 UTC, joellabes commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- gsheets deduplication pipeline https://github.com/euanjohnston-dev/gsheets_check_pipeline
```suggestion
First, I ingest home listings from the Idealista API, accessed through [API Dojo's freemium wrapper](https://rapidapi.com/apidojo/api/idealista2). The dlt pipeline I created for ingestion is in [this repo](https://github.com/euanjohnston-dev/Idealista_pipeline).

After an initial round of transformation (described in the next section), the deduplicated data is loaded into BigQuery where I can query it from the Google Sheets client and manually review the deduplication. 

When I'm happy with the results, I use the [ready-made dlt Sheets source connector](https://dlthub.com/docs/dlt-ecosystem/verified-sources/google_sheets) to pull the data back into BigQuery, [as defined here](https://github.com/euanjohnston-dev/gsheets_check_pipeline).
```

Reworked this a bit to remove the naked links and make the Google Sheets section clearer - we're in the ingestion section, but you were talking about exposing data to GSheets for manual annotation.

2024-01-09 09:29 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +		# make an authenticated connection with dlt
Yes the connection is to the warehouse sorry if that comes across a little unclear. The destination parameter specifies the type of database to which the data will be loaded.

2024-01-09 09:41 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- I did have a small hiccup with the google sheets connector assuming an oauth authentication over my desired sdk but this was relatively easy to rectify.
So this is a one line config file issue but this wasn't an issue that was able to be replicated. My fix was to explicitly state the object as GcpServiceAccountCredentials in the __init__.py file for the source. Honestly speaking I felt it overkill to go into details on this and would detract from the core article but adding provided balance to the positives. I would suggest either it stays as is or we remove it.

2024-01-09 09:42 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +<Lightbox src="/img/blog/serverless-free-tier-data-stack-with-dlt-and-dbt-core/map_screenshot.png" width="70%" title="Dashboard mapping overview" />
Thank you :)

2024-01-09 12:39 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- An EtL pipeline. The little t stands for normalisation, such as transforming strings to dates or unpacking nested structures.
I've rounded this out a bit to give a broader overview into the pipeline and then added additional details later.

2024-01-09 12:39 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +Due to the complexity of deduplication, we needed to add a human element to confirm the deduplication. This is reflected in the diagram below:
Have removed this element and discussed the gsheets element later in greater detail.

2024-01-09 12:40 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +To make our pipeline more “production ready”, we could make some improvements:
Good point I've changed this around to mention the addition.

2024-01-09 12:41 UTC, euanjohnston-dev commented on website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md
> +- I did have a small hiccup with the google sheets connector assuming an oauth authentication over my desired sdk but this was relatively easy to rectify.
On reflection I have briefly referenced this if people were to stumble into the same issue.

2024-01-12 03:40 UTC, joellabes commented
Thanks for the updates @euanjohnston-dev! I will review next week and we should be able to get this up!

2024-01-12 14:13 UTC, euanjohnston-dev commented
No worries, thank you for all your help on this. Have a great weekend!

best,

Euan

On Fri, Jan 12, 2024 at 4:40 AM Joel Labes ***@***.***> wrote:

> Thanks for the updates @euanjohnston-dev
> <https://github.com/euanjohnston-dev>! I will review next week and we
> should be able to get this up!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dbt-labs/docs.getdbt.com/pull/4658#issuecomment-1888385078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOKSWQIOWA3XGTDMMXRFUNLYOCWD3AVCNFSM6AAAAABAWUGES6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBYGM4DKMBXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-15 04:34 UTC, joellabes approved these changes

2024-01-15 04:34 UTC, merged

2024-01-15 04:34 UTC, joellabes commented
It's up!