feature: add new dynamic table paramaters
fishtown-analytics/docs.getdbt.com pull request #4835
Opened 2024-01-31 10:11 UTC by HenkvanDyk

## What are you changing in this pull request and why?

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/static/_redirects`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

2024-07-30 21:24 UTC, matthewshaver commented on website/docs/reference/resource-configs/snowflake-configs.md
> +    [refresh_mode]
```suggestion
    [refresh_mode](#refresh-mode)
```

2024-07-30 21:27 UTC, matthewshaver commented
@HenkvanDyk and @dataders what is the status of this draft? Should we move forward here?

2024-09-19 00:22 UTC, runleonarun requested changes
Hey @matthewshaver I noticed they have a [new PR](https://github.com/dbt-labs/dbt-snowflake/pull/1081/files) for this work. Removing `comment` per pr#1081

2024-09-19 00:22 UTC, runleonarun commented on website/docs/reference/resource-configs/snowflake-configs.md
> +| [`comment`](#comment)                                     | `<string>` | no       |         | n/a                       |
Per https://github.com/dbt-labs/dbt-snowflake/pull/1081 we removed `comment`
```suggestion
```

2024-09-19 00:22 UTC, runleonarun commented on website/docs/reference/resource-configs/snowflake-configs.md
> +### Comment
per https://github.com/dbt-labs/dbt-snowflake/pull/1081 removing `comment`
```suggestion
```

2024-09-19 00:22 UTC, runleonarun commented on website/docs/reference/resource-configs/snowflake-configs.md
> +Specifies a comment for the dynamic table.
per https://github.com/dbt-labs/dbt-snowflake/pull/1081 removing `comment`
```suggestion
```

2024-10-25 10:05 UTC, closed without merging

2024-10-25 10:07 UTC, HenkvanDyk commented
docs added here:
https://github.com/dbt-labs/docs.getdbt.com/issues/5678