Describes regional locations too for 'location'
fishtown-analytics/docs.getdbt.com pull request #491
Opened 2020-12-22 07:17 UTC by yu-iskw

## Description & motivation
`location` for BigQuery profiles can accept not only multi-regional locations, but also regional locations, because the location information is just passed to `google.cloud.bigquery.Client`.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [ ] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2020-12-23 21:04 UTC, clrcrl requested changes
Thanks for this PR! I made some suggestions to wording, but the information is spot on!

2020-12-23 21:04 UTC, clrcrl commented on website/docs/reference/warehouse-profiles/bigquery-profile.md
> +      location: US # Optional, one of US or EU / one of regional locations
```suggestion
      location: US # Optional, one of US or EU, or a regional location
```

2020-12-23 21:04 UTC, clrcrl commented on website/docs/reference/warehouse-profiles/bigquery-profile.md
> +`location` can accept one of multi-regional locations or one of regional locations, as [the google cloud official documentation](https://cloud.google.com/bigquery/docs/locations) describes.
```suggestion
`location` may be iether a multi-regional location (e.g. `EU`, `US`), or a regional location (e.g. `us-west2` ) as per the [the BigQuery documentation](https://cloud.google.com/bigquery/docs/locations) describes.
```

2020-12-24 02:11 UTC, yu-iskw commented
Thank you for the suggestions. I have taken them.

2021-01-04 14:57 UTC, clrcrl approved these changes
Thanks for this!

2021-01-04 14:57 UTC, merged