update version block to display content
fishtown-analytics/docs.getdbt.com pull request #5154
Opened 2024-03-25 09:13 UTC by mirnawong1

this PR fixes the version block so that the header AND content displays for v1.8 and higher. previously the header was displaying in the sidebar for all versions, but the actual content wasn't. this was a bit confusing and not the intended experience.

**Update**
version block was for 1.8 and left that in there. this pr now fixes the broken link in the migration guide.

2024-03-27 04:41 UTC, matthewshaver commented
@mirnawong1 The version blocks were intentional. The ability to use both `test:` and `data_test:` is only available in v1.8. In v1.9 you won't be able to use `test:` anymore and we will have different messaging.

2024-03-27 14:52 UTC, mirnawong1 commented
> @mirnawong1 The version blocks were intentional. The ability to use both `test:` and `data_test:` is only available in v1.8. In v1.9 you won't be able to use `test:` anymore and we will have different messaging.

got it, thought it was the case based on [my update above](https://github.com/dbt-labs/docs.getdbt.com/pull/5154#issue-2205250926) so I'll remove the version change and keep the rest since the link for data test syntax is actually broken.

2024-03-27 14:56 UTC, mirnawong1 commented
hey @matthewshaver - can you rereview? thanks!

2024-03-27 20:37 UTC, nghi-ly commented on website/docs/docs/dbt-versions/core-upgrade/01-upgrading-to-v1.8.md
> +The `tests:` syntax is changing to reflect the addition of unit tests. Start migrating your [data test](/docs/build/data-tests#new-data_tests-syntax) YML to use `data_tests:` after you upgrade to v1.
this anchor link is still broken -- doesn't take me to the section directly

curious, i wonder if the code font in the section title is the root cause

2024-03-27 20:37 UTC, nghi-ly requested changes
this anchor link is still broken -- doesn't take me to the section directly

curious, i wonder if the code font in the section title is the root cause

2024-03-28 09:21 UTC, mirnawong1 commented
oh damn, i'll test it again. i wonder if it has something to do with the version of the doc. are you on v1.8? or maybe it has something to do with the colon 👀  will test!

2024-03-28 09:43 UTC, mirnawong1 commented
ok i've tried removing the colon, adding backets (e.g {new-data_tests-syntax}), changing it to 'new data tests syntax' without any characters or underscore, and removing the versions -- and nothing is working 🥲  i wonder if it has anything to do with the right toc but OR the fact that 1.8 is beta? idk

going to open an asana ticket for the frontend team: https://www.loom.com/share/a43cd0e46e984c6498a081e6cdfc7c9d?sid=f5d9fbd0-0617-406b-bd29-f3ca6d347749

2024-03-28 09:47 UTC, mirnawong1 commented
asana task here: https://app.asana.com/0/1200099998847559/1206949105408562/f

2024-04-10 13:42 UTC, mirnawong1 commented on website/docs/docs/build/data-tests.md
> +The `tests` config has been renamed to `data_tests` in dbt version 1.8. To read more about this change, switch to version v1.8 in the documentation navigation menu.
```suggestion
In dbt version 1.8, we updated the `tests` configuration to `data_tests`. For detailed information on this update, please select version v1.8 from the documentation navigation menu
```

2024-04-10 13:43 UTC, mirnawong1 commented on website/docs/docs/build/data-tests.md
>  Data tests were historically called "tests" in dbt as the only form of testing available. With the introduction of unit tests in v1.8, it was necessary to update our naming conventions and syntax. As
```suggestion
Data tests were historically called "tests" in dbt as the only form of testing available. With the introduction of unit tests in v1.8, it was necessary to update our naming conventions and syntax. 

As of v1.8, `tests:` is still supported in your YML configuration files as an alias but will be deprecated in the future in favor of `data_tests:`. 
```

2024-04-16 08:57 UTC, mirnawong1 commented on website/docs/docs/build/data-tests.md
> +In dbt version 1.8, we updated the `tests` configuration to `data_tests`. For detailed information on this update, please select version v1.8 from the documentation navigation menu.
```suggestion
In dbt version 1.8, we updated the `tests` configuration to `data_tests`. For detailed information on this update select version v1.8 from the documentation navigation menu.
```

2024-04-16 15:42 UTC, matthewshaver commented on website/docs/docs/build/data-tests.md
> +There are generic tests defined in some open-source packages, such as [dbt-utils](https://hub.getdbt.com/dbt-labs/dbt_utils/latest/) and [dbt-expectations](https://hub.getdbt.com/calogica/dbt_expecta
```suggestion
There are generic tests defined in some open-source packages, such as [dbt-utils](https://hub.getdbt.com/dbt-labs/dbt_utils/latest/) and [dbt-expectations](https://hub.getdbt.com/calogica/dbt_expectations/latest/) &mdash; skip ahead to the docs on [packages](/docs/build/packages) to learn more!
```

2024-04-16 15:43 UTC, matthewshaver approved these changes

2024-04-16 16:21 UTC, nghi-ly approved these changes

2024-04-16 16:21 UTC, merged