synapse best practice guide
fishtown-analytics/docs.getdbt.com pull request #5496
Opened 2024-05-10 18:51 UTC by dataders

## What are you changing in this pull request and why?

as part of launch Synapse in dbt Cloud, here's some best practices (related: #5435)

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/vercel.json`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

2024-05-15 20:17 UTC, jasnonaz requested changes
Per notion - let's make this a developer blog. Let's move over to dev blog format then get ready to roll

2024-05-16 22:39 UTC, dataders commented on website/blog/2024-05-17-synapse-best-practices.md
> +description: "How to get started with Azure Synapse on dbt Cloud"
@jasnonaz would love your input on `title` and `description`

2024-05-17 19:57 UTC, jasnonaz approved these changes
Approving with the fixes we made live on call

2024-05-17 19:57 UTC, jasnonaz commented on website/blog/2024-05-17-synapse-best-practices.md
> +description: "How to get started with Azure Synapse on dbt Cloud"
maybe some tips for getting started

2024-05-17 20:47 UTC, merged