updates the expandable component
fishtown-analytics/docs.getdbt.com pull request #5531
Opened 2024-05-20 12:45 UTC by mirnawong1

this pr iterates on the expandable component to improve the user experience based on some feedback [slack thread](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1714405513625989):

- separated the expandable component from the headerLinkCopy.js file as i think that was conflicting with the behavior.
- allows copying and text highlighting inside the expandable
- added separate code for a copy link pop up/close behavior.
- added css info so expandable alt_header text is black when using details theme.

2024-05-20 12:50 UTC, mirnawong1 commented on website/src/components/expandable/styles.module.css
> +    margin-bottom: 10px;
fixed margin bc spacing was too wide in between expandables.

2024-05-22 17:25 UTC, john-rock requested changes
Hey @mirnawong1 nice work!

I only have one small request to adjust the case of the component to follow React's standards.

2024-05-22 17:25 UTC, john-rock commented on website/src/components/expandable/index.js
> +    .replace(/-+$/, '');
I'm in the camp of leaving the comments here, especially for chained regex, but not considering that as a blocker!

2024-05-22 17:25 UTC, john-rock commented on website/src/components/expandable/index.js
> +}, [anchorId]);
Nice 😎

2024-05-22 17:25 UTC, john-rock commented on website/src/components/expandable/index.js
> +  if (!alt_header) { return null; }
We should capitalize Expandable here to follow React component naming conventions

React components are regular JavaScript functions except:
[Their names always begin with a capital letter.](https://react.dev/learn/your-first-component#recap)

2024-05-23 09:20 UTC, mirnawong1 commented on website/src/components/expandable/index.js
> +  if (!alt_header) { return null; }
oh thanks for sharing that -  that's great to know and sorry my previous components will have the bad practice 🙈

2024-05-23 09:33 UTC, mirnawong1 commented
hey @john-rock , thanks for that great feedback! I've folded in your changes and can you rereview when you have chance ? 🙏

2024-05-23 13:42 UTC, john-rock commented on website/src/components/expandable/index.js
> +  if (!alt_header) { return null; }
No worries!

2024-05-23 13:42 UTC, john-rock approved these changes
lgtm @mirnawong1 , nice work on this :shipit:

2024-05-23 13:54 UTC, mirnawong1 commented
thank you so much @john-rock !

2024-05-23 14:07 UTC, merged

2024-05-23 14:40 UTC, mirnawong1 commented
@john-rock , i think i need to revert this pr: https://docs.getdbt.com/docs/collaborate/dbt-explorer-faqs the faqs aren't appearing correctly