Reorganize the deployment-tools.md file
fishtown-analytics/docs.getdbt.com pull request #5619
Opened 2024-06-05 22:45 UTC by nghi-ly

## What are you changing in this pull request and why?

Audit the deployment-tools.md file and reorganize it.

closes https://github.com/dbt-labs/docs-internal/issues/603

## Checklist
- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Needs review from DX eng

2024-06-05 23:07 UTC, joellabes requested changes
Two comments otherwise lgtm!

2024-06-05 23:07 UTC, joellabes commented on website/docs/docs/deploy/deployment-tools.md
> +The following are examples of
This trails off

2024-06-05 23:07 UTC, joellabes commented on website/docs/docs/deploy/deployment-tools.md
> +If your organization uses [Dagster](https://dagster.io/), you can use the [dagster_dbt](https://docs.dagster.io/_apidocs/libraries/dagster-dbt) library to integrate dbt commands into your pipelines.
The rpc server is deprecated

```suggestion
If your organization uses [Dagster](https://dagster.io/), you can use the [dagster_dbt](https://docs.dagster.io/_apidocs/libraries/dagster-dbt) library to integrate dbt commands into your pipelines. This library supports the execution of dbt through dbt Cloud or dbt Core. Running dbt from Dagster automatically aggregates metadata about your dbt runs. Refer to the [example pipeline](https://dagster.io/blog/dagster-dbt) for details.
```

2024-06-06 21:32 UTC, joellabes approved these changes

2024-06-06 22:11 UTC, runleonarun approved these changes
This looks good!

2024-06-06 22:13 UTC, merged