Add macros in macros faq.
fishtown-analytics/docs.getdbt.com pull request #568
Opened 2021-02-19 02:06 UTC by VersusFacit

## Description & motivation
closes #166. Totally agree this should be documented in some way.

2021-03-01 19:08 UTC, clrcrl requested changes
I think I see people ask this for two reasons:
1. The example described here (where they just haven't tried it!)
2. They are trying to call a macro as an argument to another macro, and are getting hit by the ol' [nesting curlies](https://docs.getdbt.com/docs/building-a-dbt-project/dont-nest-your-curlies) problem

Let's try to cover both cases! That's on me though — I didn't scope the issue quickly, as I probably wrote it back in the one-person-team times

In general, I also encourage you to make the language less formal — as per our brand voice, we are happy using conjunctions, and I'd avoid using words that aren't commonly used ("deference" stuck out to me)

2021-03-01 19:08 UTC, clrcrl commented on website/docs/faqs/calling-macros-in-macros.md
> +{% endmacro %}
I'm a little confused by this — this doesn't look like valid jinja (regardless of the cyclic dependency)

Did you mean something more like this:

```suggestion
{% macro macro_a(column_name) %}
    {{ macro_b(column_name) }}
{% endmacro %}
```

2021-03-01 19:08 UTC, clrcrl commented on website/docs/faqs/calling-macros-in-macros.md
> +Yes. Macros can call other macros. Jinja will automatically seek out all macros defined in the project before attempting to deference a call to a macro. In other words, a macro that invokes another m
```suggestion
Yes. Macros can call other macros, check out this example:
```

I'd add this after the first example:
```
Note: the referenced macro can be defined:
- In the same file
- In another file in the same project
- Or in an installed [package](package-management) (in which case, you'll need to prefix the macro's name with the package name)

2022-06-07 15:48 UTC, NicolasPA commented on website/docs/faqs/calling-macros-in-macros.md
> +{% endmacro %}
I also had this question, I can confirm this suggestion works. @VersusFacit would you like to finish this PR, or should I create a new one?

2022-12-14 17:22 UTC, runleonarun commented
I am closing this PR and putting it in the backlog. Labeled with "icebox" so we can revisit at a later date.

2022-12-14 17:22 UTC, closed without merging