add video url to faq
fishtown-analytics/docs.getdbt.com pull request #5861
Opened 2024-07-30 09:20 UTC by mirnawong1

this pr adds a video url to also explain how to solve the job memory limit failure in job run and development

internal slack: https://dbt-labs.slack.com/archives/C05CJT5MJF2/p1722309301858119?thread_ts=1721059396.203019&cid=C05CJT5MJF2

2024-07-30 21:10 UTC, jeremyyeo requested changes

2024-07-30 21:10 UTC, jeremyyeo commented on website/docs/faqs/Troubleshooting/job-memory-limits.md
> +As an additional resource, check out [this example video](https://www.youtube.com/watch?v=sTqzNaFXiZ8), which demonstrates how to refactor the sample code by reducing the number of columns returned.
> columns returned

rows returned

2024-07-30 21:10 UTC, jeremyyeo commented on website/docs/faqs/Troubleshooting/job-memory-limits.md
>  There are various reasons why you could be experiencing this error. We recommend you review your data models to see if there are any opportunities to optimize or refactor them. For example, you can t
> There are various reasons why you could be experiencing this error. We recommend you review your data models to see if there are any opportunities to optimize or refactor them. For example, you can try to reduce the number of columns being selected, use `group` or `where` clauses to filter data early in the query, or use `limit` clauses to reduce the amount of data being processed.

There are various reasons why you could be experiencing this error but they are mostly the outcome of retrieving too much data back into dbt (via `run_query()` operations or similar macros, or even using database/schemas that have lots of other non-dbt related tables/views). You can try to reduce the amount of data / number of rows retrieved back into dbt by refactoring the SQL in your `run_query()` operation using `group`, `where` or `limit` clauses. Additionally, you can also use a database/schema with fewer non-dbt related tables/views.

2024-07-31 20:10 UTC, mirnawong1 commented on website/docs/faqs/Troubleshooting/job-memory-limits.md
> +As an additional resource, check out [this example video](https://www.youtube.com/watch?v=sTqzNaFXiZ8), which demonstrates how to refactor the sample code by reducing the number of columns returned.
```suggestion
As an additional resource, check out [this example video](https://www.youtube.com/watch?v=sTqzNaFXiZ8), which demonstrates how to refactor the sample code by reducing the number of rows returned. 
```

2024-07-31 20:12 UTC, mirnawong1 commented on website/docs/faqs/Troubleshooting/job-memory-limits.md
>  There are various reasons why you could be experiencing this error. We recommend you review your data models to see if there are any opportunities to optimize or refactor them. For example, you can t
```suggestion
There are various reasons why you could be experiencing this error but they are mostly the outcome of retrieving too much data back into dbt. For example, using the `run_query()` operations or similar macros, or even using database/schemas that have a lot of other non-dbt related tables/views. Try to reduce the amount of data / number of rows retrieved back into dbt by refactoring the SQL in your `run_query()` operation using `group`, `where`, or `limit` clauses. Additionally, you can also use a database/schema with fewer non-dbt related tables/views.


```

2024-07-31 20:12 UTC, mirnawong1 commented
thanks @jeremyyeo ! can you please have another look?

2024-07-31 22:24 UTC, jeremyyeo approved these changes

2024-07-31 22:24 UTC, merged