Updated breaking changes section
fishtown-analytics/docs.getdbt.com pull request #6119
Opened 2024-09-23 14:24 UTC by nataliefiann

Following this Git issue: https://github.com/orgs/dbt-labs/projects/14/views/35?pane=issue&itemId=65030468, i've created this PR regarding the updated breaking changes

## What are you changing in this pull request and why?

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [x] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

2024-09-23 15:17 UTC, matthewshaver commented on website/docs/docs/collaborate/govern/model-contracts.md
> +- Removing a contracted model constitutes a breaking change. A model is considered 'removed' if it is deleted, renamed, or disabled (by config: enabled):
Suggest leaving that example out as the "enabled" language might be confusing.
```suggestion
- Removing a contracted model constitutes a breaking change. A model is considered 'removed' if it is deleted, renamed, or disabled:
```

2024-09-23 15:17 UTC, matthewshaver commented on website/docs/docs/collaborate/govern/model-contracts.md
> +  - if the model is versioned, dbt will throw an error.
```suggestion
  - If the model is versioned, dbt will throw an error.
```

2024-09-23 15:17 UTC, matthewshaver commented on website/docs/docs/collaborate/govern/model-contracts.md
> +  - if the model is unversioned, dbt will raise a warning.
```suggestion
  - If the model is unversioned, dbt will raise a warning.
```

2024-09-23 15:33 UTC, matthewshaver approved these changes

2024-09-23 17:56 UTC, runleonarun requested changes
Just suggesting to add some clarity to the warning/error here!

Also, should we revise the wording here to match your wording? https://docs.getdbt.com/reference/resource-properties/versions#detecting-breaking-changes

2024-09-23 17:56 UTC, runleonarun commented on website/docs/docs/collaborate/govern/model-contracts.md
> +  - If the model is versioned, dbt will throw an error.
Hey @nataliefiann I had spun up a PR for this locally so happen to look at this and suggest these edits:
```suggestion
  - When you remove a versioned model, you see an error.
```

2024-09-23 17:56 UTC, runleonarun commented on website/docs/docs/collaborate/govern/model-contracts.md
> +  - If the model is unversioned, dbt will raise a warning.
```suggestion
  - When you remove an unversioned contract, you see a warning.
```

2024-09-30 10:57 UTC, nataliefiann commented on website/docs/docs/collaborate/govern/model-contracts.md
> +- Removing a contracted model constitutes a breaking change. A model is considered 'removed' if it is deleted, renamed, or disabled:
```suggestion

<VersionBlock firstVersion="1.9">

- Removing a contracted model constitutes a breaking change. A model is considered 'removed' if it is deleted, renamed, or disabled:
```

2024-09-30 10:59 UTC, nataliefiann commented on website/docs/docs/collaborate/govern/model-contracts.md
> +
```suggestion
</VersionBlock>
```

2024-10-01 13:18 UTC, nataliefiann commented
Closed off as Core project has been paused

2024-10-01 18:16 UTC, runleonarun approved these changes
LGTM! We can follow up on my comment

2024-10-01 18:55 UTC, dbeatty10 commented
> Just suggesting to add some clarity to the warning/error here!
> 
> Also, should we revise the wording here to match your wording? https://docs.getdbt.com/reference/resource-properties/versions#detecting-breaking-changes

Good catch! The relevant code is [here](https://github.com/dbt-labs/docs.getdbt.com/blob/ce4a8475fd65622e66ca34f77b5a0b2dd83e192f/website/docs/reference/resource-properties/versions.md?plain=1#L76-L81).

I've opened up a docs issue in https://github.com/dbt-labs/docs.getdbt.com/issues/6198 to see if these can be abstracted into a common snippet.

2024-10-01 18:57 UTC, dbeatty10 approved these changes

2024-10-01 19:00 UTC, merged