Snapshot config to define column names
fishtown-analytics/docs.getdbt.com pull request #6146
Opened 2024-09-25 12:19 UTC by nataliefiann

I've created this PR / added section to highlight new config allows users to define column names following this Git issue: https://github.com/orgs/dbt-labs/projects/14/views/35?pane=issue&itemId=80581863

## What are you changing in this pull request and why?

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [x] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

2024-09-25 13:46 UTC, mirnawong1 commented on website/docs/reference/snapshot-configs.md
> +You can use the following config to define the names of the columns that are created in the [snapshot table](/docs/build/snapshots#snapshot-meta-fields).
```suggestion
Use the following configuration to define the names of the columns created in the [snapshot table](/docs/build/snapshots#snapshot-meta-fields).
```

2024-09-25 13:51 UTC, mirnawong1 commented on website/docs/reference/snapshot-configs.md
> +- Update your config to:
```suggestion
- If you make subsequent updates to the config to rename the column, dbt will automatically rename snapshot columns and manages the migration of column names for each configuration change. For example:
```

2024-09-25 13:53 UTC, mirnawong1 commented on website/docs/reference/snapshot-configs.md
> +You can read through the section on [Defining column names](/docs/build/snapshots#define-column-names-in-snapshot-table) for more information.
the link doesn't take me to the right place? or for some reason i didn't see the 'define column names' section?

2024-09-27 18:28 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +#### Define column names in snapshot table
```suggestion
#### Customize meta column names in snapshot table
```

2024-09-27 18:28 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +Use the following configuration to define the names of the columns created in the [snapshot table](/docs/build/snapshots#snapshot-meta-fields).
```suggestion
Use the following configuration to customize the names of the meta columns dbt creates in the [snapshot table](/docs/build/snapshots#snapshot-meta-fields).
```

2024-09-27 18:29 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +snapshots:
Let's use the full example from the issue!

```
snapshots:
  my_project:
    +snapshot_meta_column_names={
      dbt_valid_from: start_date,
      dbt_valid_to: end_date,
      dbt_scd_id: scd_id,
      dbt_updated_at: updated_date
    }
```

2024-09-27 18:29 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +<File name='dbt_project.yml'>
let's also show the example from the issue on how to do this in the config block:

```
{{
    config(
      target_database='analytics',
      target_schema='snapshots',
      unique_key='id',

      strategy='timestamp',
      updated_at='updated_at',
      
      snapshot_meta_column_names={
        dbt_valid_from: start_date,
        dbt_valid_to: end_date,
        dbt_scd_id: scd_id,
        dbt_updated_at: updated_date
      }
    )
}}
```

2024-09-27 18:30 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +<File name='dbt_project.yml'>
we have some tab thing for other examples so you can see how to write a config in different places

2024-09-27 18:30 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +- If you make subsequent updates to the config to rename the column, dbt manages the migration of column names for each configuration change. For example:
This is not true.

See issue -> https://github.com/dbt-labs/docs.getdbt.com/issues/6112#issuecomment-2374659927

> we aren't doing anything for migration, so if a user renames the columns for a snapshot without updating an existing table, they will get an error. The recommendation is to use these settings for new snapshots, or to arrange to update their existing tables prior to committing a column name change.

2024-09-27 18:31 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +- When you run your snapshots, dbt handles the renames from `example_valid_from` to `test_valid_from` for you.
this is not true

2024-09-27 18:31 UTC, graciegoheen commented on website/docs/reference/snapshot-configs.md
> +- When you run your snapshots, dbt handles the renames from `example_valid_from` to `test_valid_from` for you.
same comment as above - this is not true

2024-09-27 18:32 UTC, graciegoheen requested changes
Left some comments - I think this needs more work. Please see docs issue for examples to include and callout that we do not handle the migration -> https://github.com/dbt-labs/docs.getdbt.com/issues/6112#issuecomment-2374659927

2024-10-01 13:20 UTC, nataliefiann commented
Closed off as Core project has been paused

2024-10-01 13:20 UTC, closed without merging