Added section to Python models doc to discuss third party packages following this the thread: https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1730272033637189
fishtown-analytics/docs.getdbt.com pull request #6418
Opened 2024-11-05 13:52 UTC by nataliefiann

## What are you changing in this pull request and why?

I have added a section to the Python models doc to discuss third party packages following this the thread: https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1730272033637189

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."
- [ ] The content in this PR requires a dbt release note, so I added one to the [release notes page](https://docs.getdbt.com/docs/dbt-versions/dbt-cloud-release-notes).

2024-11-05 14:46 UTC, mirnawong1 commented on website/docs/docs/build/python-models.md
> +#### Third-party snowflake packages
```suggestion
#### Third-party Snowflake packages
```

2024-11-05 14:50 UTC, b-per commented
Thanks! I think that overall this is the way we should show it and point to the relevant docs but I am just wondering if the example we show is the best one.

Most people will want to upload Python packages so that they can call their favorite functions. In this example we are currently loading a CSV file. It works but it is not going to be the reason why people will want to use the `imports` config and load it from a Snowflake stage.

2024-11-05 14:54 UTC, mirnawong1 commented on website/docs/docs/build/python-models.md
> +In this example, dbt is configured to locate the `iris.csv` file in the designated Snowflake stage, `@dbt_integration_test`.
```suggestion
This example uses `imports = ['@dbt_integration_test/iris.csv'],`, which tells dbt to locate the `iris.csv` file in the designated Snowflake stage, `@dbt_integration_test`.
```

2024-11-05 15:35 UTC, nataliefiann commented
Hiya @mirnawong1 and @b-per 

Thank you for reviewing this. It's much appreciated.

@b-per with ref to your feedback, I found the below example in the Snowflake doc which gives an example of installing a package with native code via importing from Stage. Would you recommend using this instead:

```
create or replace function native_module_test_zip()
returns string
language python
runtime_version=3.9
handler='compute'
imports=('@mystage/mycustompackage.zip')
as
$$
import os
import sys
def compute():
   from zipfile import ZipFile
   if os.path.exists('/tmp/mycustompackage'):
      shutil.rmtree('/tmp/mycustompackage')
   os.mkdir('/tmp/mycustompackage')
   zippath = os.path.join(sys._xoptions["snowflake_import_directory"], 'mycustompackage.zip')
   ZipFile(zippath).extractall('/tmp/mycustompackage')
   sys.path.insert(0, '/tmp/mycustompackage')
   #return os.listdir('/tmp/mycustompackage')
   import mycustompackage
   return mycustompackage.mycustompackage()
$$;
```

Kind Regards
Natalie

2024-11-05 15:56 UTC, b-per commented
Yes, this looks much closer to what people might do! We just need to update it to make it a valid dbt model.

2024-11-05 21:48 UTC, nataliefiann commented
Thanks @b-per 

I did a little research and came upon this example:

```sql

{{ config(
    materialized = 'view'
) }}

create or replace function native_module_test_zip()
returns string
language python
runtime_version=3.9
handler='compute'
imports=('@mystage/mycustompackage.zip')
as
$$
import os
import sys
from zipfile import ZipFile
import shutil

def compute():
   if os.path.exists('/tmp/mycustompackage'):
      shutil.rmtree('/tmp/mycustompackage')
   os.mkdir('/tmp/mycustompackage')
   zippath = os.path.join(sys._xoptions["snowflake_import_directory"], 'mycustompackage.zip')
   ZipFile(zippath).extractall('/tmp/mycustompackage')
   sys.path.insert(0, '/tmp/mycustompackage')
   
   # Import and call the function from mycustompackage
   import mycustompackage
   return mycustompackage.mycustompackage()
$$;
```
Would that suffice?

Kind Regards

2024-11-06 07:05 UTC, b-per commented
I don't think so, no. This is not a valid dbt Python model.

There are a few things to change. [Our docs](https://docs.getdbt.com/docs/build/python-models#defining-a-python-model) describe what a Python model needs to have (for example a `def model()`)

2024-11-06 12:01 UTC, nataliefiann commented
Querying example here: https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1730894409078339

2024-11-08 15:00 UTC, nataliefiann commented
Hiya @mirnawong1 @b-per 

I'm currently querying this in ask-adapters-support. I found this example:

```
def model(dbt, session):
    # Configure the model
    dbt.config(
        materialized="table",
        imports=["@mystage/mycustompackage.zip"],  # Specify the external package location
    )
    
    # Example data transformation using the imported package
    # (Assuming `some_external_package` has a function we can call)
    data = {
        "name": ["Alice", "Bob", "Charlie"],
        "score": [85, 90, 88]
    }
    df = pd.DataFrame(data)

    # Process data with the external package
    df["adjusted_score"] = df["score"].apply(lambda x: some_external_package.adjust_score(x))
    
    # Return the DataFrame as the model output
    return df
```

Mike Alfare advised: "I think mycustompackage.zip might need to be some_external_package.py. To be honest, this is not something I have seen before, but reviewing our functional tests, it seems like this could work. I'll see if I can find someone more familiar with this particular feature."

I thought I'd share here incase you had any ideas.

Kind Regards
Natalie

2024-11-11 10:43 UTC, b-per commented
I think that both `zip` and `py` files would technically work. but people wanting to use external libraries would use the `zip` approach.

Here are other examples in the internet with the `zip` option
- https://github.com/sparsh-ai/recohut/blob/21a635dc6a8f16d74632988d580530a9a4023699/docs/03-processing/lab-snowpark-churnpark/models/ml/features/int_user_encoded.py#L45
- https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30

[This snowflake page](https://community.snowflake.com/s/article/how-to-use-other-python-packages-in-snowpark) as well mentions the zip

Rather than waiting for more and more feedback I think that the best is to push the current version and update it later if need be. As it is, it is already providing some guidance on using the `imports` config which we didn't have before.

2024-11-11 14:00 UTC, b-per commented
Was the snippet completely changed from the one in this thread? The formatting doesn't look as good as the snippet you shared before.

2024-11-11 16:27 UTC, nataliefiann commented
Hiya @b-per 

Yep, I used the one you ref'd [here](https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30). I'll rework it.

Kind Regards

2024-11-12 12:21 UTC, b-per requested changes

2024-11-12 12:21 UTC, b-per commented on website/docs/docs/build/python-models.md
> +To use external libraries, you can also use the [`zip`](https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30) approach.
I don't think we need this line. The zip approach is already the one in the example, no?

2024-11-12 12:46 UTC, mirnawong1 commented on website/docs/docs/build/python-models.md
> +To use external libraries, you can also use the [`zip`](https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30) approach.
i agre w Benoit! maybe instead we should mention that users can also use the .py approach so they know fully what approaches they can use?

2024-11-12 12:47 UTC, mirnawong1 commented on website/docs/docs/build/python-models.md
> +To use a third-party Snowflake package that isn't available in Snowflake Anaconda, upload your package by following [this example](https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-
it read a little weird to me when you had the 'this example then, configure..' structure
```suggestion
To use a third-party Snowflake package that isn't available in Snowflake Anaconda, upload your package by following [this example](https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-packages#importing-packages-through-a-snowflake-stage), and then configure the `imports` setting in the dbt Python model to reference to the zip file in your Snowflake staging.
```

2024-11-12 12:48 UTC, mirnawong1 commented on website/docs/docs/build/python-models.md
> +Here’s a complete example configuration, including using `imports` in a Python model:
```suggestion
Here’s a complete example configuration using a zip file, including using `imports` in a Python model:
```

2024-11-12 13:02 UTC, nataliefiann commented on website/docs/docs/build/python-models.md
> +To use external libraries, you can also use the [`zip`](https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30) approach.
Thanks for the feedback @b-per I'll remove that

2024-11-12 13:03 UTC, nataliefiann commented on website/docs/docs/build/python-models.md
> +To use external libraries, you can also use the [`zip`](https://github.com/phdata/dbt_snowpark_sentiment_example/blob/2c5528278e14dba678fb7773cca2d47f8adbeb4d/models/reviews.py#L30) approach.
```suggestion

```

2024-11-12 13:12 UTC, mirnawong1 approved these changes
lgtm to me!

2024-11-12 13:17 UTC, b-per approved these changes

2024-11-12 13:40 UTC, merged