Adding tab borders
fishtown-analytics/docs.getdbt.com pull request #6593
Opened 2024-12-05 00:52 UTC by matthewshaver

## What are you changing in this pull request and why?

Enhancing tabs:
- Places borders around individual tabs
- Sets a unique background color for clicked and hovered tabs
- Puts a border around the entire table area so it's clear where tabbed content ends

Closes https://github.com/dbt-labs/docs.getdbt.com/issues/3889

## Checklist
- [ ] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."
- [ ] The content in this PR requires a dbt release note, so I added one to the [release notes page](https://docs.getdbt.com/docs/dbt-versions/dbt-cloud-release-notes).

2024-12-12 15:22 UTC, mirnawong1 reviewed
looks good to me @matthewshaver !

2024-12-12 19:42 UTC, JKarlavige requested changes
Thanks for taking this on Matt. Left some comments with some recommended adjustments. To try and summarize them i'll list them below:
- Swapping hard-coded hex values for available color variables at the top of this file
- Adjusting tab text color on hover
- Adjusting tab border color on hover
- Adjusting section border color in light mode 

Let me know if you have any questions!

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
Rather than using hard-coded hex values, can we choose from the existing variables available at the top of this `custom.css` file? That will help us stay within our brand colors, while also making it easier to update colors across the board if needed down the road.

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  background-color: #f9fbfc; /* Sets the tab color the same as the file borders */
In an effort to reduce the amount of custom colors used, would we be able to swap this with the `var(--color-white)` variable. That color is close enough to white where it shouldn't be too noticeable.

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  border: 2px solid #ccc;
Same note about using available color variables here, can we swap all uses of `#ccc` with a similar color currently available as a variable?

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  background-color: #000000;
To avoid using black (not a brand color), can we swap this and anywhere #000 is used with `--color-primary-blue`, which is set to `#262a38`?

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  background-color: #D95B3B;
`#d95b3b` is not an available brand color. Could we swap this with `#DE5D43` or `#ff694a`? `#ff694a` has a variable already, but a new variable would need to be created for `#DE5D43` if you go with that one.

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  border: 1px solid #000000;
In light mode, can we use a lighter color for the border? The `var(--ifm-toc-border-color)` variable might be a good option, which is the current border color for the table of contents.

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  background-color: #D95B3B;
Also, on hover, the lighter text is still set on the tab while the orange background is applied. This doesn't pass the WCAG accessibility check for contrast [link here](https://webaim.org/resources/contrastchecker/). The text color may need to be updated on hover to match the color when the tab is active.
![image](https://github.com/user-attachments/assets/20851b6a-6d40-4c50-bcc8-24a4eac6db45)

2024-12-12 19:42 UTC, JKarlavige commented on website/src/css/custom.css
> +  background-color: #D95B3B;
And on hover, can we have the border color update to match the background color as well? Similar to how the border updates for the active tab.

2025-02-06 14:54 UTC, JKarlavige commented
Hey @matthewshaver, hope it's okay but I pushed a commit swapping the background color for the tabs from orange to teal. The orange wasn't passing accessibility tests with white text (when in dark mode), and I found the contrast between orange background and dark text a bit much.

New preview is building now, if all looks good i'll give it the approval. Let me know if you have any thoughts/concerns with that background color adjustment!

![image](https://github.com/user-attachments/assets/dac62a9d-2600-402e-b3b8-93a1e666f88f)

2025-02-06 14:55 UTC, JKarlavige approved these changes
lgtm! 🚢

2025-02-06 16:36 UTC, matthewshaver commented
@JKarlavige I like that color swap and we of course want to stay accessible to the widest audience possible. Thank you for making that change. I'll implement it elsewhere we used the orange (which was a choice to stay with our orange branding, but we're not committed to it).

2025-02-06 16:39 UTC, merged