add missing snapshot yaml examples
fishtown-analytics/docs.getdbt.com pull request #6674
Opened 2024-12-16 15:12 UTC by mirnawong1

Some of the resources listed under the general config pages don't have the updated 1.9+ YAML configs listed or mentioned. 

This PR updates the snapshot tabs to show the YAML configuration for the resources missing it.

Resolves #6382

---
🚀 Deployment available! Here are the direct links to the updated files:

- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/alias
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/contract
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/database
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/enabled
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/group
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/persist_docs
- https://docs-getdbt-com-git-add-snapshot-yaml-dbt-labs.vercel.app/reference/resource-configs/schema

2024-12-19 23:18 UTC, runleonarun requested changes
@mirnawong1 I just had some minor questions

2024-12-19 23:18 UTC, runleonarun commented on website/docs/reference/resource-configs/enabled.md
> +<File name='snapshots/properties.yml'>
Should we version this for 1.9 as well?

2024-12-19 23:18 UTC, runleonarun commented on website/docs/reference/resource-configs/schema.md
> +In a `snapshots/snapshot_name.yml` file:
This sentence doesn't flow from the previous sentence (`For example, if you have a group of marketing-related models and want to place them in a separate schema called `marketing`, you can configure it like this:
`) should it or should it be its own sentence?



Also, should this sentence be included in the version block?

2024-12-20 11:18 UTC, mirnawong1 commented on website/docs/reference/resource-configs/enabled.md
> +<File name='snapshots/properties.yml'>
yes good call, thank you!

2024-12-20 11:24 UTC, mirnawong1 commented on website/docs/reference/resource-configs/schema.md
> +In a `snapshots/snapshot_name.yml` file:
oh jeez, this doesn't even belong in this tab! that's my miss - thank you for catching this

2024-12-20 11:25 UTC, mirnawong1 commented on website/docs/reference/resource-configs/schema.md
> +In a `snapshots/snapshot_name.yml` file:
i need to move this to the snapshots tab

2024-12-20 22:02 UTC, runleonarun commented on website/docs/reference/resource-configs/alias.md
>  ```
```suggestion
```

```

2024-12-20 22:17 UTC, runleonarun approved these changes
Looks great!

2024-12-20 22:21 UTC, merged