Git providers supporting CI
fishtown-analytics/docs.getdbt.com pull request #6692
Opened 2024-12-19 14:17 UTC by nataliefiann

## What are you changing in this pull request and why?

I've created this PR with reference to this git issue: https://github.com/dbt-labs/docs.getdbt.com/issues/3704 to help users clarify which Git providers support CI.

In the PR, I have updated the Continuous integration page, created a card on the Git configuaration page and linked the table I created in the CI doc to it. I also created and used a snippet from https://docs.getdbt.com/docs/deploy/ci-jobs#trigger-a-ci-job-with-the-api

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [x] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."
- [ ] The content in this PR requires a dbt release note, so I added one to the [release notes page](https://docs.getdbt.com/docs/dbt-versions/dbt-cloud-release-notes).

2024-12-19 14:36 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +| **Git provider** | **Native dbt Cloud integration** |[**Automated CI job**](/docs/deploy/ci-jobs)|**Git import with URL**| **Information**|
going to link in the intro sentence above as it was looking odd i the table with the orange backgroun

![Screenshot 2024-12-19 at 14 35 27](https://github.com/user-attachments/assets/3d0a8426-5acd-4131-9665-f8f166fc148a)


```suggestion
| **Git provider** | **Native dbt Cloud integration** |**Automated CI job** |**Git import with URL**| **Information**|
```

2024-12-19 14:36 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +If your git provider has a native dbt Cloud integration, you can set up continuous integration (CI) jobs within dbt Cloud.
```suggestion
If your git provider has a native dbt Cloud integration, you can set up [continuous integration (CI) job](/docs/deploy/ci-jobs) within dbt Cloud.
```

2024-12-19 14:38 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +|All other git providers imported with a [git URL](/docs/cloud/git/import-a-project-by-git-url) ([BitBucket](/docs/cloud/git/import-a-project-by-git-url#bitbucket), [AWS CodeCommit](/docs/cloud/git/i
just wondering why we're saying bitbucket in the info column here? there are other git providers that dont have a native integration either and the guide isn't specifically for bitbucket. sugg keeping it general

```suggestion
|All other git providers imported with a [git URL](/docs/cloud/git/import-a-project-by-git-url) ([BitBucket](/docs/cloud/git/import-a-project-by-git-url#bitbucket), [AWS CodeCommit](/docs/cloud/git/import-a-project-by-git-url#aws-codecommit), and others)| ❌    | ❌    | ✅   | Refer to the [Customizing CI/CD with custom pipelines](/guides/custom-cicd-pipelines?step=1) guide to set up CI/CD.|
```

2024-12-19 14:42 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +### No native integration
not sure i understand why this section was turned into a snippet? and the snippet is only used once? snippets are usually for multiple uses in diff pages?

2024-12-19 14:43 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +### No native integration
also, the content is teh same as this here: https://docs.getdbt.com/docs/deploy/ci-jobs#trigger-a-ci-job-with-the-api so wondering if we need thi 'no native' section?

2024-12-19 14:44 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +|[Azure DevOps](/docs/cloud/git/setup-azure) <Lifecycle status="enterprise" />|  ✅|  ✅ |  ✅  | Organizations on the Team Plan can connect to Azure DeveOps via deploy key. Note, you won’t get the auto
wondering if we should add a line break so the lifecycle pills are on a 2nd line? do you think the git provider column looks a bit busy?

![Screenshot 2024-12-19 at 14 36 42](https://github.com/user-attachments/assets/8ad4c9bb-c753-469c-82c1-2b69e49d1ec3)


```suggestion
|[Azure DevOps](/docs/cloud/git/setup-azure)<br /> <Lifecycle status="enterprise" />|  ✅|  ✅ |  ✅  | Organizations on the Team Plan can connect to Azure DeveOps via deploy key. Note, you won’t get the automated CI jobs but you can still develop.|
```

2024-12-19 14:45 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +### No native integration
![Screenshot 2024-12-19 at 14 42 22](https://github.com/user-attachments/assets/ed644d55-f721-40bd-b264-c602ffe1fd64)

2024-12-19 15:04 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +If your git provider has a native dbt Cloud integration, you can set up continuous integration (CI) jobs within dbt Cloud.
also wondering why we're not using the [_git-providers-supporting-ci.md](https://github.com/dbt-labs/docs.getdbt.com/pull/6692/files#diff-32c06828b06474ea82f2b1b980556a620e87ff1e7acd8ea0080076223569f3d2) snippet and hardcoding the table instead?

2024-12-19 15:07 UTC, mirnawong1 commented on website/docs/docs/deploy/continuous-integration.md
> +
should we add a bit more context here about what the table explains, Git providers available to what plans? e.g. 

> If your git provider has a native dbt Cloud integration, you can set up continuous integration (CI) jobs within dbt Cloud. For providers without native integration, you can still use a Git URL. The following table explains the available integration options and their capabilities.

2024-12-20 10:56 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +If your git provider has a native dbt Cloud integration, you can set up [continuous integration (CI) job](/docs/deploy/ci-jobs) within dbt Cloud.
```suggestion
If your git provider has a native dbt Cloud integration, you can set up [continuous integration (CI) job](/docs/deploy/ci-jobs) within dbt Cloud. For providers without native integration, you can still use a Git URL. The following table explains the available integration options and their capabilities.
```

2024-12-20 11:49 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +|[GitHub](/docs/cloud/git/connect-github) <Lifecycle status="developer,team,enterprise" /> | ✅ | ✅ |  ✅         |
```suggestion
|[GitHub](/docs/cloud/git/connect-github)<br /> <Lifecycle status="developer,team,enterprise" /> | ✅ | ✅ |  ✅         |                                  
```

2024-12-20 11:49 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +|[GitLab](/docs/cloud/git/connect-gitlab) <Lifecycle status="developer,team,enterprise" /> | ✅ | ✅ |  ✅         |
```suggestion
|[GitLab](/docs/cloud/git/connect-gitlab)<br /> <Lifecycle status="developer,team,enterprise" /> | ✅ | ✅ |  ✅         |
```

2024-12-20 11:52 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +### No native integration
```suggestion

```

2024-12-20 11:52 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +import TiggeraCIJob from '/snippets/_trigger-a-ci-job.md';
```suggestion

```

2024-12-20 11:52 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +<TiggeraCIJob />
```suggestion

```

2024-12-20 12:00 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +
```suggestion
import TiggeraCIJob from '/snippets/_trigger-a-ci-job.md';
<TiggeraCIJob />
```

2024-12-20 12:11 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +import TiggeraCIJob from '/snippets/_trigger-a-ci-job.md';
```suggestion

```

2024-12-20 12:11 UTC, nataliefiann commented on website/docs/docs/deploy/continuous-integration.md
> +<TiggeraCIJob />
```suggestion

```

2024-12-20 14:08 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +|[Azure DevOps](/docs/cloud/git/setup-azure)<br /> <Lifecycle status="enterprise" />|  ✅|  ✅ |  ✅  | Organizations on the Team Plan can connect to Azure DeveOps via deploy key. Note, you won’t get th
@nataliefiann can only team plan users connect via the deploy key? what about dev plan?

2024-12-20 14:10 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +|[Azure DevOps](/docs/cloud/git/setup-azure)<br /> <Lifecycle status="enterprise" />|  ✅|  ✅ |  ✅  | Organizations on the Team Plan can connect to Azure DeveOps via deploy key. Note, you won’t get th
```suggestion
|[Azure DevOps](/docs/cloud/git/setup-azure)<br /> <Lifecycle status="enterprise" />|  ✅|  ✅ |  ✅  | Team plans can connect to Azure DeveOps using a deploy key. Note, you won’t be able to configure automated CI jobs but you can still develop. |
```

2024-12-20 14:11 UTC, mirnawong1 commented on website/snippets/_trigger-a-ci-job.md
> +If you're not using dbt Cloud’s native Git integration with [GitHub](/docs/cloud/git/connect-github), [GitLab](/docs/cloud/git/connect-gitlab), or [Azure DevOps](/docs/cloud/git/connect-azure-devops)
this is a silly question but why are you turning this into a snippet? and why isn't it be used if turning into a snippet?

2024-12-20 14:11 UTC, mirnawong1 commented on website/snippets/_trigger-a-ci-job.md
> +If you're not using dbt Cloud’s native Git integration with [GitHub](/docs/cloud/git/connect-github), [GitLab](/docs/cloud/git/connect-gitlab), or [Azure DevOps](/docs/cloud/git/connect-azure-devops)
it seems that that content is part of this section: https://docs.getdbt.com/docs/deploy/ci-jobs#trigger-a-ci-job-with-the-api

2024-12-20 14:16 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +If your git provider has a native dbt Cloud integration, you can set up [continuous integration (CI) job](/docs/deploy/ci-jobs) within dbt Cloud. For providers without native integration, you can sti
also for this snippet, to address Joel's issue and [my suggestion](https://www.notion.so/dbtlabs/Clarify-what-git-providers-support-CI-160bb38ebda780c090ddec8a3bbbfb1d?pvs=4#161bb38ebda7802cb985fade7084b021) -- should this snippet table also be used in the git configuration page (e.g. maybe the landing page or git url page)?

>t'd be useful to just have that listed in the CI docs as well as the configure git docs

2024-12-23 10:47 UTC, mirnawong1 approved these changes
looks much better, thanks for linking the snippet in other pages @nataliefiann !

2024-12-23 12:01 UTC, nataliefiann commented on website/snippets/_git-providers-supporting-ci.md
> +- For providers without native integration, you can still use the git clone method to import your git URL or leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trigg
```suggestion
- For providers without native integration, you can still use the git clone method to import your git URL or leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trigger a CI job to run.
```

2025-01-09 11:30 UTC, nataliefiann commented on website/docs/docs/cloud/git/git-configuration-in-dbt-cloud.md
> +
```suggestion
</div>
```

2025-01-10 00:54 UTC, joellabes requested changes, later dismissed
Content looks great, suggested a tweaked title but can be workshopped further as needed!

2025-01-10 00:54 UTC, joellabes commented on website/snippets/_git-providers-supporting-ci.md
> +- For providers without native integration, you can still use the git clone method to import your git URL or leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trigg
```suggestion
- For providers without native integration, you can still use the git clone method to import your git URL and leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trigger a CI job to run.
```

2025-01-10 00:54 UTC, joellabes commented on website/snippets/_git-providers-supporting-ci.md
> +## Git providers who support CI
```suggestion
## Availability of features by Git provider
```
Suggest a title like this instead, since we say that CI jobs are possible for any provider if you trigger it with the admin API.

2025-01-10 00:54 UTC, joellabes commented on website/docs/docs/cloud/git/git-configuration-in-dbt-cloud.md
> +    body="Learn which Git providers support CI"
```suggestion
    title="Availability of CI features by Git provider"
    body="Learn which Git providers have native support for Continuous Integration workflows"
```
Same comment as below - open to alternative phrasing on this though

2025-01-10 11:24 UTC, mirnawong1 commented on website/docs/docs/deploy/ci-jobs.md
> +import GitProvidersCI from '/snippets/_git-providers-supporting-ci.md';
i suggest placing the "Availability of features by Git provider" section right after "Prerequisites" but before "Set up CI jobs." that way, it balances visibility and relevance while maintaining a logical progression.

currently, i think it's placed in a weird place and has examples nested under it too

<img width="256" alt="Screenshot 2025-01-10 at 11 24 26" src="https://github.com/user-attachments/assets/fde5a0c4-6404-42ba-8b90-1144815d5fb6" />

2025-01-10 11:26 UTC, mirnawong1 commented on website/docs/docs/cloud/git/import-a-project-by-git-url.md
> +import GitProvidersCI from '/snippets/_git-providers-supporting-ci.md';
same comment as below:

i suggest placing the "Availability of features by Git provider" section right after "Git protocols" but before "Managing deploy keys" that way, it balances visibility and relevance while maintaining a logical progression.

currently, i think it's placed in a weird place and breaks up the git provider listing

<img width="244" alt="Screenshot 2025-01-10 at 11 26 20" src="https://github.com/user-attachments/assets/6f3d0719-9b15-4fb0-99e4-2e5e89ac3aec" />

2025-01-10 11:27 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +| **Git provider** | **Native dbt Cloud integration** | **Automated CI job**|**Git import with URL**| **Information**|
let's change this to git clone so it's consistent with the rest of the docs and our ui
```suggestion
| **Git provider** | **Native dbt Cloud integration** | **Automated CI job**|**Git clone**| **Information**|
```

2025-01-10 11:27 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +|All other git providers imported with a [git URL](/docs/cloud/git/import-a-project-by-git-url) ([BitBucket](/docs/cloud/git/import-a-project-by-git-url#bitbucket), [AWS CodeCommit](/docs/cloud/git/i
```suggestion
|All other git providers using [Git clone](/docs/cloud/git/import-a-project-by-git-url) ([BitBucket](/docs/cloud/git/import-a-project-by-git-url#bitbucket), [AWS CodeCommit](/docs/cloud/git/import-a-project-by-git-url#aws-codecommit), and others)| ❌    | ❌    | ✅   | Refer to the [Customizing CI/CD with custom pipelines](/guides/custom-cicd-pipelines?step=1) guide to set up continuous integration and continuous deployment (CI/CD).|
```

2025-01-10 11:29 UTC, mirnawong1 commented on website/snippets/_git-providers-supporting-ci.md
> +- For providers without native integration, you can still use the git clone method to import your git URL and leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trig
```suggestion
- For providers without native integration, you can still use the [Git clone method](/docs/cloud/git/import-a-project-by-git-url) to import your git URL and leverage the [dbt Cloud Administrative API](/docs/dbt-cloud-apis/admin-cloud-api) to trigger a CI job to run.
```

2025-01-10 11:29 UTC, mirnawong1 approved these changes

2025-01-10 12:07 UTC, nataliefiann commented
> Content looks great, suggested a tweaked title but can be workshopped further as needed!

Thanks Joel. I'm happy with the title change. And if you'd like it updated at a later date, I'm happy to make that change for you.

2025-01-10 12:08 UTC, merged