Replace 'one-off' by 'bespoke'
fishtown-analytics/docs.getdbt.com pull request #760
Opened 2021-08-10 14:11 UTC by MartinGuindon

Since the documentation has changed the terminology from data test to bespoke test and uses bespoke at the main heading in the main Tests docs (https://docs.getdbt.com/docs/building-a-dbt-project/tests#bespoke-tests), it is confusing to use `one-off test` here. I'm therefore proposing to update this to use `Bespoke` here as well.

## Description & motivation

## To-do before merge

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [ ] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2021-08-10 16:26 UTC, jtcohen6 commented
@MartinGuindon The truth is that I haven't yet decided on the final name for this test type, whether `bespoke` or `one_off` (or `specific` or `single_use`). There's some discussion about this over in https://github.com/dbt-labs/dbt/issues/3234, since we still need to change these for real in the Core codebase.

2021-08-10 17:16 UTC, MartinGuindon commented
> @MartinGuindon The truth is that I haven't yet decided on the final name for this test type, whether `bespoke` or `one_off` (or `specific` or `single_use`). There's some discussion about this over in [dbt-labs/dbt#3234](https://github.com/dbt-labs/dbt/issues/3234), since we still need to change these for real in the Core codebase.

Gotcha. Replied with my thoughts on the issue. :)

2022-01-14 21:02 UTC, runleonarun requested changes
Thank you for this edit! Looks like this was changed to singular so I made that change.

2022-01-14 21:02 UTC, runleonarun commented on website/docs/reference/resource-configs/store_failures.md
> +    { label: 'Bespoke test', value: 'bespoke', },
```suggestion
    { label: 'Singular test', value: 'singular', },
```

2022-01-14 21:02 UTC, runleonarun commented on website/docs/reference/resource-configs/store_failures.md
> +<TabItem value="bespoke">
```suggestion
<TabItem value="singular">
```

2022-01-14 21:02 UTC, runleonarun commented on website/docs/reference/resource-configs/store_failures.md
> +Configure a bespoke (data) test:
```suggestion
Configure a singular (data) test:
```

2022-01-14 21:06 UTC, runleonarun approved these changes
LGTM!

2022-01-14 21:06 UTC, merged