add info on downgrading dbt with pip
fishtown-analytics/docs.getdbt.com pull request #789
Opened 2021-08-27 20:13 UTC by sophiad96

## Description & motivation
I had a user reach out asking how to downgrade the version of dbt they were on using the CLI. They had used pip for installation. We already have instructions for changing versions of dbt with homebrew, but we didn't for pip (only for upgrading) so I wanted to add those to the docs as well!

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [X] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

2021-08-27 20:20 UTC, annafil commented
I'm so curious about why they needed to downgrade 💭 !

2021-08-27 20:32 UTC, sophiad96 commented
Great question @annafil! This user needed to downgrade because they had packages installed in their project that were not compatible with v0.20.1.

2022-12-22 14:28 UTC, runleonarun commented on website/docs/docs/get-started/pip-install.md
> +### Install dbt Core only
```suggestion
### Install dbt-core only
```

2022-12-22 14:37 UTC, runleonarun commented on website/docs/docs/get-started/pip-install.md
> +To upgrade dbt to its latest version, use:
```suggestion
You can upgrade versions of dbt Core by using an upgrade command on the Command line (CLI). For more information, see [Best practices for upgrading in Core versions](/docs/dbt-versions/core#best-practices-for-upgrading).

To upgrade dbt to the latest version:
```

2023-01-03 19:04 UTC, nghi-ly requested changes
thanks for adding this new content, @runleonarun ! sounds like it would be useful! 

left a few suggs. lemme know if you have questions on any of them!

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +You can upgrade or downgrade versions of dbt Core by using an upgrade command on the Command line (CLI). For more information, see [Best practices for upgrading in Core versions](/docs/dbt-versions/c
```suggestion
You can upgrade or downgrade versions of dbt Core by using the `--upgrade` option on the command line (CLI). For more information, see [Best practices for upgrading in Core versions](/docs/dbt-versions/core#best-practices-for-upgrading).
```

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +### Upgrade or downgrade dbt Core versions
```suggestion
### Change dbt Core versions
```

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +### Upgrade or downgrade dbt Core versions
sugg for something shorter. maybe "Update" but that could be synonymous to upgrade for a lot of people.

non blocking.

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +To downgrade to an older version, you'll want to use the command above while specifying the version you want to use. As an example:
```suggestion
To downgrade to an older version, specify the version you want to use. This command can be useful when you're resolving package dependencies. As an example:
```

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +The `upgrade` flag is used to change versions of dbt, regardless of whether you're upgrading or downgrading via pip.
```suggestion

```

2023-01-03 19:04 UTC, nghi-ly commented on website/docs/docs/get-started/pip-install.md
> +The `upgrade` flag is used to change versions of dbt, regardless of whether you're upgrading or downgrading via pip.
sugg: i don't think we need this sentence anymore if my sugg for the first sentence in the first paragraph is accepted. 

reason: redundant

or, at least, remove the passive voice in the sentence

2023-01-03 19:20 UTC, nghi-ly approved these changes

2023-01-03 19:21 UTC, merged