Update Docusaurus Version
fishtown-analytics/docs.getdbt.com pull request #862
Opened 2021-10-14 15:43 UTC by JKarlavige

## Description & motivation
[Asana Task](https://app.asana.com/0/1200099998847559/1201136871923005/f)

This is an effort to upgrade Docusaurus to the latest version (v2.0.0-beta.6) in order to utilize newer features on the platform.

Notes on a couple changes and new features:
- The new version has a new Algolia search, which functions a bit differently than the current search. This is visually different on both mobile and desktop as well. 
- There is also broken link checkers, which causes the build to fail by default. Since we have a 'bad-link' example on the /styles page, I changed this check to only warn of broken links. This allows the build to succeed. Using this link check, I updated/fixed all broken links which were flagged.
- The new version has some updated styles as well. I made adjustments to mirror our current site as much as possible, but some slight differences may be noticeable, for example with element padding/breakpoints/etc.
- Now that we will be on the latest version, it may be a good time to review the docs again to see what new features are available. A couple examples include the live coding component, as well as the ability to add a title to code examples (which we currently use a custom component for.)
- A number of duplicate slug warnings occur as well, both on this version and the live site. I will let these remain as is due to not knowing which version of the url should be used.

A side note:
The new Docusaurus requires a Node Version of > 12. This site was originally built on Node v10. I had to add a NODE_VERSION env variable to update the node version for this site. Just want to note that this is when that env variable was set.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [x] No: please ensure the base branch is `current`

[Link to preview](https://deploy-preview-862--docs-getdbt-com.netlify.app/)

2021-10-14 16:19 UTC, krevitt commented on website/src/css/custom.css
> +  text-decoration: underline;
Looks like this `underline` text-decoration on `.alert a` isn't being applied in the deploy preview ([looking at this page](https://deploy-preview-862--docs-getdbt-com.netlify.app/docs/dbt-cloud/cloud-quickstart)):

![image](https://user-images.githubusercontent.com/77362861/137357228-28e95832-64e7-415a-ac70-51fa9134c525.png)

![image](https://user-images.githubusercontent.com/77362861/137357255-b9039d49-49a9-4362-b65e-db7f88623c22.png)

2021-10-14 16:22 UTC, krevitt requested changes
Did a styling review and all looked good, outside of one link styling issue noted above.

2021-10-14 17:18 UTC, JKarlavige commented on website/src/css/custom.css
> +  text-decoration: underline;
Fix for this added

2021-10-18 13:31 UTC, lfracalossiFA approved these changes

2021-10-19 13:22 UTC, krevitt approved these changes

2021-10-19 13:27 UTC, merged