Fix error with Redshift cluster_id in profiles.yml
fishtown-analytics/docs.getdbt.com pull request #898
Opened 2021-11-04 15:25 UTC by jaypeedevlin

## Description & motivation
Per [thread in slack](https://getdbt.slack.com/archives/CBSQTAPLG/p1636036555299000) this seems to be an error in the documentation

2021-12-13 20:47 UTC, runleonarun requested changes, later dismissed
Hi @jaypeedevlin!

You change is much appreciated! I would like the dbt docs to standardize on all caps for code that requires the user to replace it. I'd also like to see a helpful explanation before the code snippet. I added my 2 cents, but please let me know if I should carry this over the finish line! 🙇🏻‍♀️

2021-12-13 20:47 UTC, runleonarun commented on website/docs/reference/warehouse-profiles/redshift-profile.md
> +      cluster_id: cluster_id
```suggestion
      cluster_id: CLUSTER_ID
```

2021-12-13 20:47 UTC, runleonarun commented on website/docs/reference/warehouse-profiles/redshift-profile.md
>      dev:
I also suggest we add something like this before the example profile:

> Set up your Redshift profile, replacing CLUSTER_ID with the unique identifier of the cluster in Redshift:

2021-12-13 20:47 UTC, runleonarun commented on website/docs/reference/warehouse-profiles/redshift-profile.md
>        iam_profile: data_engineer # optional
Below here, I also see 
>   db_groups: ['analysts']  

Should [`analysts`] become `ANALYSTS`  if we're standardizing on all caps for text that requires changing?

2021-12-16 18:06 UTC, jaypeedevlin commented
Hi @runleonarun, I'm totally onboard with these changes but unfortunately strapped for time at this busy time of year.  I would love it if you could bring this one home!

2022-09-22 13:55 UTC, mirnawong1 approved these changes

2022-09-22 14:08 UTC, mirnawong1 approved these changes

2022-09-22 14:09 UTC, merged

2022-09-22 14:10 UTC, mirnawong1 commented
thanks @jaypeedevlin and @runleonarun for flagging this and for your patience! gone ahead and merged this for you!