Update the-ide-git-button.md
fishtown-analytics/docs.getdbt.com pull request #924
Opened 2021-11-25 14:44 UTC by mirnawong1

Added a 'checkout branch' section as this was missing and a question cs gets often. i can't add the screenshot because i dont have the url so i'll attach it as a screenshot: 

Can you please add both screenshots below so we can provide users a visual of what the button and steps look like? thank you!

![Screenshot 2021-11-25 at 14 26 09](https://user-images.githubusercontent.com/89008547/143461309-8971b9d3-c7d5-473b-89dd-4a12d1a07444.png)

![Screenshot 2021-11-25 at 14 25 58](https://user-images.githubusercontent.com/89008547/143461328-98e31a6d-2e05-4e32-86c2-5f7d8fd3dcb5.png)

[](url)

## Description & motivation

## To-do before merge

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [ ] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

2022-02-03 12:22 UTC, mirnawong1 commented
hi @runleonarun and @sophiad96 do you folks mind checking this out to see if it's all ok?

2022-02-03 17:32 UTC, runleonarun requested changes
@mirnawong1 Let's upload these images together when you get a chance!

2022-02-03 17:32 UTC, runleonarun commented on website/docs/docs/dbt-cloud/cloud-ide/the-ide-git-button.md
> +<Lightbox src=" ![pull](https://user-images.githubusercontent.com/89008547/152341799-2118d743-57b9-4244-8cd2-1b7730f7ec6f.png)/>
@mirnawong1 This is using the images you uploaded in the issue, but I am hesitant to do this because GitHub can remove these images at any time. A best practice is to upload these images into the image directory: `"/img/docs/dbt-cloud/cloud-ide/`. Once you get GitHub Desktop setup, I will help you with that process!

2022-02-25 17:35 UTC, mirnawong1 commented on website/docs/docs/dbt-cloud/cloud-ide/the-ide-git-button.md
> +<Lightbox src=" ![select_branch](https://user-images.githubusercontent.com/89008547/152341705-0a0e3ee1-45bf-408e-820c-046f39c01ec7.png)/>
```suggestion
<Lightbox src="website/static/img/docs/dbt-cloud/cloud-ide/checkout_one.png"/>
```

2022-02-25 17:36 UTC, mirnawong1 commented on website/docs/docs/dbt-cloud/cloud-ide/the-ide-git-button.md
> +<Lightbox src=" ![pull](https://user-images.githubusercontent.com/89008547/152341799-2118d743-57b9-4244-8cd2-1b7730f7ec6f.png)/>
```suggestion
<Lightbox src="website/static/img/docs/dbt-cloud/cloud-ide/checkout_two.png"/>
```

2022-08-30 09:16 UTC, mirnawong1 commented
closing pull request as ide beta already contains this

2022-08-30 09:16 UTC, closed without merging