Clarify update instructions
fishtown-analytics/docs.getdbt.com pull request #977
Opened 2021-12-19 19:52 UTC by jasnonaz

## Description & motivation
Currently if you run dbt --version on the cli, you are directed to a url [docs.getdbt.com/docs/installation](docs.getdbt.com/docs/installation) which redirects to [https://docs.getdbt.com/dbt-cli/install/overview](https://docs.getdbt.com/dbt-cli/install/overview) and tells you that you can receive information about upgrading at that page. The issue is right now, this page is purely dedicated to installing dbt and doesn't give any information on how to upgrade. This PR adds links to some of the upgrading resources we have so that we can direct people who come here expecting upgrade information to the right place.
![image](https://user-images.githubusercontent.com/8147311/146688720-356a96b3-60c5-4294-b453-5ce716347d14.png)

2022-01-13 21:49 UTC, runleonarun requested changes

2022-01-13 21:49 UTC, runleonarun commented on website/docs/dbt-cli/install/overview.md
> +## Upgrading dbt
@jasnonaz I love the idea of adding an upgrade section. I think it's worthy of being its own page even if we only have pip instructions right now.

2022-09-06 22:59 UTC, nghi-ly commented
@jasnonaz : so sorry for the delay! to address our PR backlog better, the Docs team is going to dedicate time on a regular cadence to work on it. in the spirit of this, i opened this PR to see what I can do to help it along. 

looks like you created this PR in Dec 2021. is this change still needed? if it's no longer needed, we can close it.

2023-01-26 06:43 UTC, runleonarun commented on website/docs/dbt-cli/install/overview.md
> +## Upgrading dbt
Actually, I this is valuable information and we should get it added.

2023-01-26 06:53 UTC, runleonarun commented
Moved changes over to https://github.com/dbt-labs/docs.getdbt.com/pull/2759 instead of fixing merge conflicts.

2023-01-26 06:53 UTC, closed without merging